### ISSUE TITLE
Can't install via conda on Mac

### ISSUE THREAD

**Issue by jvavrek** [UCL/STIR#1004]
Poking around the documentation I didn't see anything suggesting the `conda` install wouldn't work on Mac. However, following the instructions [here](http://stir.sourceforge.net/wiki/index.php/Installing_STIR_with_conda), I get the following:
```bash
(stirenv) jvavrek:~$ conda install -c conda-forge stir
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - stir

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

It looks like [anaconda only hosts win-64 and linux-64-specific versions](https://anaconda.org/search?q=stir), whereas I would require an osx-64 or noarch version. Is this expected? Alternatively, could I get away with installing linux-64 on mac?

Other info:
```bash
$ python --version
Python 3.9.10
$ conda --version
conda 4.11.0
```

**Comment by KrisThielemans** [comment]
I have not succeeded in creating MacOS packages with conda. See https://github.com/conda-forge/stir-feedstock/issues/9, and several attempts there. As I have no access to a Mac (and no time), any help on getting that sorted would be very much appreciated. Comments in that issue there please, not here.

You can only install `linux-64` stuff on a mac via a Virtual Machine or docker. Unfortunately we are currently not creating up-to-date versions for either. It wouldn't be very hard to expand the related effort in CCP SyneRBI, see http://www.ccpsynerbi.ac.uk/downloads. That contains STIR, but currently neither its executables nor its own Python version. A while ago I made a branch to create a STIR-only VM https://github.com/SyneRBI/SyneRBI_VM/tree/STIR-exercises, but it's a bit out-of-date. Apologies.
