### ISSUE TITLE
Read GATE ROOT output into Python STIR

### ISSUE THREAD

**Issue by jvavrek** [UCL/STIR#1005]
I would like to read a listmode GATE output `.root` file into STIR's Python interface. Is there a way to do this completely programmatically in Python, or do I have to manually use the listmode utility executable `lm_to_projdata` and create a suitable ROOT header?

Ideally, I would like to do something like:
```py
import stir
proj_data = stir.lm_to_projdata("my_gate_output.root")
```
and then pass `proj_data` into the recons. However it doesn't look like much of the listmode functionality is exposed in Python.

**Comment by KrisThielemans** [comment]
This is Work in progress. I'm not sure about timelines yet. However, it won't be as simple as you hope. Currently, `LmToProjData` needs a template `projdata` as well as the listmode file (in this case `.hroot`, i.e. header for `.root`, as that doesn't contain enough info). That  could be made optional nowadays as we have https://github.com/UCL/STIR/blob/6312c07f1fdd50eb48eacdec12801f66525221e4/src/include/stir/listmode/ListModeData.h#L229. PR welcome 😉

**Comment by KrisThielemans** [comment]
#1007 provided the necessary SWIG changes. There is now also an example. Let us know if this works for you or not via the mailing list.

**Comment by jvavrek** [comment]
> #1007 provided the necessary SWIG changes. There is now also an example. Let us know if this works for you or not via the mailing list.

Can you update the conda distribution with the changes from #1007?
