### ISSUE TITLE
 `write_to_file` when the string name contains a dot "."

### ISSUE THREAD

**Issue by ClaireDelplancke** [UCL/STIR#1013]
see https://github.com/SyneRBI/SIRF/issues/1066

**Comment by robbietuk** [comment]
I think this is the same issue as I had in https://github.com/UCL/STIR/issues/648.

I suggest using underscore rather than a dot.

**Comment by ClaireDelplancke** [comment]
Indeed,  `sirf_image.write("test_1.0.hv")` works! Thanks @KrisThielemans !
