### ISSUE TITLE
CMake: is SILENT a component of HDF5?

### ISSUE THREAD

**Issue by paskino** [UCL/STIR#1037]
I'm building SIRF with CMake 3.17 and I get 

```
CMake Error at /opt/cmake-3.17.5-Linux-x86_64/share/cmake-3.17/Modules/FindHDF5.cmake:158 (message):
  SILENT is not a valid HDF5 component.
Call Stack (most recent call first):
  /opt/SIRF-SuperBuild/INSTALL/lib/cmake/STIRConfig.cmake:99 (find_package)
  src/CMakeLists.txt:89 (find_package)
```

which comes from `STIRConfig.cmake`.  What is `SILENT`? How's it written it seems to be a component of HDF5. Maybe you wanted to use `QUIET`? 

https://github.com/UCL/STIR/blob/b6bbff7a1376df78687849ae6cc05a890df8ad0c/src/cmake/STIRConfig.cmake.in#L75

**Comment by KrisThielemans** [comment]
yes, that has to be `QUIET`. sorry. Should have been caught by our CI but apparently isn't.

As I already committed 5.1 stuff on `master`, I guess I now have to branch off. Sigh

**Comment by KrisThielemans** [comment]
@paskino can you try the SB with `STIR_TAG=release_5.0`? https://github.com/UCL/STIR/tree/release_5.0

**Comment by paskino** [comment]
@KrisThielemans I think this will also fail as the position of `QUIET` is wrong, as it should come after the version number and before `COMPONENTS`. According to CMake [docs](https://cmake.org/cmake/help/v3.21/command/find_package.html) 

```
find_package(<PackageName> [version] [EXACT] [QUIET]
             [REQUIRED] [[COMPONENTS] [components...]]
             [OPTIONAL_COMPONENTS components...]
             [CONFIG|NO_MODULE]
             [NO_POLICY_SCOPE]
             [NAMES name1 [name2 ...]]
             [CONFIGS config1 [config2 ...]]
             [HINTS path1 [path2 ... ]]
             [PATHS path1 [path2 ... ]]
             [PATH_SUFFIXES suffix1 [suffix2 ...]]
             [NO_DEFAULT_PATH]
             [NO_PACKAGE_ROOT_PATH]
             [NO_CMAKE_PATH]
             [NO_CMAKE_ENVIRONMENT_PATH]
             [NO_SYSTEM_ENVIRONMENT_PATH]
             [NO_CMAKE_PACKAGE_REGISTRY]
             [NO_CMAKE_BUILDS_PATH] # Deprecated; does nothing.
             [NO_CMAKE_SYSTEM_PATH]
             [NO_CMAKE_SYSTEM_PACKAGE_REGISTRY]
             [CMAKE_FIND_ROOT_PATH_BOTH |
              ONLY_CMAKE_FIND_ROOT_PATH |
              NO_CMAKE_FIND_ROOT_PATH])

```

This is a problem also for `release_5.0` and both if CMake version is <3.21 or >3.21

**Comment by paskino** [comment]
It looks like that if CMake version is > 3.21 the command will not fail. Currently for my problems I will install a newer version of  CMake until this is fixed.

https://github.com/UCL/STIR/blob/770048aa07ef3b97c5094c46b1beb304c28bb5ab/src/cmake/STIRConfig.cmake.in#L69-L77

**Comment by paskino** [comment]
Works with `release_5.0`. I'm now rebuilding with docker.
