### ISSUE TITLE
BlocksOnCylindrical ForwardProjection results in flipped first view

### ISSUE THREAD

**Issue by markus-jehl** [UCL/STIR#1043]
When forward projecting an image with a BPET scanner and BlocksOnCylindrical, the first view appears to be flipped (or rotated by 180°).

Additionally, the last slice is homogeneous 1 instead of actual projection data, but this could be unrelated.

**Comment by danieldeidda** [comment]
a fix is coming. There was a condition moving lors around in the get_phi() function

**Comment by KrisThielemans** [comment]
fixed in 40ede282ad39f87faaef015c92901db25796aa6c (i.e. #1045 merged back to `master`)

**Comment by markus-jehl** [comment]
Brilliant, thank you!

**Comment by danieldeidda** [comment]
should be OK

**Comment by KrisThielemans** [comment]
final fix in #1050
