### ISSUE TITLE
Improving HKEM coding from SIRF

### ISSUE THREAD

**Issue by danieldeidda** [UCL/STIR#1051]
https://github.com/UCL/STIR/blob/b1227dda0537530040cde4c48d79fbb661233495/src/iterative/KOSMAPOSL/KOSMAPOSLReconstruction.cxx#L760-L764

If this function was exposed to SIRF it would make the use of  kernels more flexible and possibly use them for different algorithms then OSEM. The user would still need to set a KOSMAPOSL object for the parameters and the prior images. 
The function would calculate `kernelised_image_out = K * image_to_kernelise`  where K is the kernel
@samdporter

**Comment by KrisThielemans** [comment]
Should be a SIRF issue? Please close this and create it there
