### ISSUE TITLE
confusing naming of isRandom in SAFIR listmode class

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1064]
One of the elements in the SAFIR file is called `isRandom` https://github.com/UCL/STIR/blob/4d087f3e7cf3c6d2d95b87f64e9e68bf9f1b186e/src/include/stir/listmode/CListRecordSAFIR.h#L64
This seems a confusing name as it indicates if it's a delayed coincidendence or not.

@jafische would you agree with this?

**Comment by jafische** [comment]
Yes indeed. This was inspired by the [CListRecord for the ECATs](https://github.com/UCL/STIR/blob/4d087f3e7cf3c6d2d95b87f64e9e68bf9f1b186e/src/include/stir/listmode/CListRecordECAT966.h#L88), where it is also called "random".

**Comment by KrisThielemans** [comment]
ah well.

Luckily, this seems to be a private variable in both cases, so I think we can adjust this without affecting anyone. We'll also need to fix doxygen strings on `is_prompt()`
