### ISSUE TITLE
listmode objective function issues

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1095]
@NikEfth I created a commit with some comments on things that I believe need fixing in the listmode files. 
https://github.com/UCL/STIR/pull/1094/commits/122bd81fce5a144a9ed03b14de9c6b0c0ff69f39

In addition, I think there is problem that the [writing of the cache file](https://github.com/UCL/STIR/blob/a7d6a5118c30dd3e8739cf8be4c807a725c569c1/src/recon_buildblock/PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin.cxx#L600) doesn't use the `cache_path` variable, while the reading does. Possibly this explains the problem @evgueni-ovtchinnikov has with SIRF (not sure!).

Is there any reason we don't just use a `cache_filename` variable, as opposed to `cache_path` + hard-coded `"my_CACHE00.bin"`? That seems more flexible (and easier) to me.

I've created #1094 with currently only the above commit in there. If you could have a look and add a comment in the PR, that'd be great. I might address some of those comments there in the next few days, such that we can release 5.1.

**Comment by NikEfth** [comment]
Hi @KrisThielemans 
I will have a look tomorrow that is the election day, here

**Comment by KrisThielemans** [comment]
Larger issues to address:
- [ ] `max_ring_difference_to_process` is no longer necessarily correct, as listmode data can be span>1 for some scanners. The variable should be called `max_segment_num_to_process`
- [ ] `cache_size` conflicts with `num_events_to_process` etc
- [ ] time frame definitions not correctly handled when caching
- [ ] `add_view_seg_to_sensitivity` code has been deleted
- [ ] checks in `post_processing()` need to be moved to `set_up()`

**Comment by KrisThielemans** [comment]
hi. if you wan to help by actually writing code, yes, please. But just commenting would be already great.

**Comment by NikEfth** [comment]
Yes, I am implementing the time frames.

**Comment by KrisThielemans** [comment]
@NikEfth I was going to replace `cache_path` with a `cache_filename`, but I notice you want to be able to have several cache files. Can you explain why?

**Comment by NikEfth** [comment]
@KrisThielemans 
Well, the RAM might not sufficient to hold the whole vector and we could split it into several. 
I have the code in my private repo because I ran to this many times while working on the listmode reconstruction. But, back in June, I had enough computer resources to not run into this issue and, not enough time to bring this part of the code over.

**Comment by KrisThielemans** [comment]
ah ok. that makes sense!

**Comment by KrisThielemans** [comment]
I've ticked the items that I've addressed by now.
