### ISSUE TITLE
"estimate_triple_energy_window_scatter_sinogram" With Multiple Detector Heads

### ISSUE THREAD

**Issue by lukepolson** [UCL/STIR#1099]
When the function `estimate_triple_energy_window_scatter_sinogram` is called on three seperate interfile files (lower scatter, upper scatter, regular image) that each contain data from two detector heads, it appears that the estimated scatter file only contains projection data for one of the detector heads. Was this intended, or is this a bug?

**Comment by danieldeidda** [comment]
Dear Luke, 
not sure that follow but it definitely sounds like something is going wrong, could you show any image to explain this? the output should only be one sinogram but it should contain all the angles covered by all the detector heads.

**Comment by lukepolson** [comment]
Hi Daniel, I attach files that go with my description in the zipped folder. I only include the headers since the data itself is private. Firstly, I have the files `temp_file.hs`, `temp_file_lower.hs` and `temp_file_upper.hs` that represent the regular and lower/upper scatter windows. As you can see, each file has data from two detector heads, each detector orbits in a non-circular orbit with different radii. Then I run the command 

`estimate_triple_energy_window_scatter_sinogram temp/scatter.par`

in terminal (`scatter.par` file attached). The file it produces is called `temp_scatter_contribution.hs` (also attached). As you can see, it only contains data corresponding to the second detector head (this is confirmable by looking at the `radii` field of the `temp_scatter_contribution.hs` file).
[files.zip](https://github.com/UCL/STIR/files/10095319/files.zip)

**Comment by KrisThielemans** [comment]
I think this is likely due to #1102 and not related to the scatter estimation. @lukepolson, if that's the case, can you close this one?

**Comment by lukepolson** [comment]
Yes, I've closed the issue
