### ISSUE TITLE
extra warnings introduced by PR #102

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#110]
we're getting things like
```
/home/travis/build/CCPPETMR/SIRF-SuperBuild/STIR/src/include/stir/common.h:298:14:warning: stir::_PI defined but not used [-Wunused-variable]
 const double _PI = boost::math::constants::pi<double>();
```
we didn't have this before as we were using a `#define`.
@dvolgyes, how do we fix this?

**Comment by dvolgyes** [comment]
I am sorry, I missed it. I will make a pull request in a few minutes.
It is ugly, but that is the best I can figure it out now.
By the way, it might be a good idea to enable -Wextra in STIR too.
(I don't compile SIRF, and I did not spot it in STIR.)
