### ISSUE TITLE
CMake configuration with parallelproj (built with CUDA) 1.2.12 reports lack of CUDA

### ISSUE THREAD

**Issue by Robert-PrescientImaging** [UCL/STIR#1133]
I am pretty sure this is a STIR issue, not a parallelproj issue.

Parallelproj build and is installed correctly. The output parallelproj's `make test` is:
```
>make test
Running tests...
Test project /home/robert/devel/parallelproj/build
    Start 1: parallelproj_nontof_fwd_back_test
1/2 Test #1: parallelproj_nontof_fwd_back_test ........   Passed    0.01 sec
    Start 2: parallelproj_nontof_fwd_back_cuda_test
2/2 Test #2: parallelproj_nontof_fwd_back_cuda_test ...   Passed    0.57 sec
```
indicating a successful build with CUDA.
______

STIR's CMake configuration reports the following:
```
[build] -- Found parallelproj 1.2.12 (but using its OpenMP version as it wasn't built with CUDA)
[build] -- Parallelproj projector support enabled.
```
given by: https://github.com/UCL/STIR/blob/734b575e41fcff585395b7514af0c3a482349a85/CMakeLists.txt#L194-L210
via `grep -rnI "parallelproj_built_with_CUDA" .`, I cannot identify where `parallelproj_built_with_CUDA` is assigned. It is defined here: https://github.com/UCL/STIR/blob/734b575e41fcff585395b7514af0c3a482349a85/src/cmake/STIRConfig.h.in#L76-L77

**Comment by KrisThielemans** [comment]
hmmm. @gschramm is `parallelproj_built_with_CUDA` a variable that was set by `parallelproj` but no longer? How do we know if the cuda version is available?

**Comment by gschramm** [comment]
> hmmm. @gschramm is `parallelproj_built_with_CUDA` a variable that was set by `parallelproj` but no longer? How do we know if the cuda version is available?

Hm. That is indeed strange.
```parallelproj_build_with_CUDA``` should be set in parallelproj's [Config.cmake.in](https://github.com/gschramm/parallelproj/blob/28b504c926226f983bbdf1c89d901a4681e3afe8/cmake/Config.cmake.in#L10).
And ```CUDA_SUPPORTED``` is set to ```True``` when [CMakeLists of the cuda lib](https://github.com/gschramm/parallelproj/blob/28b504c926226f983bbdf1c89d901a4681e3afe8/cuda/CMakeLists.txt#L18).

@KrisThielemans : any idea why this is not working as expected?

**Comment by KrisThielemans** [comment]
No idea, especially as @markus-jehl and others have had no problem.

@Robert-PrescientImaging what is the content of your (exported) `parallelprojConfig.cmake`?

**Comment by Robert-PrescientImaging** [comment]
Attached copy of `${parallelproj_install}/lib/cmake/parallelproj/`[parallelprojConfig.cmake.txt](https://github.com/UCL/STIR/files/10411933/parallelprojConfig.cmake.txt)

**Comment by gschramm** [comment]
@KrisThielemans @Robert-PrescientImaging that seems correct to me, doesn't it?
```parallelproj_built_with_CUDA``` should be ```TRUE``` if I understand the "empty" ```if()``` correctly.

**Comment by KrisThielemans** [comment]
no, I don't think so, I believe that an empty `if()` is the same as `if(FALSE)` in CMake. I cannot check at the moment, but easy for one of you to do that 😄

**Comment by gschramm** [comment]
```if()``` is indeed ```if(False)```. The problem was that variables defined in subdirectory CMakeLists.txt's were not correctly expanded in the cmake.in (thus the empty if).

This is now fixed in release 1.2.13 [here](https://github.com/gschramm/parallelproj/releases/tag/v1.2.13).

@Robert-PrescientImaging can you try again with v1.2.13?

**Comment by KrisThielemans** [comment]
@paskino, please take note and upgrade to 1.2.13 in the SIRF-SuperBuild (once we know it works). sorry

**Comment by Robert-PrescientImaging** [comment]
```
[cmake] -- Found parallelproj 1.2.13 (will use its CUDA support)
[cmake] -- Parallelproj projector support enabled.
```
That fixed it, thank you @gschramm and @KrisThielemans

**Comment by Robert-PrescientImaging** [comment]
That fixed it, thank you @gschramm and @KrisThielemans 

The relevant part of the `parallelprojConfig.cmake.txt` is modified to:

```
if(NOT FALSE)
  set(parallelproj_built_with_CUDA TRUE)
endif()
```
allowing for STIR's CMake configuration to enable CUDA support
```
[cmake] -- Found parallelproj 1.2.13 (will use its CUDA support)
[cmake] -- Parallelproj projector support enabled.
```

**Comment by gschramm** [comment]
@Robert-PrescientImaging thanks for testing and thanks for finding this issue!
