### ISSUE TITLE
SingleScatterSimulation output not consistent downsample_scanner_bool's status

### ISSUE THREAD

**Issue by Robert-PrescientImaging** [UCL/STIR#1173]
I believe this is related to the status of `downsample_scanner_bool`. My testing python script:

```
def simulate_scatter_test(template_projdata: stir.ProjData, true_image: stir.FloatVoxelsOnCartesianGrid,
                          attenuation_image: stir.FloatVoxelsOnCartesianGrid,
                          downsample_scanner=False) -> stir.ProjData:

    scattered_projdata = stir.ProjDataInMemory(template_projdata.get_exam_info(),
                                               template_projdata.get_proj_data_info())
    s = stir.SingleScatterSimulation()
    s.set_template_proj_data_info(scattered_projdata.get_proj_data_info())
    s.set_exam_info(scattered_projdata.get_exam_info())

    s.set_output_proj_data_sptr(scattered_projdata)
    s.set_activity_image_sptr(true_image)
    s.set_density_image_sptr(attenuation_image)

    s.set_downsample_scanner_bool(downsample_scanner)
    s.set_up()
    s.process_data()

    print(f"Scattered projdata with downsample_scanner = {downsample_scanner}:\n"
          f"\t{scattered_projdata},\n"
          f"\tsum: {scattered_projdata.to_array().sum()}")

    print(f"Output projdata downsample_scanner = {downsample_scanner}:\n"
          f"\t{s.get_output_proj_data()},\n"
          f"\tsum: {s.get_output_proj_data().to_array().sum()}\n")


def main():
    projdata, image = construct_projdata_and_image_for_test()
    for downsample_bool in [True, False]:
        simulate_scatter_test(projdata, image, image, downsample_bool)


if __name__ == '__main__':
    main()
```

I slightly modified STIR's SingleScatterSimulation class to add `set_downsample_scanner_bool(arg)` (PR incoming). The output from the two print statements is:

```
Scattered projdata with downsample_scanner = True: 
    <Swig Object of type 'stir::shared_ptr< stir::ProjDataInMemory > *' at 0x7fae873456c0>, 
    sum: 0.0
Output projdata downsample_scanner = True: 
    <Swig Object of type 'stir::shared_ptr< stir::ProjData > *' at 0x7fadaeeedf10>, 
    sum: 737.7693481445312

Scattered projdata with downsample_scanner = False: 
    <Swig Object of type 'stir::shared_ptr< stir::ProjDataInMemory > *' at 0x7fadaeefad88>, 
    sum: 39831.5390625
Output projdata downsample_scanner = False: 
    <Swig Object of type 'stir::shared_ptr< stir::ProjData > *' at 0x7fadadea0fb8>, 
    sum: 39831.5390625
```
Note, when `downsample_scanner == True`, the memory address of `scattered_projdata` does not equal that of `s.get_output_proj_data()` and the values in `scattered_projdata` have not been updated, indicated by the sum.

However, when `downsample_scanner == False`, the addresses change between `scattered_projdata` and `s.get_output_proj_data()` but the values are present in `scattered_projdata`, indicated by the sum.

-------------

It appears to be a feature of the swig interface that `s.get_output_proj_data()` creates a new projdata sptr address with sucessive calls so we can ignore that. The concern is the output `sptr` is set but isn't populated when `downsample_scanner_bool=True`.

**Comment by Robert-PrescientImaging** [comment]
Sum values change is most likely caused by images having a very small volume of voxels greater than the scatter threshold. The down sampling most likely results in this volume to significantly change but that is not confirmed.

**Comment by Robert-PrescientImaging** [comment]
I have realized that the output of `s.get_output_proj_data()` is a downsampled projdata, hence `scattered_projdata` will not be populated and I need to upsample.

**Comment by KrisThielemans** [comment]
This is correct. It isn't entirely desirable though. At present, we combine the upsampling with tail-fitting/scaling in 1 step. I seem to recall (but am not sure) that this allows some memory saving. However, for someone doing simulation, it is pretty weird. Not so sure how to resolve that...
