### ISSUE TITLE
Multiple projectors with SPECTUBMatrix cause double free error

### ISSUE THREAD

**Issue by samdporter** [UCL/STIR#1183]
I think there's an error in freeing memory in the destructor for the `ProjectorByBinPairUsingProjMatrixByBin` class when used with the `SPECTUB` class

I'll include some minimal examples as well as valgrind output below.

Created a new issue here as opposed to [SIRF issue #1101](https://github.com/SyneRBI/SIRF/issues/1101) as it's definitely a STIR issue.

I've tried recompiling SIRF/STIR without OpenMP as suggested in the issue above, but it hasn't made any difference.

**Comment by KrisThielemans** [comment]
Probably best to wait till  #1169 is merged. That will change things.

**Comment by samdporter** [comment]
This [repo](https://github.com/samdporter/SPECTissues) now contains some minimal SIRF & STIR scripts that throw the error
`double free or corruption (!prev)
Aborted (core dumped)`
The errors occur on exiting the script after setting up two acquisition models with SPECTUB matrices

The repo also contains some valgrind output files:
for [SIRF](https://github.com/samdporter/SPECTissues/blob/main/valgrind-output-full-sirf.txt)
for [STIR](https://github.com/samdporter/SPECTissues/blob/main/valgrind-output-full-stir.txt

**Comment by samdporter** [comment]
[#1169](https://github.com/UCL/STIR/pull/1169) appears to have fixed this!
