### ISSUE TITLE
SPECT DICOM conversion: cannot rely on energy window labels

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1189]
I modified SPECT_dicom_to_interfile to use the label name as the output filename, but this doesn't work. Just had a DICOM file where the 2 scatter windows had the same name, so the header got overwritten.

**Comment by KrisThielemans** [comment]
I suggest to use `<prefix>_en<number>_<label>.hdr`, i.e.
```
      const std::string header_filename
          = output_prefix + "en" _ std::to_string(w + 1) + "_" + convert_to_filename(spect.energy_window_name[w]) + ".hdr";
```
@danieldeidda @RebeccaGillen what do you think?

**Comment by danieldeidda** [comment]
sounds good, I guess we did not think that two windows could be called the same thing.  It does not make too much sense to me but OK
