### ISSUE TITLE
Travis builds fail because of time-out

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#119]
We now often have one or more jobs failing as they run for too long. Quite a lot of the run-time is spent in the build process. Aside from fixing this as in #83, is there anything easy that can be done to let Travis cache previous builds such that it only rebuilds whatever is needed? (I saw some stuff about ccache etc but I don't know how easy that'd be to use)

**Comment by NikEfth** [comment]
Hi all,

The other day I came across this blog post
(*https://cristianadam.eu/20170709/speeding-up-cmake/).  *I am not an
exprert at cmake but CMake for configure checks actually sets up a small
project using the given generator, it tries to compile the project, and
based on the compilation result determines if some header, function or
symbol is present on the system and these checks are run sequential. So
the point is to run them once write the result somewhere and read it.

Looks promising.

**Comment by KrisThielemans** [comment]
time-out has been increased by Travis. we use ccache now. so closing.
