### ISSUE TITLE
test_interpolate_projdata failures

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1201]
conda-forge builds fail in `test_interpolate_projdata` on Linux with conda gcc 12.2.0 (all other jobs are fine)
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=701738&view=logs&j=d1321064-f6c3-56b7-0172-6d994d01c836&t=39022612-2533-571e-7b41-94814e7d38bb
[199.log](https://github.com/UCL/STIR/files/11413218/199.log). Cutting most of the log, I see 

```
INFO: Performing symmetric interpolation test for BlocksOnCylindrical scanner
Error. symmetry errors larger than 0.01% of absolute values in axial direction
INFO: Performing symmetric interpolation test for Cylindrical scanner
WARNING: Disabling symmetries as image is rotated due to phi offset of the scanner.
Error. symmetry errors larger than 0.01% of absolute values in axial direction
INFO: Performing asymmetric interpolation test for BlocksOnCylindrical scanner
Error. difference between segments is larger than expected
INFO: Performing asymmetric interpolation test for Cylindrical scanner
Error. difference between segments is larger than expected
```
Interestingly, the ubuntu gcc 12.1.0 test works fine on GitHub Actions for STIR.

Unfortunately, the test doesn't report what the actual errors are. @markus-jehl would you be able to modify the test such that it writes this out? This could be a threshold thing, or something else.

**Comment by markus-jehl** [comment]
This is being thrown by the symmetry checks, so the text written after the "Error." is the actual error: https://github.com/UCL/STIR/blob/d23cda69ebd68ac92de4f51c0536635afbaa2a22/src/test/test_interpolate_projdata.cxx#L97

The thresholds were found empirically, but did have some margin. It's a bit worrying that they fail on one specific compiler...

Should I add the actual values to the error message, such that it is immediately visible how far off we are from the thresholds?

**Comment by KrisThielemans** [comment]
@markus-jehl the PR should have allowed to have more information. Worth posting here.

**Comment by KrisThielemans** [comment]
Still occasional failures
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=765513&view=logs&j=d1321064-f6c3-56b7-0172-6d994d01c836&t=39022612-2533-571e-7b41-94814e7d38bb&l=3824
```

Going ahead anyway.

INFO: Determined voxel size by dividing default_bin_size (6.52531) by zoom

INFO: Determined voxel size by dividing default_bin_size (6.52531) by zoom

WARNING: Disabling symmetries as image is rotated due to phi offset of the scanner.

WARNING: WARNING: ProjMatrixByBinUsingRayTracing used for pixel size (in x,y) that is larger than the bin size.
Backprojecting with this matrix might have artefacts at views 0 and 90 degrees.


WARNING: ProjMatrixByBinUsingRayTracing: use_actual_detector_boundaries==true


WARNING: forward_project. Imaging modality unknown for either the image or the projection data or both.
Going ahead anyway.
Error : 23783.5 is larger than 17500, difference between segments is larger than expected

End of tests. Please correct errors !

```

**Comment by KrisThielemans** [comment]
On my desktop, I can reliably reproduce these errors with the Intel C++ compiler (which is based on LLVM) version 2023.2.0.20230721 with `RelWithDebInfo`, even without OpenMP. In `Debug` mode, they disappear...

Cutting the warnings from the log, I have
```
INFO: Performing symmetric interpolation test for BlocksOnCylindrical scanner
Error : 20.309 is larger than 0.00304248, symmetry errors larger than 0.01% of absolute values in axial direction
INFO: Performing symmetric interpolation test for Cylindrical scanner
Error : 6.3685 is larger than 0.000896101, symmetry errors larger than 0.01% of absolute values in axial direction
INFO: Performing asymmetric interpolation test for BlocksOnCylindrical scanner
Error : 4914.3 is larger than 4697, difference between segments is larger than expected
INFO: Performing asymmetric interpolation test for Cylindrical scanner
Error : 23783.5 is larger than 17500, difference between segments is larger than expected
```
Here are the sinograms.
[sinos_cyl.zip](https://github.com/UCL/STIR/files/12643284/sinos_cyl.zip)
[sinos.zip](https://github.com/UCL/STIR/files/12643285/sinos.zip)
@markus-jehl do they give you any clue? (I haven't looked at them)

**Comment by markus-jehl** [comment]
The symmetric interpolation tests fail because the interpolation is axially not symmetric:
![image](https://github.com/UCL/STIR/assets/87262701/f75aeb8e-6aa0-4714-84cd-738d9fca25cd)
vs. the expected result:
![image](https://github.com/UCL/STIR/assets/87262701/37f909b0-5340-4bdb-ad99-474a8707dd30)

**Comment by markus-jehl** [comment]
The asymmetric ones are a bit less definitive: there I just set an empirical threshold for the difference between interpolated and ground truth proj data and it is exceeded in this version.
Expected proj data:
![image](https://github.com/UCL/STIR/assets/87262701/bb13b99a-b544-469d-bc5b-aba5f4ab37ff)
Proj data you sent me:
![image](https://github.com/UCL/STIR/assets/87262701/f65dc533-ef98-481f-bd8b-ec028aaf814c)

**Comment by KrisThielemans** [comment]
good test! As it's compiler/optimisation depend, this one will be hard!

**Comment by markus-jehl** [comment]
Could it be that it is actually not related to interpolation/projection, but due to a slight misalignment of the image to the scanner? If the simulated scene is not perfectly centred, then the interpolation would not be symmetric.

But why this would be compiler/optimisation dependent is another question...

**Comment by markus-jehl** [comment]
I think this is it! Here is the downsampled sinogram that is being interpolated in the axial symmetry test:
![image](https://github.com/UCL/STIR/assets/87262701/3dba7eaa-0369-426a-8dbd-e9043c90096b)
compared to the expected:
![image](https://github.com/UCL/STIR/assets/87262701/4c452322-1dd8-4d63-a074-a4fcf8a674b3)

**Comment by KrisThielemans** [comment]
great. Some dependency on discretisation, i.e. `floor` etc?

**Comment by KrisThielemans** [comment]
`construct_volume` has to discretise the shape. It does it by sampling. With the sampling set to 1,1,1, it will check if the centre of each voxel is inside the shape. If that is obviously dependent on rounding error. As we're using an `EllipsoidalCylinder`, do the edges by any chance fall right between voxels? If so, we could be unlucky...

Aside from changing the length of the cylinder, probably best to use higher sampling (certainly in z, preferably in the others as well), e.g. 10,3,3 should soften the discretised shape.

What do you think?

I can try this out then

**Comment by markus-jehl** [comment]
So, the crystal spacing in axial direction on the downsampled scanner is 20 mm, and the cylinder length is 40. Therefore I thought that the crystal should perfectly align with the two central rings and the edges therefore be as far away from the centre of the voxels. Smoothing could hide the issue to some degree, but probably not fix the underlying problem.

**Comment by KrisThielemans** [comment]
Are you saying the image is symmetrical but the downsampled sino (obtained by forward projection) isn't?

https://github.com/UCL/STIR/blob/738ed77c3a42a113b4bde1cd0e050fb04d01b3ed/src/test/test_interpolate_projdata.cxx#L174
implies that voxel-z-size is half the crystal spacing, i.e. 10mm. The cylinder will be centred, but extend exactly half-way into the voxels either side, I think.

**Comment by markus-jehl** [comment]
Oh, you're right! I was only looking at the proj data, but the image should indeed use twice the resolution. So it indeed aligns perfectly with one of the voxel edges.

Could you try making the cylinder a tiny bit longer to avoid these rounding errors? I've tried with 41 mm length and the test still passes.

**Comment by KrisThielemans** [comment]
This resolves the "symmetric" tests.

Increasing the sampling reduces the "asymmetric" errors (which makes sense), but I can't immediately get them small enough. In fact, doing that makes my gcc-11 build now fail on the "asymmetric" tests. Sinograms look fine though. Example for the "cylindrical" case (compiled with gcc)
![image](https://github.com/UCL/STIR/assets/6362141/7e8579bd-ac3d-4d52-8e58-f221b9836a54)
(legend on the left). It seems that test is rather unstable.

I do note that the image of the "full" case has voxel-size 8x8x2, while the downsampled has 6.52531x6.52531x5 (cylindrical, didn't check the block one yet). A bit unexpected that the latter xy voxel size is smaller... Intentional?

Of course, whatever we use, these are never going to be very close.

**Comment by markus-jehl** [comment]
No, that wasn't intentional. The downsampled scanner has fewer crystal per ring and fewer rings, so I assumed the voxel size must be bigger for the downsampled. Will have a look at this.

But yes, this test is a bit clunky since it just tests against an empirical threshold. Increasing the sampling seems like a good way to make the compiler differences less pronounced. So maybe we can do that and adjust the threshold?

**Comment by KrisThielemans** [comment]
sure. Probably we should also convert the threshold to a relative one (RMSE / l2_norm) which would be more future proof. Might even be more robust to use l1-norm (`abs`), as we do in `compare_projdata` I believe.

can you give that a go, and I can then test it with the Intel compiler.

**Comment by markus-jehl** [comment]
Fixed the voxel size and changed the projdata comparison to use the (eroded) ground truth shape to check if the interpolation fills in any wrong voxels. This is more stable because the voxel values are just naturally different and can vary a lot between different scenes.

https://github.com/markus-jehl/STIR/commit/b0dfffe4a31425d372d4301fc3a7634aefe230bf

**Comment by markus-jehl** [comment]
this might now be fixed, after https://github.com/UCL/STIR/pull/1272 was merged
