### ISSUE TITLE
Ray tracing projector introduces axial artifacts for BlocksOnCylindrical scanner geometry

### ISSUE THREAD

**Issue by markus-jehl** [UCL/STIR#1223]
This was found in the master branch as well as in the latest TOF branch. Segment 0 is not affected, but oblique segments have cross-talk suggesting that the intrinsic_tilt and/or segment sign are assigned wrongly in certain situations.

Example from BlocksTests::run_map_orientation_test (slightly modified. left: original, right: rotated detector map):
![image](https://github.com/UCL/STIR/assets/87262701/f06060dc-0774-4c97-ae7b-874f39cc6231) ![image](https://github.com/UCL/STIR/assets/87262701/30c10de0-b818-4d95-b7f7-3b80e684a82e)

**Comment by markus-jehl** [comment]
And below, a plot of a reconstruction of projdata with the same rotation for the template and the data (first) compared to a reconstruction that has a template with a different scanner intrinsic tilt than the data (the data was generated at a different tilt, then the projdata were modified to the same tilt than the one used for reconstruction):
![image](https://github.com/UCL/STIR/assets/87262701/13e338e2-bd16-410e-a0dc-f6016da18936)
![image](https://github.com/UCL/STIR/assets/87262701/d3ae565f-e8cf-4283-b1b5-1fb603c270f1)

**Comment by KrisThielemans** [comment]
Can you confirm this doesn't happen with `parallelproj`?

Can you clarify what you are showing with the viewgrams please? which view, which segment? The left one looks weirder than the right one, so what is "original"?

**Comment by markus-jehl** [comment]
Yes, with parallelproj it does not happen.

The viewgrams I'm showing are across all segments (0, 1, -1, 2, -2, ... going downwards), the left one is the standard SAFIRDualRingPrototype used in the test, the right one is the same scanner but with flipped tangential coordinates in the detector map. The one on the left is definitely showing some data that is axially placed wrongly, so should be a good test case to investigate the problem.

**Comment by markus-jehl** [comment]
@KrisThielemans : I think the problem with the vertical line emerges in the transformation from detectors to tang_pos_num and view_num, i.e. around here https://github.com/UCL/STIR/blob/4a9391257c76e8b8b1b68c22bc81fa92033bff77/src/buildblock/ProjDataInfoCylindricalNoArcCorr.cxx#L289
This is probably the same issue seen here: https://github.com/UCL/STIR/issues/1176

What I was wondering: the tangential positions go from (-num_detectors/2 + 1) to (num_detectors/2), so they are not symmetric. This means that the assumption in the comment on line 289 doesn't work, or does it?

**Comment by markus-jehl** [comment]
Probably the failing round-trip test was just a red herring - the test has a margin for +-1 in the bins, but doesn't handle the wrap-arounds. So I went back to looking at the blocks on cylindrical projection test that creates these vertical lines, and the central tangential bin produces a phi that is 0, when all the neighbouring bins have phis close to pi:
![image](https://github.com/UCL/STIR/assets/87262701/3ee56c58-55d8-4e23-834e-069301dccc4b)

**Comment by markus-jehl** [comment]
Found the problem! The get_phi function does a lot transformations, among which it also often flips the orientation of the line of response. This is fine when getting phi, but unfortunately the same transformations are not done when getting theta. Therefore we often end up with the correct tangential position, correct phi, but inverse theta when doing the ray tracing.

For the plots I have shown above I could fix it by adding the same transformations also to the get_tantheta function in ProjDataInfoGeneric.inl:
```
float
ProjDataInfoGeneric::get_tantheta(const Bin& bin) const
{
  CartesianCoordinate3D<float> _p1;
  CartesianCoordinate3D<float> _p2;
  find_cartesian_coordinates_of_detection(_p1, _p2, bin);

  _p1.z() += z_shift.z();
  _p2.z() += z_shift.z();

  // do the below transformation to check whether the points are swapped when phi is obtained
  // if they are swapped theta needs to be inverted, otherwise the oblique segments contain flipped streaks
  LORAs2Points<float> lor_as_2_points(_p1, _p2);
  const double R = sqrt(fmax(square(_p1.x()) + square(_p1.y()), square(_p2.x()) + square(_p2.y())));
  LORInAxialAndNoArcCorrSinogramCoordinates<float> lor;
  lor_as_2_points.change_representation(lor, R);
  float sign = 1.0;
  if (abs(_p1.z() - lor.z1()) + abs(_p2.z() - lor.z2()) > abs(_p1.z() - lor.z2()) + abs(_p2.z() - lor.z1()))
    sign *= -1;

  CartesianCoordinate3D<float> p2_minus_p1 = _p2 - _p1;
  return sign * p2_minus_p1.z() / (sqrt(square(p2_minus_p1.x()) + square(p2_minus_p1.y())));
}
```

I will also test this with a full reconstruction and then open a PR.

**Comment by markus-jehl** [comment]
This works for full reconstructions as well! Unfortunately doesn't fix https://github.com/UCL/STIR/issues/1058 or https://github.com/UCL/STIR/issues/1176, so there is at least one more problem somewhere
