### ISSUE TITLE
(potential?) data-races

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1255]
Running Intel Inspector (with the Intel compiler) gives me a few data-races. Of course, I'm not sure if these are false positives or not

<h1>when checking internal ProjDataInfo data-structures were initialised</h1>

https://github.com/UCL/STIR/blob/9e40811fac72de58d5488247788c520e447b0501/src/include/stir/ProjDataInfoGenericNoArcCorr.inl#L43-L44
conflicts with
https://github.com/UCL/STIR/blob/9e40811fac72de58d5488247788c520e447b0501/src/buildblock/ProjDataInfoCylindricalNoArcCorr.cxx#L228
(and equivalent for Generic). 

This implementation of the Double-Checked-Locking(DCL) pattern was suggested at http://stackoverflow.com/questions/27975737/how-to-handle-cached-data-structures-with-multi-threading-e-g-openmp.
I see that I didn't use the `atomic write` in the .cxx [Edit: this is now fixed by #1256], but adding that doesn't seem to make Intel Inspector happy.

I can make these disappear by initialising these tables in the constructor, i.e. commenting out lines like
https://github.com/UCL/STIR/blob/9e40811fac72de58d5488247788c520e447b0501/src/buildblock/ProjDataInfoCylindricalNoArcCorr.cxx#L73-L74
However, that causes a slow-down as these tables take a while to construct. For example, 
```
time ./run_test_simulate_and_recon.sh
```
before
```
real    0m23.021s
user    4m12.391s
sys     0m2.925s
```
after
```
real    0m33.966s
user    4m39.860s
sys     0m10.009s
```

<h1>detector position access in `DetectorCoordinateMap::get_coordinate_for_det_pos`</h1>

https://github.com/UCL/STIR/blob/9e40811fac72de58d5488247788c520e447b0501/src/include/stir/DetectorCoordinateMap.h#L91-L93
conflicts with some internal randoms stuff.

This will be because [std random generators are not thread-safe](https://stackoverflow.com/a/45908573).
I think we need one generator per thread (probably a vector of size `get_max_num_threads()`. @markus-jehl feel like looking at that one?

**Comment by markus-jehl** [comment]
sure, I'll put the second one on my list

**Comment by markus-jehl** [comment]
@KrisThielemans : can this be closed?
