### ISSUE TITLE
0/NULL and nullptr for c++0x and c++11 

### ISSUE THREAD

**Issue by rijobro** [UCL/STIR#129]
Problem occurred on OSX, although may be more general.

Comparisons between shared_ptr and 0/NULL cause compilation errors (see [here](https://github.com/UCL/STIR/blob/master/src/buildblock/ProjDataFromStream.cxx#L128)) with c++11. Setting CMAKE_CXX_FLAGS to -std=c++0x solves this.

If all these lines were changed to:
`if (sino_stream == nullptr)`
this would compile with c++11 but not c++0x.

A possible solution would be:
`if (!sino_stream)`
which would work with both c++11 and c++0x.

I assume that OSX Travis successfully compiles because it uses c++0x by default. When `DISABLE_CERN_ROOT_SUPPORT` is `ON`, Travis uses c++11 and compilation also fails.

Thoughts?

**Comment by KrisThielemans** [comment]
all null-ptr checks should use the STIR function `is_null_ptr` (before you can use it, you'll need to include its own include file). if there's a problem with `is_null_ptr`, then we will just have to check one place. It seems this line is a left-over one (or are there others in that file?). Can you generate a PR to fix this?

thanks!

**Comment by rijobro** [comment]
There are multiple instances in this file and at least one other file (I stopped checking after the second file). I'll change them all and then do a PR.

**Comment by KrisThielemans** [comment]
closed with #136
