### ISSUE TITLE
scatter estimation problem in recon_test_pack

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1302]
Originally observed in https://github.com/NikEfth/STIR/pull/66#issuecomment-1878475159 but this is not a TOF issue, and happens on current `master`.

Changing the template to DSTE span 2, max rd3 (from span 0, max rd2) encovers a problem in the scatter estimation, i.e. run_scatter_tests.sh fails with too large difference between simulation and estimation. This is pretty weird as segment 0 for both these templates should be identical.

Initial investigation shows that
- scatter simulation and upsampling is the same
- reconstructed images during scatter estimation look fine but have different scale (and both seem to be wrong)

estimated (left) and simulated (right) scatter and diff (bottom) (segment 0, central view):
![image](https://github.com/NikEfth/STIR/assets/6362141/0e2f696c-aef8-4403-b486-2d5fd4f852a7)
reconstructed images during scatter (from span=2 left, from span=0 right, input = bottom)
![image](https://github.com/UCL/STIR/assets/6362141/8e2b81a0-661a-4da7-aead-159549f79f28)
ROI values of these images are ~12, ~8, 1 resp. I'd expect a factor 4 due to the ratio in x-voxel size between reconstructions and input though.

This is all weird, as the reconstructed images should have the same values, and it's hard to understand why the difference in seg 0 is on one end of the scanner, while actually the axial image profiles are fine.

**Comment by markus-jehl** [comment]
This looks vaguely related to axial geometry fixes in the downsampling done here: https://github.com/UCL/STIR/pull/1466

So maybe this issue can be closed?

**Comment by KrisThielemans** [comment]
Fixed by #1531
