### ISSUE TITLE
TOF loop missing for Hessian computation

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1305]
`PoissonLogLikelihoodWithLinearModelForMeanAndProjData::actual_add_multiplication_with_approximate_sub_Hessian_without_penalty` and other Hessian function don't loop over TOF data

**Comment by Robert-PrescientImaging** [comment]
Is this as simple as updating the relevant lines to use the `ViewgramIndices` (https://github.com/UCL/STIR/pull/1273), e.g. 
https://github.com/UCL/STIR/blob/75a9342157e59db6d43a968fa48f7d8c951853fb/src/recon_buildblock/PoissonLogLikelihoodWithLinearModelForMeanAndProjData.cxx#L949C49-L961

**Comment by KrisThielemans** [comment]
@gschramm, this is going to create trouble...

**Comment by KrisThielemans** [comment]
Actually, the list-mode Hessian should be fine.

**Comment by gschramm** [comment]
@KrisThielemans and I am using non-TOF mMR data from the examples ;)

**Comment by gschramm** [comment]
But good to keep that in mind and maybe warn people.
+ another reason to use `torch.autograd.gradcheck` to verify custom layers ...

**Comment by KrisThielemans** [comment]
@gschramm I fixed this now.
