### ISSUE TITLE
Link external project to STIR libraries leads to segmentation errors

### ISSUE THREAD

**Issue by NikEfth** [UCL/STIR#131]
I develop a sinogram viewer based on QT and I link to to stir libraries to load the projection data. But I kept falling into segmentation faults as soon as the function that created the ProjData returned. 

The errors came from various places were shared_ptrs were passed by reference and the shared counter did not increment. I will PR a fix for the ProjData, soon.

**Comment by KrisThielemans** [comment]
I've been reading-up a bit, e.g. [here](https://stackoverflow.com/questions/3310737/shared-ptr-by-reference-or-by-value/8741626#8741626) and it seems it only matters if non-sequential access is required (e.g. create a `shared_ptr` `A`, pass it elsewhere where it's copied to `B`, then`A` gets destructed. You clearly want the reference count to be updated. I always thought this would be ok even with code like
```C++
ProjData::ProjData(const shared_ptr<ExamInfo>& exam_info_sptr,
		   const shared_ptr<ProjDataInfo>& proj_data_info_sptr)
  :ExamData(exam_info_sptr), proj_data_info_ptr(proj_data_info_sptr)
{}
```
but now I'm not so sure, and the version without references would clearly be safer (and a bit slower but I don't think we care about that in this context). Looking forward to your PR.

**Comment by KrisThielemans** [comment]
we don't see any problems with SIRF, so I will close this, as probably outdated. Feel free to reopen.
