### ISSUE TITLE
valgrind errors with parallelproj in test_blocks_on_cylindrical_projectors (on WSL with Ubuntu 22.04)

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1384]
I've got a load of errors with `valgrind` once the (CUDA) parallelproj code starts.

It's unclear to me if these are WSL (I think most likely), CUDA, parallelproj problems/false-positives, and/or maybe an occasional STIR problem. Anyone could run this on Ubuntu or so without WSL?

(There's also some ROOT library errors at the end. We get them all the time. Hopefully will disappear when upgrading ROOT).

[valgrind.log](https://github.com/UCL/STIR/files/14297745/valgrind.log)

This check was prompted by a seg-fault of `test_proj_data_info_subsets` on `master`, but that one has no `valgrind` 
errors on my machine (except the ROOT ones).
My system info
- Windows 11 Pro with WSL2, nvidia 12.2.2.1
- current STIR master
- on WSL
  - libparallelproj 1.7.3
  - gcc 12 with C++20
```
(base) kris@ASC-HYDRA:~/devel/build/SIRF-SuperBuild/builds/STIR/buildRelWithDebInfo-gcc12$ g++-12 --version
g++-12 (Ubuntu 12.3.0-1ubuntu1~22.04) 12.3.0
(base) kris@ASC-HYDRA:~/devel/build/SIRF-SuperBuild/builds/STIR/buildRelWithDebInfo-gcc12$ nvidia-smi
Thu Feb 15 14:03:09 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.98.01              Driver Version: 536.99       CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070        On  | 00000000:0B:00.0 Off |                  N/A |
|  0%   29C    P8               9W / 220W |    826MiB /  8192MiB |     13%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        20      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        20      G   /Xwayland                                 N/A      |
|    0   N/A  N/A        20      G   /Xwayland                                 N/A      |
+---------------------------------------------------------------------------------------+
```

@gschramm did you ever run `valgrind` on some parallelproj code?

**Comment by gschramm** [comment]
Hi Kris,
so far I have never run `valgrind` on parallelproj programs. But it is probably a good idea to do that.
From former colleagues I got feedback that using `valgrind` is not entirely trivial, is that true? If so,
can you recommend tutorials?
Do you also have a feeling what kind of paralleproj functions could cause the problem?

**Comment by KrisThielemans** [comment]
This shouldn’t be too hard, really. Simply

                valgrind test_program

The only difficulty might be that you don’t have a C++/C program, and therefore would need to do

                valgrind python test_script.py

In that case, you’ll likely see “errors” in the python interpreter, which can be confusing.

Feel free to post your log file somewhere (e.g. here) if it doesn’t make sense to you.

TBH, I don’t think the most of the errors are parallelproj errors, as it flags up loads of stuff in cuda libraries (actually WSL wrappers).

Kris

**Comment by gschramm** [comment]
Hi Kris,

1.  I have a few minimal Ctest programs that call the projectors. I will run them with valgrind during the weekend.
I guess I have to compile with "-g" to have debugging information (CMAKE_BUILD_TYPE=Debug)?
Learning how to trace memory errors is definitely a useful skill.  Apparently, people have reported false positive with valgrind and cudaMalloc
https://stackoverflow.com/questions/20593450/valgrind-and-cuda-are-reported-leaks-real
Is this what you are seeing as well?
2. Thanks for the optimization tips. I will include / test them. But my feeling is that with the current projectors the main limiting factor is memory access.

Georg

**Comment by gschramm** [comment]
I just run `valgrind` and `cuda-memcheck` on my ctest program that does a minimal non-TOF fwd/back projection.
`valgrind` outputs all kinds of memory leaks due to cuda-libs. `cuda-memcheck` says everything is fine.

**Comment by KrisThielemans** [comment]
alright. So we'll ignore this then.

I guess it'd still be worth running `valgrind` on the non-CUDA version, but I'll close this issue. thanks!

**Comment by gschramm** [comment]
Thanks to this issue, I lost my fear from using "valgrind" :)
The scary thing is that, we probably need two different tool to mem check CPU/GPU code :(
