### ISSUE TITLE
RDP gradient can generate NaNs if epsilon is zero

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1394]
Reconstructing the mMR NEMA data gives me NaNs in the background of the image, then quickly ruining everything of course. Obviously, when `epsilon`=0, the function is not differentiable at x,y=0. We try to set the gradient to zero, but apparently still miss some cases. Relevant code is
https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/recon_buildblock/RelativeDifferencePrior.cxx#L403-L424

@Imraj-Singh have you seen this?

**Comment by robbietuk** [comment]
Could be because of _small_ x/y values?

**Comment by KrisThielemans** [comment]
This was fixed by #1410
