### ISSUE TITLE
Other places that use `abs` as opposed to `std::abs` for floats/doubles that could be affected:

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1415]
Following from #1409, we need to check other places that use `abs` for floats/doubles that could be affected. Simplest is to just replace them with `std::abs`, but it'd be good to know if there was a problem or not. I guess easiest might be to put an error `abs(1.5)-1>.2` while checking.

Copying from https://github.com/UCL/STIR/issues/1409#issuecomment-2080218794_

Library: (worrying!)
- [ProjDataInfo::get_sampling_in*](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/buildblock/ProjDataInfo.cxx#L93-L114): are not affected, but I don't know why
- [inverse_SSRB](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/buildblock/inverse_SSRB.cxx#L88)
- [extend_projdata](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/buildblock/extend_projdata.cxx#L77)

Utilities:
- [shift_image](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/utilities/shift_image.cxx#L77-L82) (maybe not due to `#include <math.h>`)
- [find_fwhm_in_image.cxx](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/buildblock/find_fwhm_in_image.cxx#L203) (possibly not due to `using namespace std;`)

Relatively harmless as error checking:
- [ExamInfo::operator==](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/buildblock/ExamInfo.cxx#L56-L66), - [Radionuclide::operator==](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/buildblock/Radionuclide.cxx#L97-L103)
- [TimeFrameDefinitions::operator==](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/buildblock/TimeFrameDefinitions.cxx#L271)
- [error checking in ProjMatrixByBinSPECTUB](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/recon_buildblock/ProjMatrixByBinSPECTUB.cxx#L325-L330)
- [error checking in ProjMatrixByBinUsingRayTracing](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/recon_buildblock/ProjMatrixByBinUsingRayTracing.cxx#L269-L270)

Test code:
- [test_interpolate_projdata.cxx](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/test/test_interpolate_projdata.cxx#L81)
- [test_blocks_on_cylindrical_projectors.cxx](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/recon_test/test_blocks_on_cylindrical_projectors.cxx#L372)

Commented out code, hence harmless (but confusing):
- [warp_image](https://github.com/UCL/STIR/blob/8ced2d73933420457e0bc76074964b7d4ff00f0c/src/spatial_transformation_buildblock/warp_image.cxx#L46)

**Comment by markus-jehl** [comment]
The inverse_SSRB tests still pass even if the expressions passed into abs() are cast to integers before. I think it would require some quite elaborate design of the scanner rings and downsampling to find a case where the logic would be vulnerable to the int conversion. Nonetheless, it would definitely be saver to switch to std::abs.
