### ISSUE TITLE
LMtoProjData only propagates projdata_info

### ISSUE THREAD

**Issue by danieldeidda** [UCL/STIR#1509]
This is where it happens:
https://github.com/danieldeidda/STIR/blob/31e730eeb4dd5d2fb49c3d2f404ed7bc02e45115/src/listmode_buildblock/LmToProjData.cxx#L320

**Comment by KrisThielemans** [comment]
The template is indeed not used to get this information. Instead, it is obtained from the lm file itself
https://github.com/danieldeidda/STIR/blob/31e730eeb4dd5d2fb49c3d2f404ed7bc02e45115/src/listmode_buildblock/LmToProjData.cxx#L661-L665
https://github.com/danieldeidda/STIR/blob/31e730eeb4dd5d2fb49c3d2f404ed7bc02e45115/src/listmode_buildblock/LmToProjData.cxx#L676
I think this is best: the template can be generic, and is really only used for geometry.

What does `list_lm_info` give for your data? It should have modality, radionuclide etc.

**Comment by KrisThielemans** [comment]
> This doesn't probably explain why SPECT headers are saved as PET though

The interfile writer differentiates Interfile version on modality
https://github.com/danieldeidda/STIR/blob/31e730eeb4dd5d2fb49c3d2f404ed7bc02e45115/src/IO/interfile.cxx#L545
so if it isn't set, it will default to PET.

**Comment by KrisThielemans** [comment]
Then I think your listmode reader doesn't set ExamInfo

**Comment by danieldeidda** [comment]
yes I think that's it

**Comment by danieldeidda** [comment]
OK I fixed it I am going to close this issue
