### ISSUE TITLE
Intrinsic tilt for default ECAT scanners may have the wrong sign

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#1513]
Should tilt to be negative for these scanners? Most have either positive values

https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/buildblock/Scanner.cxx#L177
https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/buildblock/Scanner.cxx#L204
https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/buildblock/Scanner.cxx#L231
https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/buildblock/Scanner.cxx#L258

or 0 value

https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/buildblock/Scanner.cxx#L121
https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/buildblock/Scanner.cxx#L285

Most GE scanners use a negative tilt, e.g.:

https://github.com/UCL/STIR/blob/6417022e54a4814f25776bc8ca1df3acd4e865f6/src/buildblock/Scanner.cxx#L953

_______________

I have acquired and obtained some data using an EXACT scanner with some 3rd party proprietary software.
Please excused the terrible image quality. Using STIR's with a default +15 degree tilt, the image reconstruction is:
![Screenshot 2024-09-20 165906](https://github.com/user-attachments/assets/7d5e52fd-0a28-490d-95af-623faf8fe14d)

If I set this value to be -15 degrees yields this
![image](https://github.com/user-attachments/assets/d148b7cb-f195-4f55-bd40-95b3dc9e4d20)

I expect this second image, with the two rod sources to be horizontally aligned (minor rotation due to how the phantom sits on the bed).

_______

The change is easy. I just don't know if the 3rd party software I am using for acquisition is doing some pre-correction to the tilt. Is there any other ECAT data in circulation that this issue has been examined on?

**Comment by KrisThielemans** [comment]
All our ECAT tests were from before the intrinsic tilt was taken into account. I have no access to any data anymore, nor do I want to spend any time on it :-).

I'm fine with changing it.
