### ISSUE TITLE
ForwardProjectorByBinUsingProjMatrixByBin::forward_project should check image etc

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#154]
there doesn't seem to be any check that the image passed to `forward_project` is actually compatibile with the one that the projector was set_up with. This can easily lead to errors and crashes.

same will be true for back-projectors etc.

**Comment by RebeccaGillen** [comment]
Attempting to forward project SPECT data while details in the template sinogram are inconsistent with image dimensions (eg. a radius of rotation which is smaller than half of the x-dimension or the x-dimension in mm) gives the following error message:

weight3d: attpth larger than allocated
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > 

Including a check for consistency and a more specific error message would be useful.

**Comment by RebeccaGillen** [comment]
Error message weight3d: attpth larger than allocated when attempting to reconstrust a dataset of 128x128x128 4mm voxels (i.e. dimensions of 512mm) with a Radius of Rotation of 250mm using the CS cluster (note that the error message was NOT encountered when simulating these data using the same voxel size, matrix dimensions and radius of rotation)

**Comment by KrisThielemans** [comment]
Original issue was covered by introducing `check() in `Forward/BackProjectorByBin` when revising the the projectors. New issue created for the SPECT matrix.
