### ISSUE TITLE
Recovering the wiki

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#1540]
The MediaWiki on SourceForge is no longer functional. Files seem to be lost. Amazingly, there is an archive on https://archive.org/details/wiki-stirsourceforgenet_wiki.

I've downloaded that and checked what's in there. I find an xml, image files and some logs. The xml looks like what you'd obtain from exporting from MediaWiki:
```
<mediawiki xmlns="http://www.mediawiki.org/xml/export-0.8/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.mediawiki.org/xml/export-0.8/ http://www.mediawiki.org/xml/export-0.8.xsd" version="0.8" xml:lang="en-gb">
  <siteinfo>
    <sitename>stir</sitename>
    <base>http://stir.sourceforge.net/wiki/index.php/Main_Page</base>
.....
```

As opposed to putting this back on SourceForge, I suggest we try and convert this to a GitHub wiki. A quick search throws up 3 options:
- use `pandoc -f mediawiki -t markdown bla.xml -o wiki.md` . That doesn't work very well, as it creates one huge file with all the revisions of each page.
- https://github.com/philipashlock/mediawiki-to-markdown
- https://github.com/outofcontrol/mediawiki-to-gfm?tab=readme-ov-file (evolved version of the previous one)

The latter 2 claim to create a list of files so seem most promising. When trying this, it probably needs both the xml and the Images directory in the .7z file.

Note that when trying `pandoc`, I had to do some small edits to the xml file (replacing `class=&quot;sortable wikitable&quot; style=&quot;width: auto; text-align: center; font-size: normal; border=1 cellpadding=10 cellspacing=0` with `class="sortable wikitable" style="width: auto; text-align: center; font-size: normal; border=1 cellpadding=10 cellspacing=0"`). The resulting file is [here](https://github.com/user-attachments/files/17836653/stirsourceforgenet_wiki-20230429-history.xml.txt) (rename from .xml.txt to .xml).

**Comment by casperdcl** [comment]
FYI I created https://stir.tomography.stfc.ac.uk

missing:
- Asimflow.png
- CreativeCommons-BY-SA-Logo.png
- Logo.png
- Mcc1 logoSTIR.png
- Mcc2 logoSTIR.png
- MediaWikiSidebarLogo.png
- Rb stir.png
- STIRlogo suggestion.jpg
- STiR.png
- Stir logo1b.jpg
- Stir logo2.jpg
- Stirlogo-full.GIF
- Stirlogo-small.GIF

**Comment by KrisThielemans** [comment]
great. That proves that it was ok 😄. Thanks to the Internet Archive!

The images are in stirsourceforgenet_wiki-20230429-wikidump.7z\images\.

**Comment by casperdcl** [comment]
most things are restored at https://github.com/UCL/STIR/wiki

Notes:

- CC-BY-SA-3.0 footer added to all pages
- images are available at `https://raw.githubusercontent.com/wiki/UCL/STIR/*.{png,jpg,GIF}` but most are not actually used afaik
- some files reference non-images (`*.{pdf,xlsx}` etc) which I don't have
- some things haven't exported properly so needs manual checking...
  + e.g. https://stir.tomography.stfc.ac.uk/index.php/STIR-ASIM_Howto does not appear at https://github.com/UCL/STIR/wiki/STIR-ASIM-Howto

**Comment by KrisThielemans** [comment]
That's great! It's also scary to see how out-of-date some of these are 😢 . Let me know when this will be safe to edit.

Regarding missing pages: I don't know why the content doesn't appear. I first thought it had to do with spaces in the link, but there are plenty of pages where that didn't create trouble. We can copy that by hand of course.

How did you do the conversion?

(By the way, when cloning the wiki, I see all the .md files with spaces, while github links to pages with spaces replaced by  _ or -. Sadly, all 3 appear on a github search!)

**Comment by KrisThielemans** [comment]
Sadly, https://stir.tomography.stfc.ac.uk/index.php/STIR_FAQ is also truncated quite a lot: https://github.com/UCL/STIR/wiki/STIR-FAQ.

**Comment by casperdcl** [comment]
updated a bit more

**Comment by KrisThielemans** [comment]
It's looking good at first sight!
