### ISSUE TITLE
RunTests::check_if_equal unsafe for floats/double

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#183]
current code uses
```c++
((fabs(b)>tolerance && fabs(a/b-1) > tolerance)
      || (fabs(b)<=tolerance && fabs(a-b) > tolerance))
```
However, this fails if `tolerance` is large, e.g. for large magnitude numbers, as `fabs(a/b/-1)` should always be small.

**Comment by KrisThielemans** [comment]
changing it to an absolute comparison makes lots of other tests fall over...

**Comment by NikEfth** [comment]
Also fails when `b==0`
Case : `test_ArrayFilter` line 148:  comparison between 12 and 0 passes as equal. 
:fearful:
