### ISSUE TITLE
Keyparser out-of-range when keyword of type array[1]

### ISSUE THREAD

**Issue by NikEfth** [UCL/STIR#185]
_Please excuse my title my not be the actual cause of the crash._ 

I run LM reconstruction using the new `InterfileHeaderSiemens` class, in the file header file I have the keywords
```
%energy window lower level (keV) [1]:=430
%energy window upper level (keV) [1]:=610 
```
Which cause the parser to crash at this point: 

```
// local function to be used in set_variable below
template <typename T1, typename T2>
void static
assign_to_list(T1& mylist, const T2& value, const int current_index, 
	       const string& keyword)
{
  if(mylist.size() < static_cast<unsigned>(current_index))
    {
      error("KeyParser: the list corresponding to the keyword \"%s\" has to be resized "
	      "to size %d. This means you have a problem in the keyword values.",
	      keyword.c_str(), current_index);
      // mylist.resize(current_index);
    }
  mylist[current_index-1] = value;
}
```
`mylist` has not been allocated and ` current_index = 1`

**Comment by KrisThielemans** [comment]
missing `number of energy windows:=1`?

**Comment by NikEfth** [comment]
Nope it is there. 
But when` read_num_energy_windows()` is called it is still ` -1`

**Comment by KrisThielemans** [comment]
It has to be above the others of course. If that's the case, then it's quite strange. I'm assuming you are using recent `master` (or merged)?

can you refresh your `master` and try 
```
list_projdata_info --exam examples/samples/mMR_sinogram.s.hdr 
```
and then for one of your files? This is sinogram data of course. we don't have the equivalent for list data yet. you could maybe try your listmode recon on the list sample (it'll fail because there are no events in the file, but that would be after reading the header of course).

**Comment by NikEfth** [comment]
I am resolving the conflicts with the listmode branch and I am currently in the ECAT8_32bit.
Initially it was the case that in the recon_test_pack the listmode header was the converted interfile, which do not seem to work neither with the interfile parser nor with the Siemens. 
So I copied a lot of stuff from the header you suggested and worked. 

Now there is the issue that ` InterfilePDFSHeaderSiemens::post_processing()` checks for `storage_order `and throws an error.

**Comment by NikEfth** [comment]
I am sorry just noticed that there is and a `InterfileListmodeHeaderSiemens`.

**Comment by NikEfth** [comment]
All sorted. I will close this now. Thank you.
