### ISSUE TITLE
tell people how to cite STIR

### ISSUE THREAD

**Issue by dvolgyes** [UCL/STIR#193]
Hi,

It would be nice, if STIR could contain a quick reference file for citation purposes,
and also the code could be archived.
e.g. the README file could contain a bibtex entry, or an example APA citation, or a separate file, like
STIR.bib.

Also, the source code itself could/should be archived. This is actually quite easy with Zenodo and github. After an initial setup, Zenodo installs a commit hook, and every release automatically gets a DOI, and it is archived. (This feature can be turned on and off, so it could be turned on just before the new release, ignoring all the test releases, and turned off after the release is done.)

Excellent step-by-step tutorial from Github can be found here:
https://guides.github.com/activities/citable-code/

**Comment by KrisThielemans** [comment]
Adding a STIR.bib would be a good idea. But at least we'll have a DOI with the next release.
