### ISSUE TITLE
reading ECAT8 norm files can fail due to EOL

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#195]
Siemens norm files seem to sometimes come with a broken EOL after the name of the data file, i.e. just a CR, not a CR LF combination as in the rest of the file (and is usual for Windows). This makes the STIR KeyParser fail as it concatenates it with the next line.

Current solution: fix the header, e.g.
```bash
tr '\r' '\n' < norm.n.hdr > normfixed.n.hdr
```
which will replace all CR with LF characters.

**Comment by KrisThielemans** [comment]
I'm not sure but I seriously doubt it's the petmr-rd-tools. (how would it do such a weird thing?).

I guess our best bet is to modify `stir::KeyParser` to split lines that have a ``\r`. should be a small fix in 1 or 2 lines.

**Comment by ashgillman** [comment]
For me, I get the solo '\r' only on the 'name of data file' key. I wondered if it was where the tools replace this with the generated file name. E.g., perhaps a fencepost error when filling in this field?

**Comment by ashgillman** [comment]
Actually, perhaps due to the inconsistency between:
https://github.com/UCL/petmr-rd-tools/blob/master/lib/nmtools/MMR.hpp#L737
and
https://github.com/UCL/petmr-rd-tools/blob/master/lib/nmtools/MMR.hpp#L774

I'll have a look at that.

**Comment by KrisThielemans** [comment]
aha. yes.. good thinking! closing this issue therefore. thanks!
