### ISSUE TITLE
OSMAPOSLReconstruction crashes if set_up not called

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#199]
I noticed this in SIRF, when calling `reconstructor.process()` without `set_up()`. It should raise an error, not generate a segmentation fault.

**Comment by NikEfth** [comment]
Are you working on it? I could do this.

**Comment by KrisThielemans** [comment]
I won't have time to tackle this for a while. The `Reconstruction` hierarchy should follow the same strategy as all the others (with a `check` and `already_setup`). I see `Reconstruction.h` contains a comment
```
Currently, set_up() is called by reconstruct(). 
```
possibly that is incorrect as I suspect SIRF calls `reconstruct`, but I haven't checked. @evgueni-ovtchinnikov ?  Any of the `update` functions should call the `check anyway.

**Comment by KrisThielemans** [comment]
This tripped up up again. https://github.com/CCPPETMR/SIRF/issues/268

**Comment by KrisThielemans** [comment]
Moving this optimistically to v4.0 again.
