### ISSUE TITLE
Cannot find numpy

### ISSUE THREAD

**Issue by adler-j** [UCL/STIR#2]
When compiling I get an error:

```bash
/.../STIR/build/src/swig/stirPYTHON_wrap.cxx:4212:10: fatal error:
    'numpy/arrayobject.h' file not found
```

This is due to you [only importing python](https://github.com/UCL/STIR/blob/26aeaaa5009309208d4c133c550fb39a43419966/src/swig/CMakeLists.txt#L36) and not numpy. When building STIR with python using the [anaconda](https://www.continuum.io/downloads) python distributions, the python includes are in

`/home/name/anaconda2/include/python2.7`

while the numpy includes are located in:

`/home/name/anaconda2/lib/python2.7/site-packages/numpy/core/include`

What is needed is that you need to add some "find numpy" cmake command that also finds the numpy headers. We have one in [odl](https://github.com/odlgroup/odlpp/blob/master/cmake/FindNumpy.cmake), but you could also write your own.

**Comment by adler-j** [comment]
Fix available in fork (if you want it)

https://github.com/odlgroup/STIR/commit/ce54a1659c6b2d74f9165a5fea4370d187e43ab7

**Comment by KrisThielemans** [comment]
thanks. I'd prefer to use a FindNumpy.py with an Apache 2.0 compatible license

I've found 
http://docs.mitk.org/nightly/FindNumpy_8cmake_source.html

MITK uses BSD-style. does this one work for you?

**Comment by adler-j** [comment]
The one you linked is probably better than the one I linked, nice find.
