### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by dvolgyes** [UCL/STIR#21]
Travis CI is continuous integration system which is free for open source projects hosted on GitHub. The basic idea is that: every commit is compiled and tested automatically, and the status is reported in an e-mail and can be checked online any time.

It also can test pull requests which would ensure that only tested requests are merged.

A proposed config file (.travis.yml) will be sent as a pull request.

Travis website: https://travis-ci.org/

**Comment by KrisThielemans** [comment]
thanks David. I've merged this now.

**Comment by KrisThielemans** [comment]
@dvolgyes. for some reason, the build for PR #32 frrom @NikEfth fails with time-outs. The recon_test_pack seems to take quite a lot longer (while there is reason that I can see this'd happen). Any ideas?

**Comment by KrisThielemans** [comment]
this problem was due to a bug, now fixed.
