### ISSUE TITLE
PSF reconstruction is returning reconstructed images which is scaled by large factor of 10^7.

### ISSUE THREAD

**Issue by pwadhwa351** [UCL/STIR#221]
@ashgillman Can you add the images for describing this issue?

**Comment by ashgillman** [comment]
![beb-baseline_hkem_par_s21sm1sp1sdm5sdp5_84_k hv](https://user-images.githubusercontent.com/816777/43929295-4361fb84-9c2c-11e8-876e-2021a05b0e1d.png)

![beb-baseline_hkem psf_par_s21sm1sp1sdm5sdp5_84_k hv](https://user-images.githubusercontent.com/816777/43929301-4b0be1c4-9c2c-11e8-8068-22669a7076df.png)

**Comment by ashgillman** [comment]
I think the images look good, but something is obviously just ever so slightly off. Perhaps something isn't being applied to denominator sensitivity image?

**Comment by ashgillman** [comment]
@pwadhwa351 Did you ever get anywhere with this?

**Comment by KrisThielemans** [comment]
I haven't tested this, but are you sure your PSF kernel sums to 1?

**Comment by ashgillman** [comment]
This is a good question. I should have included details on how I utilised PSF. The relevant exerpt from the .par file, under `PoissonLogLikelihoodWithLinearModelForMeanAndProjData Parameters`, is:

      ; very awkward way to specify PSF in both forward and back projector
      projector pair type := Separate Projectors
      projector pair using separate projectors parameters :=
        forward projector type := Pre Smoothing
        Pre Smoothing Forward Projector Parameters:=
          original forward projector type := Matrix
          Forward Projector Using Matrix Parameters :=
            Matrix type := Ray Tracing
            Ray tracing matrix parameters :=
            End Ray tracing matrix parameters :=
          End Forward Projector Using Matrix Parameters :=
          ; image-based blurring
          filter type :=  Separable Cartesian Metz
          Separable Cartesian Metz Filter Parameters :=
            x-dir filter FWHM (in mm):= 4.2
            y-dir filter FWHM (in mm):= 4.2
            z-dir filter FWHM (in mm):= 5.7
            x-dir filter Metz power:= 0.0
            y-dir filter Metz power:= 0.0
            z-dir filter Metz power:=0.0
            ; truncate it a bit to avoid negative lobes
            x-dir maximum kernel size := 5
            y-dir maximum kernel size := 5
            z-dir maximum kernel size := 1
          END Separable Cartesian Metz Filter Parameters :=
        End Pre Smoothing Forward Projector Parameters:=
        back projector type:= Post Smoothing
        Post Smoothing Back Projector Parameters:=
          original back projector type := Matrix
          Back Projector Using Matrix Parameters :=
            Matrix type := Ray Tracing
            Ray tracing matrix parameters :=
            End Ray tracing matrix parameters :=
          End Back Projector Using Matrix Parameters :=
          ; image-based blurring
          filter type :=  Separable Cartesian Metz
          Separable Cartesian Metz Filter Parameters :=
            x-dir filter FWHM (in mm):= 4.2
            y-dir filter FWHM (in mm):= 4.2
            z-dir filter FWHM (in mm):= 5.7
            x-dir filter Metz power:= 0.0
            y-dir filter Metz power:= 0.0
            z-dir filter Metz power:=0.0
            ; truncate it a bit to avoid negative lobes
            x-dir maximum kernel size := 5
            y-dir maximum kernel size := 5
            z-dir maximum kernel size := 1

          END Separable Cartesian Metz Filter Parameters :=
        End Post Smoothing Back Projector Parameters:=
      end projector pair using separate projectors parameters := 

Although I don't think this is an 'officially supported' feature of STIR yet. Does this look roughly correct. When I get a chance, I'll see if I can find the sum over the kernel.

**Comment by KrisThielemans** [comment]
hmmm. looks ok. Easiest way to check the sum of the kernel is to use `postfilter` with this kernel and check sums in before/after images (as long as they original object is well within the image).

**Comment by KrisThielemans** [comment]
would be interesting to try this with #239
