### ISSUE TITLE
Time-of-flight reconstruction capability with STIR 3.1?

### ISSUE THREAD

**Issue by lasyowl** [UCL/STIR#233]
Hello, I am a novice user who is trying to implement tof reconstruction using PET with STIR.
I have heard that STIR will support tof reconstruction at IEEE NSS / MIC, is it available with the current 3.1 version?
Where can I find the relevant documentation?

**Comment by yhkim8912** [comment]
Hello, I am a novice user who is trying to implement tof reconstruction using PET with STIR. 
I have heard that STIR supports tof reconstruction before at  IEEE NSS / MIC, is it available with the current 3.1 version? 
Where can I find the relevant documentation?
