### ISSUE TITLE
pSTIR.ListModeToSinograms.set_template from ProjData

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [UCL/STIR#234]
LmToProjData.post_processing() fails if template_proj_data_name is empty, which prevents the resolution of https://github.com/CCPPETMR/SIRF/issues/173

**Comment by KrisThielemans** [comment]
This is addressed in #828 by splitting functionality to set_up(). It will mean that SIRF will have to call `set_up()` once merged (to `release_4` and `master`).
