### ISSUE TITLE
pass doxygen to Python

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#249]
2 options:

- doxyg2swig, at least one version is at https://github.com/m7thon/doxy2swig
- Next version of SWIG will do this natively: Doxygen support was merged into swig master on 2018-06-07. See https://github.com/swig/swig/blob/master/Doc/Manual/Doxygen.html

**Comment by rijobro** [comment]
I used to use `doxy2swig` for SIRF before I started wrapping it the way the rest of the code is wrapped, so there might be some useful example code in the SIRFReg branch. 

During the CMake configuration step I ran doxygen to convert all doxygen to xml, then I used my doxy2swig to get that across to python.
