### ISSUE TITLE
test_PoissonLogLikelihoodWithLinearModelForMeanAndProjData (SEGFAULT)

### ISSUE THREAD

**Issue by NikEfth** [UCL/STIR#26]
After merging with _dataInput_from_ExamInfo (PR #19) the test_PoissonLogLikelihoodWithLinearModelForMeanAndProjData reports a segmentation fault. 

After PR #25 the bug persists. 

It probably has to do with the move of the target image from the IterativeReconstruction.h to Reconstruction.h. 

I gonna try tackle it.

**Comment by KrisThielemans** [comment]
Has to be something else. PoissonLogLikelihoodWithLinearModelForMeanAndProjDataTests doesn't use Reconstruction, only PoissonLogLikelihoodWithLinearModelForMeanAndProjData...

**Comment by NikEfth** [comment]
This issue is solved by PR #27
