### ISSUE TITLE
Separable Cartesian Metz filter

### ISSUE THREAD

**Issue by rijobro** [UCL/STIR#269]
I noticed that my images were decreasing massively in intensity (order of 10^6) when I did Gaussian postfiltering with the Separable Cartesian Metz filter. 

I think the problem originates from PR #205. If I take the commit before (or revert this commit), then the results make sense again. I've tried this on single, dynamic and parametric images (interfile and nifti). 

@NikEfth, as far as I can see there is no `ctest` in place for postfiltering with this filter. How did you validate? It would be simple enough to put a test in, I suppose.

**Comment by ashgillman** [comment]
Duplicate for #221

Good hunting to find the commit

**Comment by KrisThielemans** [comment]
there might not be a `ctest` but the recon_test_pack does run a [recon using this filter](https://github.com/UCL/STIR/blob/4177ae5ac6460522dabe9bc4a0d255c1f63200b6/recon_test_pack/OSMAPOSL_test.par#L47), so it's weird that this still works

**Comment by KrisThielemans** [comment]
@NikEfth can you look at this rather quickly? The MIC exercises depend on this.

**Comment by NikEfth** [comment]
Hi all, sorry for the delay. 
Could you tell me how to reproduce your findings?

**Comment by ashgillman** [comment]
There is an example clip of a par file in #221, if you use that with any recon (sorry, I'm away from the computer to post the actual par file)

**Comment by rijobro** [comment]
Equally, you should be able to use `postfilter_Metz.par` in STIR's `src/examples/samples`. Set the Metz powers to 0 (although maybe it doesn't work for other values of Metz powers too...). For input, I think you can use any image. 

Compare before and after with `list_image_info` via image min, max and sum.

**Comment by rijobro** [comment]
Oh, and obviously you actually need to do the smoothing
```
postfilter --verbose <output> <input> edited_postfilter_Metz.par
```

**Comment by NikEfth** [comment]
Thank you for you help. 
I found the bug, but I am not sure if it really a bug or it serves a purpose (other than breaking the transformation)

https://github.com/UCL/STIR/blob/38876a97ad3ebb7284239f71988d36cc6df815fc/src/include/stir/numerics/fourier.h#L70

**Comment by rijobro** [comment]
If this git blame of this line is 15 years old, why is it that we didn't have this problem before? Because we weren't using `numerics/fourier.h` prior to your changes?

**Comment by NikEfth** [comment]
I am sure that the Metz did not use this function, but I can confirm that it was not used somewhere else. It should not be hard to find this out. I started the PR #277 for this

**Comment by KrisThielemans** [comment]
Hmm. The comment above that line says that this scale factor is there to make sure it's actually the inverse. That isn't necessarily what the NR FFT was doing of course.

Instead, I think the normalisation in the [Metz code](https://github.com/UCL/STIR/blob/38876a97ad3ebb7284239f71988d36cc6df815fc/src/buildblock/SeparableMetzArrayFilter.cxx#L227) is incorrect.
Instead of 
```C++
filter[j] = (fftdata[i].real()*MmPerVox)/(Res*sampling_interval);
```
I guess we need something like
```C++
filter[j] = (fftdata[i].real()*MmPerVox)/(sampling_interval);
```

Amazingly, I see that there's no test code for the fourier things. There is one in experimental but that uses NR FFT stuff. we'd have to cut that out and reorganise rather dramatically. sorry.

**Comment by KrisThielemans** [comment]
@NikEfth thanks!

would you have time to make a basic test_Fourier and test of the filter? I guess not!

**Comment by KrisThielemans** [comment]
This bug also made scatter fall-over. I don't understand how it wasn't caught by the recon_test_pack.

I've created 2 basic tests now. coming soon.
