### ISSUE TITLE
doc in PLS example file is incorrect

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#288]
eta should scale with the anatomical image, [not the emission](https://github.com/UCL/STIR/blob/f0504f293979c4f6877e10955796c6eef459b752/examples/samples/OSMAPOSL_PLS.par#L45)

Also would be helpful to include the formulas in this parameter file, as it's a bit cryptic otherwise

**Comment by KrisThielemans** [comment]
@danieldeidda, maybe you can have a go?

**Comment by danieldeidda** [comment]
Sure. The formula of the prior in the parameter file?

**Comment by KrisThielemans** [comment]
what about the following
```
  ; the prior has 2 parameters alpha and eta. It is computed for an image f as
  ;   phi(f) = sqrt{alpha^2 + |nabla f|^2 - <nabla f,xi>^2
  ; with xi the normalised gradient of the anatomical image calculated as follows:
  ;   xi = nabla v / sqrt(|nabla v|^2 + eta^2)
  ; alpha controls the edge-preservation property of PLS, and depends on the scale of the emission image. 
  ; eta avoids division by zero, and depends on the scale of the anatomical image. 
```

**Comment by KrisThielemans** [comment]
@danieldeidda not sure if this has been done by now. could you please check?

**Comment by danieldeidda** [comment]
I remember I did the modification, not sure I did a PR. Let me check
