### ISSUE TITLE
solution already contains an item called tests in visual studio

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#296]
I'm getting a warning that the `tests` item already exists when opening the project with Visual Studio 2015. I guess this is since #236. We have a folder called `Tests` already which seems to clash with the new target `tests`. Here's another [case where this happened](http://lists.llvm.org/pipermail/llvm-commits/Week-of-Mon-20150105/251150.html).

I guess this is really a CMake bug, but our only solution seems to be to rename either the target or the folder. I guess the latter is less intrusive.

We currently have folders `Executables`, `Libs` and `Tests`. Anyone has a good name for the latter then?

**Comment by KrisThielemans** [comment]
turns out it's not the folder. Renaming that didn't help. Renaming the target to `tests1` did. No idea where it comes from.

**Comment by KrisThielemans** [comment]
It is in any case somewhat confusing to have a target `RUN_TESTS` (CMake auto-generated), a folder `Tests` (or even with the alternative name `Test executables`) and a target `tests`. What about renaming it to `build_tests`? @ashgillman ?

**Comment by ashgillman** [comment]
Yep, I'm happy to rename the target. `tests` is confusingly close to `test` anyway. I'd suggest `all_tests` as opposed to the verb 'build'?

**Comment by KrisThielemans** [comment]
To me, `all_tests` doesn't quite convey what it's doing (could just as well run all tests). no?

To make matters worse, I just checked Visual Studio. CMake generates the following targets there (and presumably for XCode etc as well): `ALL_BUILD`, `INSTALL`, `RUN_TESTS` (and  `ZERO_CHECK`), while the "Unix Makefile" generator uses `all`, `install` and `test`. Oh well. (it means that you cannot use `cmake --build . --target RUN_TESTS --config Release` or whatever in a portable manner)

For our own targets, I think using different target names for different platforms is going to be a pain for maintenance and documentation. My current feeling is therefore we should caps as well. For Unix makefiles, it has the advantage of removing any doubt that this is a "normal" target.

So... my latest suggestion is `BUILD_TESTS`.

(Sadly, it seems this PR failed the test "do we really need this compared to the amount of effort it takes". I hadn't seen that coming!)

**Comment by ashgillman** [comment]
I see. I was thinking that being a target implied that it was to be built, but I guess targets are a lot more flexible than that.

I will make a PR with BUILD_TESTS as the target.

I guess I am the only one using this target, but I do find it quite convenient. How are other people running their tests? `make all` every time?
