### ISSUE TITLE
CMake should give error if building python without shared libs

### ISSUE THREAD

**Issue by adler-j** [UCL/STIR#3]
Currently, when configuring, you can select `BUILD_SWIG_PYTHON` and neglect to select `BUILD_SHARED_LIBS`. This lets you build all of STIR (to linking) before you get an error saying you need to build shared libs. CMake should instead give you a warning at generate, this would save some time.

**Comment by adler-j** [comment]
Fix available in fork:

https://github.com/odlgroup/STIR/commit/5a6e0020fe8b76df33d2356a46aedd23e4743ae3

**Comment by KrisThielemans** [comment]
in fact, on Linux you can build without shared library as long as you add -fPIC (that's what I do as currently shared libraries in STIR run into recursion problems on many systems due to interdependencies of the libraries which we need to fix)

**Comment by adler-j** [comment]
Oh, then you could check if the cmake flag `POSITION_INDEPENDENT_CODE` is true, or `BUILD_SHARED_LIBS` is true.
