### ISSUE TITLE
ITK_USE_FILE

### ISSUE THREAD

**Issue by rijobro** [UCL/STIR#312]
We should be able to do away with the `find_package(ITK)` in `STIRConfig.cmake`. However we can't at the moment because we don't do:
```
include(${ITK_USE_FILE})
```

_Originally posted by @KrisThielemans in https://github.com/UCL/STIR/pull/310#issuecomment-458737138_

**Comment by KrisThielemans** [comment]
#399 introduces `ITK_USE_FILE`. However, it doesn't remove the need for `find_package(ITK)` in `STIRConfig.cmake` as I claimed above. No idea why I thought that...
