### ISSUE TITLE
Provide set/get functions for image parameters in AnalyticReconstruction

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#326]
We currently don't have `set/get_zoom` etc. This creates trouble for SIRF. https://github.com/CCPPETMR/SIRF/issues/354

Sadly, since #325 it means we need a lot of modifications in [stir::ParseDiscretisedDensityParameters](https://github.com/UCL/STIR/blob/master/src/include/stir/ParseDiscretisedDensityParameters.h) (providing `set/get` there as well). That isn't ideal as we then need to forward the calls, but ok. Maybe we could declare `AnalyticReconstruction` a `friend`?

**Comment by rijobro** [comment]
It would be great to squeeze this one through, as Travis is red for all SIRF DEVEL=ON at the moment. 

I would do it, but I'm not sure concretely what the `set` and `get` methods should do (since it's not as trivial as setting it to a member variable).

**Comment by KrisThielemans** [comment]
closed by #330
