### ISSUE TITLE
DICOM series reader restrictions can result in incomplete volumes

### ISSUE THREAD

**Issue by bathomas** [UCL/STIR#332]
Series restrictions can result in incomplete reading of DICOM volumes. This affects CT data - particularly cine CT - and likely MR too.

https://github.com/UCL/STIR/blob/3a277f7a819f35a553a8d6097402ea25cf55a240/src/IO/ITKImageInputFileFormat.cxx#L445

**Comment by ashgillman** [comment]
Yes, I think I've had issues with this line also. I guess the problem is how to read a single frame of a dynamic PET recon otherwise. I guess though, do you even want to do that? Maybe its better to read the whole series and choose a frame.
