### ISSUE TITLE
BinNormalisation::apply should use timing info from ExamInfo

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#340]
`BinNormalisation::apply` uses explicit timing arguments (only used for dead-time). we should get these from the `ExamInfo` instead.

**Comment by KrisThielemans** [comment]
postpone till #44 done, as there are changes there to the norm classes

**Comment by KrisThielemans** [comment]
seems best to pass `exam_info` to `set_up`

**Comment by danieldeidda** [comment]
> 
> 
> seems best to pass `exam_info` to `set_up`

Shall we have a exam_info member in BinNormalisation?

**Comment by KrisThielemans** [comment]
would then have to be, yes. The point is that we shouldn't have to pass timing explicitly in all the `apply`/`undo` calls. (We'd have to allow it in any initial step, as otherwise we get into backwards compatibility issues and trouble with SIRF and STIR versions).

However, note that this is the longer term solution as we discussed. I think we should only tackle this after merging #564 for instance.

**Comment by danieldeidda** [comment]
with "any initial step" you mean something like set_up(). right?

**Comment by KrisThielemans** [comment]
Depends where we are on the path. I think we can resolve #446 (with decay) first without working on this one.

**Comment by danieldeidda** [comment]
BinNormalisationWithCalibration is ready but it only includes calibration factor and branching ratio. Didn't we say we need to separate decay correction for SPECT and PET?

**Comment by KrisThielemans** [comment]
yes. sure.

**Comment by danieldeidda** [comment]
The part for SPECT is already done shallI leave it there or shall I create something like BinNormalisationDecayRotatingScanners  and BinNormalisationDecayStaticScanner (maybe static is not the best world?) This can directly be derived from BinNormalisation I would think.
