### ISSUE TITLE
Energy window threshold for root

### ISSUE THREAD

**Issue by ludovicabrusaferri** [UCL/STIR#356]
In "InputStreamFromROOTFIle.cxx":
    this->parser.add_key("low energy window (keV)", &this->low_energy_window);
    this->parser.add_key("upper energy window  (keV)", &this->up_energy_window);

The the energy thresholds are given in keV. However, gate energies are stored in MeV. Either the energy or the energy window threshold need to be rescaled.
Currently this doesn't create any problem as the threshold values are set respectively to 0 and 1000.

**Comment by KrisThielemans** [comment]
Good spot. I prefer to rescale the energies when reading from ROOT. That way, STIR remains in keV

Kris

________________________________

**Comment by robbietuk** [comment]
This can be closed as it was fixed with #736
