### ISSUE TITLE
Detector Swap in ROOT

### ISSUE THREAD

**Issue by ludovicabrusaferri** [UCL/STIR#359]
The current code swaps both the detectors and the rings : https://github.com/UCL/STIR/blob/9be73d4615e4cd53a6fbc2abdd6ebf4e8f85e59d/src/listmode_buildblock/CListRecordROOT.cxx#L91-L100

this needs to be removed as it can create problems with matching the detector with photon energy and arrival time.

It has been already fixed in the time-of-flight branch but not in the master.

**Comment by KrisThielemans** [comment]
See #360

**Comment by KrisThielemans** [comment]
closed by #360
