### ISSUE TITLE
Post-smoothing forward projector and post-smoothing back projector needn't exist

### ISSUE THREAD

**Issue by rijobro** [UCL/STIR#364]
Firstly, their names are potentially misleading as they can apply any type of `DataProcessor`, not just smoothing (e.g., motion). Instead of renaming them something more generic, we can simply absorb them into the main projectors. That is to say, have a method `set_pre_data_processor` and `set_post_data_processor`. If present, do these at the correct moment. 

This will now be possible thanks to PR #362, allowing data processors to be applied to the forward projector during `set_input` and after the back projection during `get_output`.

**Comment by KrisThielemans** [comment]
This has been done #367. Remaining clean-up is in #389.
