### ISSUE TITLE
ListMode objective function have a condition with find_basic_bin()

### ISSUE THREAD

**Issue by danieldeidda** [UCL/STIR#366]
Find_basic_bin() always returns false as a consequence the reconstruction can skip  all events

**Comment by danieldeidda** [comment]
In line 476 of PoissonLogLikelihoodWithLinearModelForMeanAndListModeDataWithProjMatrixByBin,cxx


`if (this->num_subsets > 1)
            {
                Bin basic_bin = measured_bin;
                if (!this->PM_sptr->get_symmetries_ptr()->find_basic_bin(basic_bin) ||
                        subset_num != static_cast<int>(basic_bin.view_num() % this->num_subsets))
                    continue;
            }
`

the solution is:
`if (this->num_subsets > 1)
            {
                Bin basic_bin = measured_bin;
                this->PM_sptr->get_symmetries_ptr()->find_basic_bin(basic_bin);
                if (subset_num != static_cast<int>(basic_bin.view_num() % this->num_subsets))
                    continue;
            }
`

**Comment by NikEfth** [comment]
Is this the case were you do not use any symmetries at all?

**Comment by danieldeidda** [comment]
Yes, I haven't used any symmetry with SPECT


#####################################

Daniel Deidda, PhD, Higher Research Scientist,

National Physical Laboratory, G6A3,

Hampton Rd, Teddington TW11 0LW.

#####################################



________________________________
