### ISSUE TITLE
ROOT ECAT system has bugs

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#369]
The conversion from ROOT blocks/crystals to STIR rings/crystals is incorrect.
https://github.com/UCL/STIR/blob/67c4f1fa307ae0de14412c58d7e90a6498f995a7/src/IO/InputStreamFromROOTFileForECATPET.cxx#L89-L99
it only works ok if `crystal_repeater_z=crystal_repeater_y`.

compare to https://github.com/UCL/STIR/blob/67c4f1fa307ae0de14412c58d7e90a6498f995a7/src/IO/InputStreamFromROOTFileForCylindricalPET.cxx#L93-L95 and https://github.com/UCL/STIR/blob/67c4f1fa307ae0de14412c58d7e90a6498f995a7/src/IO/InputStreamFromROOTFileForCylindricalPET.cxx#L101-L104

**Comment by KrisThielemans** [comment]
@NikEfth, @ludovicabrusaferri is preparing a PR for this.

**Comment by KrisThielemans** [comment]
@ludovicabrusaferri I guess you fixed this? Please close the issue then

**Comment by KrisThielemans** [comment]
@ludovicabrusaferri could you confirm this is fixed (and close)? sorry

**Comment by ludovicabrusaferri** [comment]
@KrisThielemans I do confirm this is fixed but I don't think I can close the issue as I didn't create it
