### ISSUE TITLE
list_roi_values could print image name in the same raw as the roi values

### ISSUE THREAD

**Issue by danieldeidda** [UCL/STIR#375]
https://github.com/UCL/STIR/blob/a72db6d73dc9a85df869600d9cd6f766856124d8/src/utilities/list_ROI_values.cxx#L236

At the moment the name of the image is  printed before the table for the ROIs:

output_images/AC_SC_CORC_UC_DC_NRC_12.hv
            ROI          Mean          Stddev             CV         Volume
        medulla          0.00597686          0.00796737          1.33304          60925.8
         spleen     0.00109266     0.00384564        3.51951         128220
output_images/AC_SC_CORC_UC_DC_NRC_24.hv
            ROI          Mean          Stddev             CV         Volume
        medulla     0.00740933      0.0145732        1.96688        60925.8
         spleen      0.0013633     0.00693401        5.08619         128220
output_images/AC_SC_CORC_UC_DC_NRC_36.hv
            ROI          Mean          Stddev             CV         Volume
        medulla       0.007454      0.0183482        2.46152        60925.8
         spleen     0.00135662     0.00776648        5.72487         128220

However, It is more useful if the name is part of another coulumn as follows:

                   ImageName                                   ROI          Mean          Stddev             CV         Volume
  AC_SC_CORC_UC_DC_NRC_12.hv      medulla     0.00598     0.00797           1.33        60925.8
  AC_SC_CORC_UC_DC_NRC_12.hv      spleen       0.00109     0.00385            3.52       128220

                   ImageName                                   ROI          Mean          Stddev         CV         Volume
AC_SC_CORC_UC_DC_NRC_24.hv         medulla     0.0074      0.0145        1.967       60925.8
AC_SC_CORC_UC_DC_NRC_24.hv         spleen      0.0014      0.0069        5.086         128220

In this way, we can create a CSV file that can be modified to create new columns with the information contained in the name ( ex: one column for attenuation correction, one for decay correction etc., or you could have different algorithm parameters.)

**Comment by KrisThielemans** [comment]
I agree. it's a change that breaks backwards compatibility though, but I guess minor.

If you create a PR, please document clearly in the release notes.

**Comment by danieldeidda** [comment]
Hi,
Why does this break backwards compatibility? will the release note be "release_3.1.htm"?

**Comment by KrisThielemans** [comment]
the file format would change, which is going to trip someone up presumably.

Yes, release notes are still 3.1. We'll rename this before actual release of 4.0 of course.

**Comment by KrisThielemans** [comment]
fixed by #376.

@danieldeidda, can you put something like "fixed #375" net time in your commit message? Then github will auto-close the issue.

**Comment by danieldeidda** [comment]
shall I do this commit on my branch?

**Comment by KrisThielemans** [comment]
sorry. this was a recommendation for the future. If you open an issue, and then fix it with a PR. It's best to specifiy in the relevant commit that you fixed an issue. (Alternatively, I have to remember to put it in the merge commit message).
