### ISSUE TITLE
Travis OSX with ROOT timeout due to compile from source

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#386]
currently all Travis jobs fail for osx when using ROOT as it wants to compile it from source, and then times-out. example https://travis-ci.org/UCL/STIR/jobs/598767861. problem
```
==> Installing root
Warning: Building root from source:
  The bottle hardcodes locations inside Xcode.app
==> Downloading https://root.cern.ch/download/root_v6.18.04.source.tar.gz
<snip>
```
This is both with `osx_image: xcode9` and the default `osx_image`, which according to the [Travis table](https://docs.travis-ci.com/user/reference/osx/) is XCode 9.4 on macOS 10.13. This should be High Sierra . The binaries ("bottle") should be available though, see https://bintray.com/homebrew/bottles/root/6.18.04#files but maybe not for this XCode version.

Anyone knows which XCode/OS version `brew` does have the bottle? @rijobro @bathomas @ludovicabrusaferri?

**Comment by rijobro** [comment]
I'm on macOS 10.14.6 (Mojave), and `xcodebuild -version` returns `Xcode 11.0`. 

`brew install root` installs without and problems and doesn't build from source.

I see that from the link you sent, `root` should be available with `osx_image: xcode9`. However, since it's not working, should we just set it to `osx_image: xcode11` and see what it does?

**Comment by rijobro** [comment]
I've created the PR here: #387 , let's see.

**Comment by rijobro** [comment]
`Xcode 11.0` same error:
```
/usr/local/Cellar/xrootd/4.10.1: 296 files, 7.8MB

[32m==>[0m [1mInstalling [32mroot[39m[0m

[33mWarning:[0m Building root from source:

  The bottle hardcodes locations inside Xcode.app

[34m==>[0m [1mDownloading https://root.cern.ch/download/root_v6.18.04.source.tar.gz[0m

```

**Comment by KrisThielemans** [comment]
no longer using Travis
