### ISSUE TITLE
OSSPS test fails, but silently 

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#393]
I spotted the following in https://travis-ci.org/UCL/STIR/jobs/599837970
```
$ ./run_test_simulate_and_recon.sh
...
=============================================
Using /home/travis/build/UCL/STIR/install/bin/OSSPS
=============================================
Running OSSPS OSSPS_test_sim_PM_QPweights.par
Input ROI mean: 1
Output ROI mean: 2.84969
DIFFERENCE IN ROI VALUES IS TOO LARGE. CHECK RECONSTRUCTION LOG my_OSSPS_test_sim_PM_QPweights.par.log
=============================================
There were errors. Check  my_OSSPS_test_sim_PM_QPweights.par.log
...
The command "./run_test_simulate_and_recon.sh" exited with 0.
```
2 problems of course:
- the test fails 
- the failure isn't reflected in the return code of `run_test_simulate_and_recon.sh`

I have not investigated since when this is happening. @rijobro maybe you could have a look?

**Comment by rijobro** [comment]
Just checked through master builds on travis and it looks like the first time OSSPS fails is due to PR #362: https://travis-ci.org/UCL/STIR/builds/574564312

**Comment by rijobro** [comment]
I've had a look but I can't see anything that's immediately obvious. I ran the test in debug mode, no errors there either. Presumably, there's a missing `start_accumulating_in_new_target` somewhere or something like that?

**Comment by KrisThielemans** [comment]
The `run_tests.sh` failed on OSSPS as well. Travis didn't know.

**Comment by KrisThielemans** [comment]
seems all `run*.sh` should have `exit 1` when the tests failed. They just return 0 anyway!

**Comment by KrisThielemans** [comment]
Found the problem with OSSPS. The `PoissonLogLikelihoodWithLinearModelForMeanAndProjData<TargetT>::
actual_add_multiplication_with_approximate_sub_Hessian_without_penalty` function is supposed to accumulate the output (that's what the name says), but it overwrites what was there.
