### ISSUE TITLE
Install removes binaries

### ISSUE THREAD

**Issue by adler-j** [UCL/STIR#4]
When running `make install`, the following type of messages are given repeatedly:

```bash
-- Installing: /usr/local/lib/libanalytic_FBP3DRP.so
-- Removed runtime path from "/usr/local/lib/libanalytic_FBP3DRP.so"
```

This causes python to crash since it cannot access the library:

```python
>>> import stir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "stir.py", line 28, in <module>
    _stir = swig_import_helper()
  File "stir.py", line 24, in swig_import_helper
    _mod = imp.load_module('_stir', fp, pathname, description)
ImportError: libanalytic_FBP3DRP.so: cannot open shared object file: No such file or directory
```

A solution is to select (when configuring) `CMAKE_SKIP_RPATH`. I suggest this either be the default, or give users a warning if they try compiling without it.

EDIT: it seems the suggested fix does not help with the python error, which persists.

**Comment by adler-j** [comment]
This seems to be an issue with `usr/local/lib` not being added to the runtime loader by default in Ubuntu, I'll close it for now.

**Comment by KrisThielemans** [comment]
yes. this is probably one for the wiki. wherever the shared libraries are installed will need to be in the relevant path for your system (PATH for Windows, LD_LIBRARY_PATH for Linux, no idea for Mac) or added to the system loader.

would you mind adding it?

**Comment by adler-j** [comment]
I may sound ignorant, but where is the wiki?
