### ISSUE TITLE
find_package(X11) causing failure on OSX

### ISSUE THREAD

**Issue by rijobro** [UCL/STIR#414]
Not sure if this is specific to my machine or because I've just updated to OSX Catalina, but `cmake` currently fails:

```
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.15/Modules/FindFontconfig.cmake:59 (file):
  file STRINGS file "/usr/X11/include/fontconfig/fontconfig.h" cannot be
  read.
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.15/Modules/FindX11.cmake:208 (find_package)
  src/display/CMakeLists.txt:11 (find_package)
```

This is in the display folder, even though I've set `Graphics` to `None`. Currently solved by commenting out the problematic line.

**Comment by KrisThielemans** [comment]
this is tricker then you'd hope as `if(DEFINED CACHE{<name>}` only exists from CMake 3.14 and doing something like
```cmake
if (NOT "${GRAPHICS}" STREQUAL "None")
  find_package(X11)
endif()
```
is dangerous, as it will create a local (i.e. non-cached) CMake variable `GRAPHICS` as far as I  recall.

maybe
```cmake
set(GRAPHICS X 
    CACHE STRING "Type of graphics to use. Choose X, PGM or None")
if( "${GRAPHICS}" STREQUAL "X")
   find_package(X11)
   if(NOT X11_FOUND)
      message(WARNING "X11 not found. Setting GRAPHICS to PGM")
      set(GRAPHICS PGM)
    endif()
endif()
```

**Comment by rijobro** [comment]
Seemed this problem went away after updating command line tools. I'll close this for now, and we can potentially implement your suggested fixes if ever it comes back.
