### ISSUE TITLE
HKEM with a constant anatomical prior causes a NaN image

### ISSUE THREAD

**Issue by ashgillman** [UCL/STIR#415]
Setting the anatomical image to a uniform image (to get no anatomical information) causes the image to be completely filled with NaN values after a single iteration.

@danieldeidda , is the image divided by the standard deviation for normalisation by any chance?

**Comment by ashgillman** [comment]
@harrymarquis

**Comment by danieldeidda** [comment]
> Setting the anatomical image to a uniform image (to get no anatomical information) causes the image to be completely filled with NaN values after a single iteration.
> 
> @danieldeidda , is the image divided by the standard deviation for normalisation by any chance?

Yeah! I didn't think about it. Myabe is worth adding a condition like only_functional
if true set Km=1

**Comment by danieldeidda** [comment]
> > Setting the anatomical image to a uniform image (to get no anatomical information) causes the image to be completely filled with NaN values after a single iteration.
> > @danieldeidda , is the image divided by the standard deviation for normalisation by any chance?
> 
> Yeah! I didn't think about it. Maybe is worth adding a condition like only_functional
> if true set Km=1

or actually even easier we can set the SD=1

**Comment by markus-jehl** [comment]
This looks like it can be closed.

**Comment by KrisThielemans** [comment]
@danieldeidda ?
@markus-jehl did you test it?

**Comment by danieldeidda** [comment]
yes this  was fixed
