### ISSUE TITLE
LmToProjDataBoostrap not working

### ISSUE THREAD

**Issue by danieldeidda** [UCL/STIR#425]
I have been trying this utility with PET and SPECT data. I f I use num_events=-1 it runs OK but the sinogram produced is empty.  when I set any number of subset the utility crashes.
If I use frames it runs again but the sinogram is empty. For frames shorter than acquisition time the program crashes.

it seems to me that the event are being replicated but not stored in their associated bin.

**Comment by KrisThielemans** [comment]
not sure yet why, but
https://github.com/UCL/STIR/blob/75b24a566e9d84fb41adccf06005ac6ec09280aa/src/listmode_buildblock/LmToProjDataBootstrap.cxx#L153
should not do `else if` but just `if`, as it'd break for listmode file formats where the event contains both time and detector stuff (such as ROOT)

**Comment by KrisThielemans** [comment]
seems that we'll need to do something like
```
  CListModeData::SavedPosition start_of_this_frame =
     lm_data_sptr->save_get_position();
```
at the start (potentially somewhat optimised to save the position around [here](https://github.com/UCL/STIR/blob/75b24a566e9d84fb41adccf06005ac6ec09280aa/src/listmode_buildblock/LmToProjDataBootstrap.cxx#L151) when we get the first timing event in the frame), and then go back to that position at the end of the `start_new_time_frame` function

**Comment by danieldeidda** [comment]
> seems that we'll need to do something like
> 
> ```
>   CListModeData::SavedPosition start_of_this_frame =
>      lm_data_sptr->save_get_position();
> ```
> 
> at the start (potentially somewhat optimised to save the position around [here](https://github.com/UCL/STIR/blob/75b24a566e9d84fb41adccf06005ac6ec09280aa/src/listmode_buildblock/LmToProjDataBootstrap.cxx#L151) when we get the first timing event in the frame), and then go back to that position at the end of the `start_new_time_frame` function

We can get the same  result by just calling this->lm_data_ptr->reset(); at the end of the `start_new_time_frame`.

**Comment by danieldeidda** [comment]
I get around 40% less events wit bootstrap. It might be because the replication are done considering all events while we have energy window rejection  in the get_bin() which is only called by lmtoprojdata

**Comment by KrisThielemans** [comment]
> We can get the same result by just calling this->lm_data_ptr->reset(); at the end of the start_new_time_frame.

that might be true, but could  be quite inefficient of the frame starts qutie late in the listmode file

**Comment by KrisThielemans** [comment]
> I get around 40% less events wit bootstrap. It might be because the replication are done considering all events while we have energy window rejection in the get_bin() which is only called by lmtoprojdata

hmmm. not good. I can't see this to be correct. One way of thinking about that is that we'd bootstrap the rejected and accepted events separately. On average, these should both give the same number of counts. some other bug...
