### ISSUE TITLE
`KOSMAPOSLReconstructor` doesn't write output image at end of run.

### ISSUE THREAD

**Issue by ashgillman** [UCL/STIR#429]
OSMAPOSL will write images when iteration % save_interval ==0, and at the end of the program. However, KOSMAPOSL will only write images in the former case. So if the number of iterations is not a multiple of the save interval, you don't get a final image.

@danieldeidda is this because of the extra half iteration required?

**Comment by danieldeidda** [comment]
"OSMAPOSL will write images when iteration % save_interval ==0, and at the end of the program" Is that so? 
This is decided in the parameter file.  So if you say in the parfile that you want to save images every N subiterations, then it makes sense to give a total subiteration number that is a multiple, k, of N. I thought OSMAPOSL would do the same, but I never tried to put a number of subiterations which is not a multiple of the interval. Is there a reason why we would want to write the last?

**Comment by KrisThielemans** [comment]
fixed with #436
