### ISSUE TITLE
2D NIfTI images read with z-spacing = 1

### ISSUE THREAD

**Issue by rijobro** [UCL/STIR#456]
I have a NIfTI image, which has 1 voxel in the z-direction. The spacing is 2.03125mm. However, when I load it into STIR, the voxel spacing is set to 1 mm.

This can be seen with `stir_print_voxel_sizes.sh`, which prints a value of 1, and `stir_math` converts the NIfTI to interfile but sets the incorrect z-spacing.

**Comment by KrisThielemans** [comment]
sorry. This seems to be an ITK NiftiIO problem.

We call a normal ITK reader
https://github.com/UCL/STIR/blob/e7864977c4547951d967892480612c94dd69e507/src/IO/ITKImageInputFileFormat.cxx#L413-L422
and then convert to STIR using 
https://github.com/UCL/STIR/blob/e7864977c4547951d967892480612c94dd69e507/src/IO/ITKImageInputFileFormat.cxx#L290-L293

Possibly you want to run a check that indeed the `GetSpacing[2]=1`. If so, not much we can do about it, aside from testing with ITK 5, and potentially raising in issue with ITK.

**Comment by KrisThielemans** [comment]
Needs nifti images that have `num_dimensions` set to 3, otherwise there is nothing we can do about it.
