### ISSUE TITLE
examples/src forward project errors

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#463]
Following the README.txt instructions. After running 
   `generate_image generate_image.par` 
calling  
   `forward_project sino.hs image.hv  small.hs` 
results in the following error.

`ERROR: forward_project: Imaging modality should be the same for the image and the projection data
libc++abi.dylib: terminating with uncaught exception of type std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >
Abort trap: 6`

**Comment by rijobro** [comment]
what mentions of imaging modality are there in `sino.hs`, `image.hv` and `small.hs`? Either they're different (in which case the error is correct), or maybe one of them is unspecified, in which case I would have thought that STIR would assume it was PET.

**Comment by robbietuk** [comment]
Fixed by adding 

`!imaging modality := PET` to the small.hs file. This line was not present. I agree, STIR should have defaulted to PET?

I will make a PR for the demo.

**Comment by KrisThielemans** [comment]
I'm a bit surprised by this. It should indeed have defaulted to PET both for the image and the template, as I don't think most other examples are specifying the modality (hence the tons of warnings about it).

Still, fixing it by providing the modality is a good idea.
