### ISSUE TITLE
add C++ demo on using objective function hierarchy

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#465]
We need a demo like the ones in `examples/src` that creates an objective function and compute its value and gradient.

Sadly, it's currently somewhat involved in STIR to create an objective function from C++. We could do it via a reconstruction parameter file, and then use `get_objective_function`.

Code to do all this is in https://github.com/UCL/STIR/blob/master/src/recon_test/test_PoissonLogLikelihoodWithLinearModelForMeanAndProjData.cxx

**Comment by KrisThielemans** [comment]
@robbietuk, as discussed

**Comment by robbietuk** [comment]
Working on it!
