### ISSUE TITLE
Upsampler does not seem to check scanner dimention sizes

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#468]
Running 
`upsample_and_fit_single_scatter  --min-scale-factor 1 --max-scale-factor 1 \
    --output-filename ${output}_pre_norm.hs --data-to-fit ${norm} --data-to-scale ${OUTPUT_PREFIX}.hs --weights ${norm} 2> ${output}_stderr.log`
from simulate_scatter.sh in the recon test pack.

${norm} has:
`Number of rings                          := 2
Number of detectors per ring             := 560`
whereas ${OUTPUT_PREFIX}.hs has:
`Number of rings                          := 8
Number of detectors per ring             := 64`
The returned ${output}_pre_norm.hs was of the same size as ${norm} but the values were all 0.

I believe this is related to the attempt to upsample from 8 rings to 2. Should STIR have a warning in the upsampler when it can't upsample an axis?

**Comment by robbietuk** [comment]
When reducing the number of rings (and relavent parameters related to z axis of downsampled sinogram), the upsampled sinograms are non-zero.

**Comment by KrisThielemans** [comment]
I believe there are more checks in the scatter PR #44 
If you feel like it, you could try that first.

I hope to find some time this week to finalise that PR (but then again, I 've been hoping that for a long time now...)

**Comment by robbietuk** [comment]
I believe this can be closed now as #44 is merged and the aforementioned checks should be implemented
