### ISSUE TITLE
SPECT failures since merge of #445

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#472]
recon_test_pack's `run_SPECT_tests.sh` are failing since merge #445 (not sure why I merged it!).

tail of `out/OSEM_2DPSF.log` shows that it's failing in the very first computation. The error gets thrown here
https://github.com/UCL/STIR/blob/0d11904982fd482ff8927c22d810427737c929c6/src/recon_buildblock/SPECTUB_Weight3d.cxx#L278

I guess this implies that the matrix row size is not consistent with what was calculated before.

@danieldeidda I'm afraid this is yours. Possibly related to your problematic fix for #452 but then maybe not.

**Comment by danieldeidda** [comment]
mh the only thing I changed in that class is the direction of the axis. I am not sure how this would affect the size but I'm gonna look into it
