### ISSUE TITLE
CMake ROOT variable

### ISSUE THREAD

**Issue by NikEfth** [UCL/STIR#48]
CMake variable HAS_GLOBAL_ROOT. Can we rename this to HAS_GLOBAL_CERN_ROOT. Or HAS_CERN_ROOT_CONFIG? Or even better CERN_ROOT_CONFIG (no reason to have the "HAS")

Otherwise the user might think this ROOT variable is something else entirely.

**Comment by KrisThielemans** [comment]
closed with PR #49
