### ISSUE TITLE
Reconstruct::set_up and ProjectorPair::set_up when using reduced segment range

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#51]
the following causes a crash or causes surprising behaviour

> proj_data = ...
> shared_ptr<ProjectorPairByBin> p = ...
> p->set_up(proj_data.get_proj_data_info_sptr())
> recon.set_projector_pair_sptr(p)
> recon.set_max_segment_to_process(3) // lower number than in actual data
> recon.set_up()
> p->forward(image)

This last forward projection will either only forward project the reduced range, or crash when it goes out-of-range. 
Reason: recon_set_up() calls p.set_up() with a reduced proj_data_info.

Possible fix: let p.set_up() check if it has been set-up with a "large enough" range. if so, keep its previous settings.

**Comment by NikEfth** [comment]
I feel that recon.set_up() should not be able to edit whatever p is pointing to. 
If the user want to reduce the range should do it directly to p and than recon will have to use that.

**Comment by KrisThielemans** [comment]
Although I agree with @NikEfth, this is a difficult choice.

It's clear that the current behavour is far too dangerous. An easy thing to do would be to remove `set_max_segment_to_process`. Although this nice and clean, it would be a serious backwards compatibility issue. In any case, it still doesn't prevent us from doing similar dangerous stuff.

Description of the problem
-----------------------------
I think it makes a lot of sense performance-wise to be able to share projectors. They potentially store a lot of stuff in memory. you want to be able to have multiple reconstructors or forward projectors re-using the same projector object. Preventing this would potentially have major performance impact. In addition, it is kind of re-assuring to know that you can forward project with the same projector as used by your recon. So, I think that **sharing of projectors is necessary**.

Question is then if we can force that the object pointed to by the `shared_ptr` is not changed. It seems only possible if `set_up()` would be a const member, but that is logically rather weird or even impossible (of course you're going to change your projector if you set it up!). I believe therefore that **`recon.set_up()` has to be able to modify the `shared_ptr` to the projector** (and similar if you construct a pair of projectors, its `set_up()` has to change the underlying forward/back-projectors).

So, enforcing at compile time that recon (or whatever) doesn't change the projector seems impossible. What about run-time solutions?

A potential solution might be to let set_up check if the ref-count is > 1, if so, throw an error. However, who knows who owns another `shared_ptr` to your projector? Even in the above example, you'll very likely end up with a ref count of 2 even if you don't have a forward projector. I cannot see how this could work in practice. 

Proposal 
----------
What seems feasible is to let `projector.set_up()` do a consistency check:
1. i haven't been set-up yet, go ahead
2. I have been set-up, I check that I can handle the new data (simplest is a check that it's the same geometry, a more involved check would be to see if the new data is a subset of how I was set-up). If so, I do nothing, otherwise I complain.

The disadvantage is that you'd need to create a different projector for any data with different geometry.
Potentially add a `reset()` function or so that says to ignore whatever went on before. That seems to be a loophole with all the `shared_ptr` stuff though.

Note that most on-the-fly projectors probably don't store state, so don't care whatever you set it up with. So, all of this is reducing flexibility. Ah well, we cannot win all the time :-;
