### ISSUE TITLE
Request: get_total_number_of_events() from listmode files. 

### ISSUE THREAD

**Issue by NikEfth** [UCL/STIR#52]
A simple function to be added in the CLimodeData interface, which will return the total number of events. 
I will implement it for ROOT files, while for the rest of Listmode data, temporarily it will throw an error. 

I don't add this feature directly in the listmode reconstruction branch. Because I regard it more as data feature which should have an issue id, until the function has been implemented for all listmode classes.

**Comment by KrisThielemans** [comment]
This function was added in  9976161af63336f6a133d9d2f67d42781c4e27b9
