### ISSUE TITLE
add axpby for Array

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#560]
https://github.com/UCL/STIR/pull/557 added `axpby` (a*x+b*y) as
```c++
  virtual void ProjData::axpby(const float a, const ProjData& x,
                     const float b, const ProjData& y);
```
modifying `*this`. This would be useful to have for `stir::Array` as well.

However, Intel's [MKL axpby](
https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-c/top/blas-and-sparse-blas-routines/blas-like-extensions/cblas-axpby.html) and other BLAS libraries (e.g. [ATLAS](http://www.netlib.org/atlas/developer/atlas_contrib/node54.html), [Math-BLAS](https://metacpan.org/pod/Math::BLAS)) modify `y` instead.

Note that `axpby` is not a standard BLAS function, but `axpy` is. I couldn't immediately find the BLAS standard, but [this ref](https://northstar-www.dartmouth.edu/doc/idl/html_6.2/BLAS_AXPY.html) says that `axpy` modifies `y`.

I find that convention a bit weird, but I suppose it's best to stick to BLAS, such that at some point we could use BLAS libraries.

**Comment by KrisThielemans** [comment]
The "appropriate" signature should be implemented as a static function. However, the difficulty with making this a static member is that we cannot use `virtual`.

**Comment by KrisThielemans** [comment]
For the fun of it, here's a link to the [overview of Boost ublas](https://www.boost.org/doc/libs/1_72_0/libs/numeric/ublas/doc/overview.html) which does interesting things with expression templates and implements maps `y += *x` as the equivalent of `apxy` (not so surprisingly). Obviously that can't be done with `axpby`.

**Comment by rijobro** [comment]
I find the python signature in SIRF a little confusing. I imagine it comes from CIL, so maybe @paskino knows why theirs is that way:

```
def axpby(self, a, b, y, out=None, **kwargs):
```
I find it confusing because the two scalars are separated in the method name, but together in the signature.

To me, your first signature makes the most sense, @KrisThielemans. `this->(a,x,b,y)`, such that `self` is modified. Doesn't have to be static in that case.

**Comment by paskino** [comment]
The C signature in CIL is [here](https://github.com/vais-ral/CCPi-Framework/blob/master/src/Core/axpby.c) 
```c
int daxpby(double * x, double * y, double * out, double a, double b, long size, int nThreads);
```

The reason of the signature in Python is 
```python
def axpby(self, a, b, y, out=None, **kwargs)
```
is that `axpby` is a method of `DataContainer` acting on `self` where `self` is `x`. Therefore there's no need to specify `x`. 

The other option I see in Python is to use a static method
```python
@staticmethod
def axpby(a, x, b, y, out=None, **kwargs)
```
but then it would be called as 
```python
DataContainer.axpby(a,x,b,y,out)
```
which I don't find particularly nice, and maybe this is the reason why I settled on the other signature.

Some time ago I spent some time to measure the [performance ](https://github.com/paskino/acceleration)of different ways to do AXPBY in Python with numpy/scipy/blas/numba and some other tricks.

**Comment by KrisThielemans** [comment]
@evgueni-ovtchinnikov mentioned
> The reason I implemented z = a*x + b*y rather than BLAS axpy (y = a*x + y) was that I wanted to use it for overloading + and -. Adding BLAS axpy, if needed at all, is a trivial job.

**Comment by KrisThielemans** [comment]
> The reason of the signature in Python is
> `def axpby(self, a, b, y, out=None, **kwargs)`
> is that axpby is a method of DataContainer acting on self where self is x. 

so x.axpby(a,b,y)? Confusing name then.

If we don't do all the same, and also if we don't do whatever others do, I think we should adjust our naming. It is very confusing to have one function doing very different things.

CIL signature
> int daxpby(double * x, double * y, double * out, double a, double b, long size, int nThreads);

I strongly suggest you start adding `const` for any pointers that point to stuff that doesn't get modified.

**Comment by KrisThielemans** [comment]
merged #561 with the same signature as Richard's. I'm still not happy about that though. For one thing, it needs creation of an object first, which might be inconvenient.

We could of course easily have 2 versions: one with the current signature, and one where `x` or `y` is `*this`.

As far as I can see, we now have 3 different signatures:
- this->axpby(a,x,b,y) (STIR), modifying `*this`, checking that `*this` is the "same" as `z` and `y`.
- x.axpby(a,b,y, out=None) (SIRF and CIL Python). presumably not modifying x, but returning a new object or filing `out`
- `axpby(a,x,b,y)` modifying `y` (MKL, ATLAS etc)

Can someone propose some names to make clear which is which?

**Comment by evgueni-ovtchinnikov** [comment]
the second might be called `aspby` for `a*s[elf] p[lus] b*y` 

the third might be called `yaxpby` for `y = a*x p[lus] b*y`, and it is obviously static

BTW there is no `axpby` in libraries implementing BLAS - they have `axpy` (my `axpby` actually mimics `gemm` update `z = a*x*y + b*z`, where `x`, `y` and `z` are matrices).

**Comment by KrisThielemans** [comment]
I can live with `self` even if it isn't a C++ concept. Renaming that will impact CIL of course. @paskino ?

the third cannot be renamed in my opinion as MLK and ATLAS etc use it (not BLAS, but BLAST apparently).

if we don't have the third, I still feel that we should avoid a name clash, so we should rename the first.

sorry, but naming is important for a 20 year old project...
first

**Comment by evgueni-ovtchinnikov** [comment]
the first: how about `taxpby` for `*this = a*x + b*y`? (I understand it exists in C++ only.)

**Comment by paskino** [comment]
I've been thinking about this. As @KrisThielemans and @evgueni-ovtchinnikov mention, the function that is normally found in BLAS is `axpy`. However, `axpby` is in [MKL](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-c/top/blas-and-sparse-blas-routines/blas-like-extensions/cblas-axpby.html).

My implementation of `axpby` is a very naive OpenMP implementation developed to speed things up. However, I'm pretty sure that MKL's will be much more efficient even on a single thread because it'll use the hardware better. I'm investigating if and how using [intel's distribution of python](https://software.seek.intel.com/python-distribution) (via conda) is faster than conda-forge's. 

So, I'm considering to use the same signature as MKL where `axpby` (in C) modifies `y`. At the python level, do you think we need to maintain the same signature?

It would still be nice to retain the possibility to not modify `x` or `y` and specify the output; one solution could be to make `axpby` a static method of `DataContainer` and use something like this?

```python

@staticmethod
def axpby(a,x,b,y,out=None):
    if out is None:
        call_axpby(a,x,b,y)
    else:
        out.fill(y)
        call_axpby(a,x,b,out)
```

Notice that we encountered lately with @rijobro 's MCIR the necessity to perform axpby with `a` and `b` as `ndarray`s not scalars.

**Comment by paskino** [comment]
Just another comparison https://github.com/bennylp/saxpy-benchmark

**Comment by KrisThielemans** [comment]
> At the python level, do you think we need to maintain the same signature?

Good question. On the C side, you will probably need `saxpby` and `daxpby` (and is there a complex version?) for compatibility. I would consider whatever happens on the C side as an internal thing that people don't need to know. 

On the C++/Python side we surely don't want to have different names for the same functionality. However, I still think it would be wise to avoid names that would lead to surprises to the user. Worth doing a search on some C++/Python interfaces to BLAS-type libraries. For instance, Eigen is apparently able to call MKL. How does their interface look like?

> Notice that we encountered lately with @rijobro 's MCIR the necessity to perform axpby with a and b as ndarrays not scalars.

Not sure if there's an MKL/ATLAS/whatever equivalent of that. There's tons of operations that you could optimise. Pick the ones that matter. 


> My implementation of axpby is a very naive OpenMP implementation 

Just a warning that writing to an array with openmp can give race conditions, see [one post on this](http://forum.openmp.org/forum/viewtopic.php?f=3&t=1551). https://github.com/bennylp/saxpy-benchmark/blob/master/src/saxpy_omp.cpp tries to get round this with "interleaving" but I cannot see that this avoids the problem. (it seems it turned out to be slower anyway).

Obviously this kind of stuff is exactly why BLAS-type libraries exist. We've never bothered with them in STIR as the projectors are much slower than anything else, but it changes with sophisticated regularisation schemes of course.

**Comment by gfardell** [comment]
I can't see how there would be a race-condition with a simple implementation:
y[i] = a*x[i]+b*y*[i]

Each thread is reading from and writing to a single element. Even if x and y are the same it would be ok. The only issue I can see is if x and y point to the same data with an offset, which would take some effort from the user at least on the cil side.

I can see there would be performance issues with the interleaved approach because multiple threads are trying to write to different elements in the same cache line. As default openMP chunks the indices up so this shouldn't happen, although I guess we could run over an inner loop to be sure.

**Comment by KrisThielemans** [comment]
This goes a bit beyond what I know, but from what I read, there is a potential race condition when the internal "chunck-size" is larger than the "element-size". Example, `sizeof(x[i])=32` on a 64-bit machine. The following seems dangerous
1. thread 1 get `x[0]` (which means it will actually also store `x[1]` and it updates `x[0]`.
2. thread 2 gets `x[1]` (which means it will actually also store `x[0]` and it updates `x[1]`.
3. thread 1 amalgamates `x[0]` and `x[1]` and puts that in memory
4. thread 2 amalgamates `x[0]` and `x[1]` and puts that in memory

how realistic is this? I don't know, but what I read in the links above implies that you are not guaranteed that it won't happen.

**Comment by KrisThielemans** [comment]
@gfardell you probably know more about openMP than me though!

**Comment by gfardell** [comment]
That led me down an interesting rabbit hole this afternoon!

https://www.openmp.org/spec-html/5.0/openmpsu9.html

> Accesses to variables smaller than the implementation defined minimum size or to C or C++ bit-fields may be implemented by reading, modifying, and rewriting a larger unit of memory, and may thus interfere with updates of variables or fields in the same unit of memory.

On a hardware level I think any computer we care about will be able to write 8-bits atomically. The compiler might do something different, but it seems like the behaviour should be guaranteed by C++ 11.

> In fact, the C++ language, starting from C++11, guarantees that concurrent operations on distinct memory locations have well-defined behavior, i.e. the one you'd expect.

https://stackoverflow.com/questions/46721075/can-modern-x86-hardware-not-store-a-single-byte-to-memory#:~:text=Not%20only%20are%20x86%20CPUs,CPUs%20are%20capable%20of%20it.&text=Another%20consideration%20is%20that%20while,t%20required%20to%20use%20them

**Comment by KrisThielemans** [comment]
> On a hardware level I think any computer we care about will be able to write 8-bits atomically.

sure. "able to". that doesn't mean that the compiler will do that. in general, it will slow you down, so they might chose not to.

> > In fact, the C++ language, starting from C++11, guarantees that concurrent operations on distinct memory locations have well-defined behavior, i.e. the one you'd expect.

we're not using C++ language threading features for this, but openmp. I don't think this sentence applies.

I'm a bit warry about doing something that we don't have control over.

**Comment by KrisThielemans** [comment]
Continuing with the "signature"/"renaming" question. See also https://github.com/vais-ral/CCPi-Framework/issues/613#issuecomment-653432285

Fun is that in Python/C++ we can overload/are overloading with `a` and `b` being a vectors, so the naming of the whole thing is out of the window anyway. Note also that as this is all element-wise, we can swap `ax` with `xa` etc. And of course mathematically we can swap `ax` and `by`. So we need only 2 versions I guess, one where we fill a new object, and one where we update an existing one (of course, we can implement one in terms of the other)

- C++
  - void T::xapyb(const T&x, T2 a, const T&y, T2 b)` set `*this=x*a+y*b`
  - void T::sapyb(float a, const T&y, float b)` sets `*this= (*this)*a + y*b` (could be implemented via  BLAST `axpby(b,y,a,*this)`!). 

- Python interface in SIRF/CIL (different because of use of optional `out` argument)
   - `x.sapyb(a,y,b,out=z)` would call C++ `z.xapyb(x,a,y,b)`
  - `z=x.sapyb(a,y,b)` would call C++ `z.xapyb(x,a,y,b)`

It's undesirable to have Python and C++ names different (STIR Python won't do this), but possibly the names tell the user what it's doing?

**Comment by KrisThielemans** [comment]
Conclusion: we will rename STIR `axpby` to `xapyb` (obviously changing order of arguments). SIRF then needs adapting, and will follow the above conventions.
