### ISSUE TITLE
LmToProjData num_events_to_store

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#60]
the new handling of num_events_to_store isn't quite consistent. stored_num_events is still signed (and i think it's best to keep it that way, as delayed might be subtracted). I therefore think that we should keep num_events_to_store signed long as well. I think that'd still allow a large number of events (~2.1 10^9). going to unsigned buys as only a factor of 2.

If we really think this number is too small we could using long long on systems that support it. Anyone thinks this is necessary?

Or we could use double (allows a large number of ints) but I find that a bit strange and scary (putting a really large number will lead to an infinite loop as it won't increment anymore after a while).

As an additional benefit reverting to a signed type would allow us to avoid backwards-compatibility problems with num_events_to_store=-1 (the previous default).

@NikEfth, what do you think?

**Comment by NikEfth** [comment]
I am planning provide code for normalisation factors calculation and projection matrix creation from large listmode files. The number of events, in both cases can be more than 2 billion.

**Comment by NikEfth** [comment]
It would be great to have the hierarchy of Tahereh's classes so I could build on that. Just a doxygen generated image would be sufficient, to start with.

**Comment by KrisThielemans** [comment]
a factor 2 won't help a lot. you can always use time frames as opposed to num_events. would that not be enough? otherwise we need to do a fair amount of work...

**Comment by NikEfth** [comment]
ok ... I will make all the appropriate changes soon, and upload some fixes.

**Comment by NikEfth** [comment]
👍
