### ISSUE TITLE
Geometric Correction Not Calculated within BinNormalisationFromGEHDF5.cxx

### ISSUE THREAD

**Issue by pwadhwa351** [UCL/STIR#608]
The gemetric correction factors are not yet calculated within the normalisation correction sinogram. There is a separate utility to calculate it. This needs to be re-done and the utility needs to be removed by incorporating it directly into BinNormalisationFromGEHDF5.cxx.

**Comment by AnderBiguri** [comment]
@pwadhwa351 where is the separate utility that you mention?

**Comment by KrisThielemans** [comment]
added to a new project

**Comment by pwadhwa351** [comment]
> @pwadhwa351 where is the separate utility that you mention?

I had a utility to read geometric factors but we had to remove from the current release: https://github.com/pwadhwa351/STIR/blob/ToFscatter_ToFGE/src/utilities/read_geo_factors.cxx

**Comment by KrisThielemans** [comment]
*step1. clean-up*

this is incorrect for GE data
https://github.com/UCL/STIR/blob/f96933e7375e0b3e79b54a9521a8cef73c8c5fc4/src/recon_buildblock/BinNormalisationFromGEHDF5.cxx#L228-L231
as it would give `span=3`, while it has `span=2`. However, it doesn't seem to be used. so cut.

cut https://github.com/UCL/STIR/blob/f96933e7375e0b3e79b54a9521a8cef73c8c5fc4/src/recon_buildblock/BinNormalisationFromGEHDF5.cxx#L534-L548

delete `crystal_interference` related stuff, e.g. https://github.com/UCL/STIR/blob/f96933e7375e0b3e79b54a9521a8cef73c8c5fc4/src/recon_buildblock/BinNormalisationFromGEHDF5.cxx#L523-L528

**Comment by KrisThielemans** [comment]
* step 2: create function for geo-norm-factors

replace
https://github.com/UCL/STIR/blob/f96933e7375e0b3e79b54a9521a8cef73c8c5fc4/src/recon_buildblock/BinNormalisationFromGEHDF5.cxx#L514-L518
with
```c++
if (this->use_geometric_factors())
	  {
	    lor_efficiency_this_pair *=
	    get_geometric_factors(uncompressed_bin);
           }
}
```

**Comment by KrisThielemans** [comment]
*step 3: implement it!*
(I've changed signature)

possibly like this
- create `geo_proj_data_info_cyl` which is at span=2, mash=1, i.e. move following lines to `shared_ptr<ProjDatainfoCylindricalNoArcCorr> GEHDF5Wrapper::create_native_proj_data_sptr`
https://github.com/UCL/STIR/blob/f96933e7375e0b3e79b54a9521a8cef73c8c5fc4/src/buildblock/ProjDataGEHDF5.cxx#L71-L77

- read geo-factors as in the utility

- define
```c++
float get_geometric_factors(const DetectionPositionPair& det_pos_pair)
{
   Bin geo_bin;
   if (geo_proj_data_info_sptr->get_bin_for_det_pos_pair(det_pos_pair) != Succeeded::yes)
     error();
   // find geo factor by using the symmetry in views (TODO possibly swap)
   const int geo_view_num = geo_bin.view_num() % 16; // TODO has to come from somewhere. transaxial_crystals in bucket?
   const int GE_sino_num = ... (convert seg+axialpos to single index)
   const int GE_tang_pos_num = geo_bin.tangential_pos_num()  + geo_proj_dat_info_sptr->get_min_tangential_pos_num(); // possibly swap
   return geo_factors[geo_view_num, GE_sino_num, GE_tang_pos_num];
}
```

**Comment by AnderBiguri** [comment]
@pwadhwa351 @KrisThielemans Where is this function supposed to read from?

https://github.com/UCL/STIR/blob/master/src/recon_buildblock/BinNormalisationFromGEHDF5.cxx#L562

Its used for the dead time, but it seems that its unfinished.

**Comment by KrisThielemans** [comment]
let's ignore dead-time for a while longer. we're only concerned with
https://github.com/UCL/STIR/blob/master/src/recon_buildblock/BinNormalisationFromGEHDF5.cxx#L536

**Comment by AnderBiguri** [comment]
@KrisThielemans To add the Geometric factors, in theory, we need 2 filename inputs to `BinNormalisationFromGEHDF5`. In RDF9, norm contains geo, so only norm is required. 

What do I do? Do I allow for 2 inputs to the constructor, or do I make sure the file `is_norm_file()` first, and error otherwise, and we will fix this in the future if in RDFXX there is no geo contained in norm?

**Comment by KrisThielemans** [comment]
I agree. enforce passing the file with both components (with a gentle error message)

**Comment by AnderBiguri** [comment]
I am a bit stuck in a place that @KrisThielemans you may be able to help me unstuck. I am trying to read the Bin normalization as Palak does, but using the variables in the existing code. 

Palak uses `ProjDataFromHDF5` (I assume now ProjDataGEHDF5) to know segments, `ProjDataInterfile` to load the template etc. If we want to avoid reading the sinogram in the Bin normalization, we can avoid all these ProjData types, but I still need a `ProjData` template somewhere, to 

1. Construct/allocate the  `shared_ptr<ProjDataInMemory>  geo_norm_factors_sptr;` that stores the geo factors (is this the right type for this variable? In any case we need some sort of `ProjData`)
2. get segments (`get_min_segment_num()` etc)

I see that in the same function that we need that, there is a `dynamic_cast<ProjDataInfoCylindricalNoArcCorr*> (ProjDataInfo::ProjDataInfoCTI` that is created from the scanner etc, that its used for the uncompressed scan info. Can I just create another one of these, locally, with just `span=2` and use it for the geo factors loops, initialization etc?

**Comment by KrisThielemans** [comment]
ok, we were going to create a `ProjDataInMemory`, and that will be have to be span=2 so you can create the `ProjDataInfo` indeed using similar lines to what you found. It looks like we should lift the relevant lines from ` ProjDataGEHDF5::initialise_from_wrapper()`.

(Note that you can do `proj_data_info.get_min_segment_num()` as well, you don't need a complete `proj_data`).

**Comment by AnderBiguri** [comment]
Ah yes, thanks for the confirmation! Indeed, I just need a `ProjDataInfo`, which should be (inferring from the name) much cheaper than a full `ProjData`. I can use that one for all the members and initialization, indeed. Thanks!

**Comment by AnderBiguri** [comment]
Another question that got me lost the rabbit hole:

When doing `set_viewgram` and `get_viewgram` or `get_empty_viewgram`, what is the role of the segment and view number? They are clear in `get_viewgram`, but `get_empty_viewgram`? Will the viewgram have a different size (I am inclined towards "no"), or is it just used so if you do `set_viewgram` it knows which one to set? If so, can I create an empty viegram at semgent and view =0 and then reuse it and change its segment and view number? 

I am mostly thinking about 

   1- Not creating a viegram in each loop iteration 
   2- Trying to avoid somehow the final stage of the copying to flip views in Palak's code.

**Comment by AnderBiguri** [comment]
Latest commit in #601 compiles and is supposed to do the right thing. But I don't know how to test it. 

I will continue working on it, trying to tidy up a couple of things and put the flips inside the Wrapper.

**Comment by KrisThielemans** [comment]
@pwadhwa351 did you upload the output with your previous code somewhere ? If so, we could compare against that

**Comment by KrisThielemans** [comment]
@AnderBiguri I've added the content of the PDF and some files in the PR now

**Comment by pwadhwa351** [comment]
> @pwadhwa351 did you upload the output with your previous code somewhere ? If so, we could compare against that

Sorry for the delay, kindly find DOI :10.5281/zenodo.3939512

**Comment by AnderBiguri** [comment]
Current status of this:  

1. when I load the geo factors in ` BinNormalisationFromGEHDF5.cxx`, they are the same as  https://doi.org/10.5281/zenodo.3939512 geo.hs. Yay!

2. `correct_projdata correct_projdata_param.par` takes exponentially longer to compute with each segment. The first are few seconds, the last is >20 minutes. There is something off on  `BinNormalisationFromGEHDF5::get_geometric_factors` or on `correct_projdata`. 

3. Even with the long runs,  I can not match the results of `correct_projdata` with anything in that zenodo database. So perhaps `get_geometric_factors` is not only slow, its also wrong.
