### ISSUE TITLE
LmToProjData crash with arc-corrected template

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#61]
most (but not all) scanners have list-mode data that corresponds to non-arccorrected data. Currently the code crashes (with segmentation fault) when given a wrong template proj_data. In debug mode, this is checked with an assert resulting in

> /src/include/stir/listmode/CListEventCylindricalScannerWithDiscreteDetectors.inl:80: 
>virtual void stir::CListEventCylindricalScannerWithDiscreteDetectors::get_bin(stir::Bin&, const stir::ProjDataInfo&) const: 
>Assertion `dynamic_cast<ProjDataInfoCylindricalNoArcCorr const*>(&proj_data_info) != 0' failed.

We need to write an error message. However, this is not easy, as we probably don't want to do this check in stir::CListEventCylindricalScannerWithDiscreteDetectors::get_bin as it'd slow it down.

**Comment by eliseemond** [comment]
we need to add a method to CListEvent that allows us to check if a particular template can be used or not. LmToProjData then should call that one once.

**Comment by KrisThielemans** [comment]
fixed in 5b1e726925331ea26ed712ffeb5699ba894ef619
