### ISSUE TITLE
replace std::auto_ptr with std::unique_ptr

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#63]
`std::auto_ptr` is deprecated. We need to replace it. The only places where we’re using `auto_ptr` is in the STIR API are 

```
 std::auto_ptr<DataT>   InputFileFormat::read_from_file(…)
 std::auto_ptr<DataT> read_from_file(…)
 std::auto_ptr<SymmetryOperation>
    DataSymmetriesForBins::find_symmetry_operation_from_basic_bin(Bin&) const;
  std::auto_ptr<SymmetryOperation>
   DataSymmetriesForDensels_PET_CartesianGrid::find_symmetry_operation_from_basic_densel(Densel&);
```
When doing this change, I’m also planning to remove the following class member:

```
DiscretisedDensity * DiscretisedDensity::read_from_file(const string& filename)
```
This was there just for backwards compatibility. If you are still using that, you’ll need to replace it with

```
read_from_file<DiscretisedDensity>(…)
```
These changes will break your own code if you use any of these functions of course. You should normally also just be able to replace `auto_ptr` with `unique_ptr`.

For compatibility with old compilers, I will put a
```
#ifdef BOOST_NO_CXX11_SMART_PTR
  #define unique_ptr auto_ptr
#endif
```
in stir/common.h. However, in a future STIR release, we will give up on non-C++11 compilers.

**Comment by casperdcl** [comment]
Are we intending to replace it in all the other files where it's mentioned?
```
./documentation/STIR-developers-overview.tex
./documentation/release_2001_01_12.htm
./src/recon_buildblock/BackProjectorByBinUsingProjMatrixByBin.cxx
./src/recon_buildblock/BackProjectorByBinUsingInterpolation.cxx
./src/recon_buildblock/DataSymmetriesForBins.cxx
./src/recon_buildblock/ForwardProjectorByBinUsingProjMatrixByBin.cxx
./src/recon_buildblock/TrivialDataSymmetriesForBins.cxx
./src/recon_buildblock/ProjMatrixElemsForOneBin.cxx
./src/recon_buildblock/ProjMatrixElemsForOneDensel.cxx
./src/recon_buildblock/DataSymmetriesForDensels.cxx
./src/swig/stir.i
./src/recon_test/test_PoissonLogLikelihoodWithLinearModelForMeanAndProjData.cxx
./src/test/test_OutputFileFormat.cxx
./src/include/stir/ProjDataInMemory.h
./src/include/stir/doxygen_doc_for_boost.h
./src/include/stir/recon_buildblock/DataSymmetriesForBins.h
./src/include/stir/recon_buildblock/DataSymmetriesForBins_PET_CartesianGrid.inl
./src/include/stir/recon_buildblock/DataSymmetriesForBins_PET_CartesianGrid.h
./src/include/stir/recon_buildblock/ProjMatrixByBin.inl
./src/include/stir/recon_buildblock/DataSymmetriesForDensels.h
./src/include/stir/recon_buildblock/TrivialDataSymmetriesForBins.h
./src/include/stir/common.h
./src/include/stir/IO/ECAT962ListmodeInputFileFormat.h
./src/include/stir/IO/ECAT8_32bitListmodeInputFileFormat.h
./src/include/stir/IO/ECAT6ImageInputFileFormat.h
./src/include/stir/IO/ECAT7DynamicDiscretisedDensityInputFileFormat.h
./src/include/stir/IO/ITKImageInputFileFormat.h
./src/include/stir/IO/ECAT7ImageInputFileFormat.h
./src/include/stir/IO/InterfileImageInputFileFormat.h
./src/include/stir/IO/InputFileFormat.h
./src/include/stir/IO/ECAT966ListmodeInputFileFormat.h
./src/include/stir/IO/ROOTListmodeInputFileFormat.h
./src/include/stir/IO/read_from_file.h
./src/include/stir/is_null_ptr.h
./src/include/local/stir/recon_buildblock/DataSymmetriesForDensels_PET_CartesianGrid.inl
./src/include/local/stir/recon_buildblock/ProjMatrixByDensel.inl
./src/include/local/stir/recon_buildblock/DataSymmetriesForDensels_PET_CartesianGrid.h
./src/utilities/list_image_info.cxx
./src/utilities/stir_math.cxx
./src/iterative/OSMAPOSL/OSMAPOSLReconstruction.cxx
./src/iterative/OSSPS/OSSPSReconstruction.cxx
./src/IO/stir_ecat7.cxx
./src/IO/ECAT7DynamicDiscretisedDensityInputFileFormat.cxx
./src/IO/ITKImageInputFileFormat.cxx
./src/buildblock/ChainedDataProcessor.cxx
```

I haven't really looked into the code but `unique_ptr` sounds good to me. If files support muti-read and are not writable we may want a `shared_ptr` instead.

**Comment by KrisThielemans** [comment]
sure. we'd replace all of them. many occurences are just "local" (to make an pointer-object destruct). Replacing those is harmless of course. It's the ones in the class interface that will break backwards compatibility.

**Comment by KrisThielemans** [comment]
I've made now 2 attempts to get this to work (see 9dbc5fed3039d42731478ffdb6cb2357b0b70a86) but still fail on OSX.
The issue is that OSX supplies a broken unique_ptr (even with C++-11!). See http://stackoverflow.com/questions/31655462/no-type-named-unique-ptr-in-namespace-std-when-compiling-under-llvm-clang.
I'm trying to replace it with a boost solution, see 
https://github.com/UCL/STIR/blob/9dbc5fed3039d42731478ffdb6cb2357b0b70a86/src/include/stir/unique_ptr.h

This should have worked on Travis as its boost version is 1.61 while I require 1.57. However, it looks like it is still using the "desperate" fall-back of using a define (which I knew would fail). Can someone with a Mac investigate what's wrong with my preprocessor-ifs?

**Comment by KrisThielemans** [comment]
Anyone knows how to pass a flag to a specific compiler in Travis? We need to pass -stdlib=libc++ to clang on Apple for C++-11 (http://stackoverflow.com/questions/11853822/clang-3-1-cant-see-unique-ptr) but it won't work for Linux/gcc (presumably), and we don't want that flag when testing non-C++-11. @dvolgyes?

**Comment by dvolgyes** [comment]
I have just sent a pull request, hopefully, it will fix it.
The main point is this:
before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
EXTRA_BUILD_FLAGS="$EXTRA_BUILD_FLAGS -stdlib=libc++"; fi

It is a bit long and ugly, but as far as I know this is the idiomatic way.
Or if it fails, then similarly: CXXFLAGS="$CXXFLAGS -stdlib=libc++"
(I am not quite sure about cmake, and it takes a long time to test it,
so I had to guess, and I chose the first one. We will see soon.)

**Comment by dvolgyes** [comment]
On second thought, probably this is the wrong enviromental variable,
and CXX_FLAGS is the way.

Another way: cmake could detect OSX, and setting variables accordingly.
See here:
http://public.kitware.com/pipermail/cmake/2012-September/052049.html

**Comment by dvolgyes** [comment]
It passed the test but I don't like it anymore, because it makes
the OSX & CERN_ROOT_SUPPORT part ugly in Travis' script section.

Unfortunatelly, I travel today, so if anybody has time or idea to continue
or finish it,
then please do it.

My current best guest is this:
we should modify the cmake config to detect OSX, and append the compiler
flag there.
The Travis build could be fixed with environment variable, but this will
not fix general OSX builds.
I think it would be better to detect OSX in Cmake, and in this case, append
an  -stdlib=libc++
to the compiler flags.

**Comment by KrisThielemans** [comment]
Thanks David. I think the option to detect OSX in Cmake is best, unless anyone knows if this would create trouble on OSX in certain situations?

By the way, I don't understand why Evgueni's last update occurs in your PR #64. I was already surprised I had to do an explicit merge of the CMakeExport branch on my side (should have been a fast-forward as far as I could tell). Did I create some trouble in git?

**Comment by casperdcl** [comment]
Yes, I'll probably find time to do it tonight if no one else does first.

**Comment by casperdcl** [comment]
Yes, CMake is the way, otherwise it'll only work on travis osx and not
other people's osx machines.
