### ISSUE TITLE
Hardcoded value in construct_randoms_from_GEsingles

### ISSUE THREAD

**Issue by AnderBiguri** [UCL/STIR#630]
The following value is just there:

https://github.com/UCL/STIR/blob/c4df936a480c01441fb599ad7883a65a9566111c/src/utilities/construct_randoms_from_GEsingles.cxx#L240

To figure out:

Read it from file?
From which field?

Related to PR #601 

PD: there are other hardcoded values that are already being taken care of in the PR.

**Comment by KrisThielemans** [comment]
not sure. what's in `HeaderData/AcqParameters/EDCATParameters/coincTimingPrecision`

**Comment by AnderBiguri** [comment]
hummm nope. That is `0.0130`. In fact none of the 13 parameters inside `HeaderData/AcqParameters/EDCATParameters/` have the same numerical value ignoring exponent 10 than the value in the code (i.e. 457eX). So unless its some calculation using these values, its not there. I have not found it anywhere else in the H5 header yet (not exhaustive search yet).

**Comment by KrisThielemans** [comment]
checking some code, this might be it (using edcat parameters)
```
timingWindow=(2*posCoincidenceWindow+1) *coincTimingPrecision
```

**Comment by AnderBiguri** [comment]
@KrisThielemans yes!

`timingWindow=(2*posCoincidenceWindow+1) *coincTimingPrecision*1E9`

Perhaps `timingWindow=(posCoincidenceWindow*negCoincidenceWindow+1) *coincTimingPrecision*1E9` ?

**Comment by KrisThielemans** [comment]
> Perhaps `timingWindow=(posCoincidenceWindow*negCoincidenceWindow+1) *coincTimingPrecision*1E9` 

I don't think so (even with a plus and not a times). not sure what's in the `neg`.

**Comment by AnderBiguri** [comment]
Exactly the same value as in pos, and his is why I asked

**Comment by AnderBiguri** [comment]
@KrisThielemans please review that last commit, as I have made a method to read and compute the number, but perhaps its something that should go inside scanner or other place that I don't know about. If its good, close the issue.

**Comment by KrisThielemans** [comment]
It's great. we should be able to store this info in `Scanner`, but we don't have a field for it yet. In any case, you need to read it her like you do.
