### ISSUE TITLE
Output size of construct_randoms_from_GEsingles

### ISSUE THREAD

**Issue by AnderBiguri** [UCL/STIR#637]
When I run 

`construct_randoms_from_GEsingles /somepath/singles_test /somepath/LIST0000.BLF /somepath/templateGE.hs`

I get an output of shape:

`(1, 1981, 224, 331)`

Which is strange, I expect:

`(1, 1981, 224, 357)`

**Comment by KrisThielemans** [comment]
I haven't checked, but it looks like the difference between non-arccorrected and arc-corrected size. we want the former.

**Comment by AnderBiguri** [comment]
Ah right, so perhaps this is correct then. 
Haven't changed anything here, so if this is what is expected, good.

**Comment by KrisThielemans** [comment]
I've checked that `331` is indeed the default size after arc-correction. However, `construct_randoms_from_GEsingles` should refuse to run on such data (it has a check).

Where did you get your template from? Is it the same as in `examples/GE_Signa_PETMR`? (can just do a `diff`). Is your output projdata same size as the template? (should be the case). Can check with `list_projdata_info` for instance (I believe now also accessible in SIRF)

**Comment by AnderBiguri** [comment]
@KrisThielemans my bad, bad template. 

Question however: why is arc-corrected data smaller than non-arc-corrected data? Is it because you reject pairs at large radial distances (i.e. pairs that are very close to each other) or  does it has to be with interpolation?

If I don't understand it wrong, it should flatten the detector array, but that should not necessarily change the number of LORs, right?
