### ISSUE TITLE
optimise ProjDataInMemory::get_bin_value()

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#638]
Currently, `ProjDataInMemory::get_bin_value()` is terribly slow. It should be a lot faster if we just remove it, or explicitly reimplement it in terms of `ProjDataFromStream` as suggested previously https://github.com/UCL/STIR/issues/462#issue-586411241 but it seems we didn't do that yet.

Even better would be to use something like this
```C++
{
// first find offset in the stream
    vector<streamoff> offsets = get_offsets_bin(this_bin);
    const streamoff total_offset = offsets[0];
// now convert to index in the buffer
    const int index = static_cast<int>(offsets[0]/sizeof(float));
   return buffer[index];
}

Clearly, the same would apply for `set_bin_value`.

**Comment by KrisThielemans** [comment]
@AnderBiguri could you do `get_bin_value() on `release_4`? We can then do `set_bin_value` on `master`.

**Comment by AnderBiguri** [comment]
`ProjDataFromStream::get_offsets_bin` is private method of `ProjDataFromStream` so I went with the solution in #462 because it works fast (the Bin normalization code increases from 3s to 50s using this data, but with the prior code it was 3000s. seems reasonably fast).
