### ISSUE TITLE
GE Signa template is wrong

### ISSUE THREAD

**Issue by AnderBiguri** [UCL/STIR#641]
Current template in #601 is wrong. 

Needs fixing/testing.

**Comment by KrisThielemans** [comment]
I probably generated this with an old version of the code. Just recreate using the new one.

**Comment by KrisThielemans** [comment]
By the way, I find it a bit weird to create an issue for a problem in a PR. Admittedly, github doesn't seem to have a nice way to track things that need to be finished in a PR. If anyone knows one, that'd be great.

**Comment by AnderBiguri** [comment]
Ah, maybe I could have added it simply as a task in the project... Just needed a way to keep track of things

**Comment by KrisThielemans** [comment]
yeah. you can use [task lists](https://github.blog/2014-04-28-task-lists-in-all-markdown-documents/) in a PR, but after too many comments, you're never sure where the relevant is going to end up (except if you put it right at the top).
