### ISSUE TITLE
SAFIR code assumes long is 64-bit

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#66]
When compiling STIR with Visual Studio with 32-bit tools I get

```
C:\Users\\krisf\Documents\devel\STIR\src\include\stir/listmode/CListRecordSAFIR.h(156): error C2034: 'stir::CListTimeDataSAFIR::time': type of bit field too small for number of bits
C:\Users\krisf\Documents\devel\STIR\src\include\stir/listmode/CListRecordSAFIR.h(146): warning C4293: '<<': shift count negative or too big, undefined behavior
```
Both of these are severe problems, not Windows specific. @jafische, can you look at this?

**Comment by jafische** [comment]
Sorry about that. I agree it's serious. I have created a pull request with a suggested fix.

**Comment by KrisThielemans** [comment]
possibly fixed by commit 80dce30. It now compiles ok in VS2015 and the BOOST_STATIC_ASSERT on sizes are ok. 

I wonder if it wouldn't be best to use boost::uint64_t for the 'normal events', although in C++ this might not be necessary.

**Comment by jafische** [comment]
This is also an option. I guess it does not harm to use the uint64_t, but I believe the normal events are safe because of the 16 bit minumum length of unsigned int

**Comment by dvolgyes** [comment]
Choosing type is always a tradeoff between many factors.
However, enforcing the choice:
- cmake
- boost::numeric_limits + boost::static_assert

Boost own types are slow (multiprecision) or just an alias for standard C++
types.

I like static assert, but cmake could be an earlier solution (configuration
time).
Obviously, they also could be combined.

For travis: Cmake is faster (gives feedback sooner), boost is more portable.

Best,
   David

**Comment by KrisThielemans** [comment]
Was fixed so closing.
