### ISSUE TITLE
Add example of how to use JSON files for ctac_to_mu_values

### ISSUE THREAD

**Issue by AnderBiguri** [UCL/STIR#660]
`ctac_to_mu_values` has no docs, which makes it hard to use. 

Add either an example `.json` file or some docs to explain how it works.

**Comment by AnderBiguri** [comment]
Hum, I am not sure I am following with what you want here done. 

> But the first thing to do before writing documentation is figuring out how it works 

`ctac_to_mu_values` will print:

```
ctac_to_mu_values -o output_filename -i input_volume -j slope_filename -m manufacturer_name [-v kilovoltage_peak] -k target_photon_energy
Default value for tube voltage is 120 kV.
```

Which is the only docs I could get. Should be enough to execute it, as long as there is some example script of what are the files required. Mostly the JSON I guess. 

The relevant lines that you mentioned simply do a "bilinear" interpolation (weird name, this its used for 2D linear, rather than 1D-2 lines) on the input data. Noticeable is that I have seen that its common to have more than 2 lines for CTAC images, but this code only supports 2.

----

> So for PET, we'd need similar entries with keV 511 with  ....

I am not sure I follow. Surely the CT image is not at 511 KeV, so what am I missing?

**Comment by KrisThielemans** [comment]
STIR doc is in a few parts:
1. Latex files in `documentation`
2. doxygen doc via the source (See for instance the [entry for all utilities that have some doxygen](http://stir.sourceforge.net/documentation/doxy/html/group__utilities.html)
3. usage message of any utilities
4. example parameter files/headers etc
5. the source itself if all else fails (which is often enough)

For utilities like this, I guess the usage message is ok, there is a file but we couldn't find it. So I suggest we add to 1 and 2, and address 4 by moving the file, now that we have some idea how this works (which I didn't really before).

>  "bilinear" interpolation (weird name)

correct. it should be "piece-wise linear".

It wouldn't be hard to extend it to more than 2 pieces, but life is short. Let's not do it if we don't need it.




> > So for PET, we'd need similar entries with keV 511 with  ....
> 
> I am not sure I follow. Surely the CT image is not at 511 KeV, so what am I missing?

CT energy is specified as kVp, the gamma photon energy is another variable. It's the latter I'm referring to. The current ct_slopes.json contains values for some single photon emitters, but not PET.

**Comment by danieldeidda** [comment]
Hi,
I have used this for PET as well I can post here how I run it I modified the json file to add the 511keV energy

**Comment by AnderBiguri** [comment]
> Hi,
> I have used this for PET as well I can post here how I run it I modified the json file to add the 511keV energy

Sure sounds good! 
I ended up writing my own code, but definitely useful to have more info to be able to help others in the future.

**Comment by danieldeidda** [comment]
so this is how I run it:
ctac_to_mu_values -o umap0.hv -i CT.* -j ct_slopes.json -m mediso -k 511

it doesn't let me upload the file but this is what I added at the end for PET:

```
{
        "kvp": 120,
        "kev": 511,
        "a1": 0.096,
        "b1": 9.6e-5,
        "a2": 0.096,
        "b2": 5.73e-5,
        "break": 0
      }
```
also from my experience it seems the utility is quite sensitive to the energy number for example 99Tc should be 140.5 keV but since the file has 140 keV it will only accept the latter. 
This needs some error or warning to be throw

**Comment by AnderBiguri** [comment]
> also from my experience it seems the utility is quite sensitive to the energy number for example 99Tc should be 140.5 keV but since the file has 140 keV it will only accept the latter.

Yup, it just parses that input into an `int` and then exactly matches the value in the JSON file:

https://github.com/UCL/STIR/blob/85cc1940c297b1749cf44a9fba937d7cefdccd47/src/utilities/ctac_to_mu_values.cxx#L89

**Comment by KrisThielemans** [comment]
Possibly JSON doesn't allow floats?

**Comment by AnderBiguri** [comment]
@KrisThielemans it's just a string, isn't it? If you read just the few lines avobe the line I posted it just grabs from osstream and puts it on an int.

**Comment by AnderBiguri** [comment]
@KrisThielemans no, JSON and nlohman both support floats. The script simply doesnt.

**Comment by KrisThielemans** [comment]
we could just `round` all the time, not just the input parameter, but also those found in the JSON file.

**Comment by AnderBiguri** [comment]
Definetly we can... But also many other things, like add support for arbitrary piecewise linear segments etc. I'd say as long as everything is well documented on how it works... Ideally we'd document this and then if we decide to add more functionality to it, we'd also document it then!

**Comment by KrisThielemans** [comment]
> > "bilinear" interpolation (weird name)
> 
> correct. it should be "piece-wise linear".

It's actually used by others in the internet. As "piecewise-linear" doesn't convey there's only 2 pieces, I've left it for now.
