### ISSUE TITLE
GE RDF9 listmode support does not handle records that are not of size 6

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#679]
GE RDF9 listmode records can be of size 6 (normal),8 (coincidence + energy), or 16 (calibration) bytes, as indicated by 2 bit-fields. However, if the size is larger than 6, we never read the remaining bytes.

https://github.com/UCL/STIR/blob/ab0fc96d39ec3cdcea72906bbbdf02ae59b975f0/src/include/stir/IO/InputStreamWithRecordsFromHDF5.inl#L103-L110

Aside from not initialising the data properly, it should also lead to remaining events being corrupted (as the next call to [read_list_data](https://github.com/UCL/STIR/blob/ab0fc96d39ec3cdcea72906bbbdf02ae59b975f0/src/IO/GEHDF5Wrapper.cxx#L677) will just read 6 bytes again.

It appears therefore that these events don't occur in "regular" listmode files, but we need to fix the code.

**Comment by KrisThielemans** [comment]
This also needs fixing
https://github.com/UCL/STIR/blob/ab0fc96d39ec3cdcea72906bbbdf02ae59b975f0/src/include/stir/listmode/CListRecordGEHDF5.h#L290-L296

**Comment by KrisThielemans** [comment]
and https://github.com/UCL/STIR/blob/ab0fc96d39ec3cdcea72906bbbdf02ae59b975f0/src/include/stir/listmode/CListRecordGEHDF5.h#L298

**Comment by AnderBiguri** [comment]
Ah the horror of the ever increasing RDF9 problems! :D 

This is getting a bit out of hand for me, please let me know when you stop having a look at it and maybe we can share some ideas.

**Comment by KrisThielemans** [comment]
closed in #601
