### ISSUE TITLE
STIR ignores orientation when reading/converting images from other file formats

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#69]
Many file formats have orientation info. When reading these (via ITK), STIR ignores this completely. This can create trouble when reading DICOM images for instance (e.g. for MRAC conversion)

**Comment by KrisThielemans** [comment]
@ashgillman @rijobro I think this was resolved? If so, could you add a note when, and close this one?

**Comment by ashgillman** [comment]
I believe this is solved with #257

**Comment by ashgillman** [comment]
Specifically:
https://github.com/ashgillman/STIR/blame/ab735eb11053208b750da6092e8ec3ce9c4e70a7/src/IO/ITKImageInputFileFormat.cxx#L240
