### ISSUE TITLE
RDF9 correct_projdata segfaults. 

### ISSUE THREAD

**Issue by AnderBiguri** [UCL/STIR#692]
This happens when one uses `correct_projdata` with `From GE HDF5` as bin normalization. 

In particular in the following function call

https://github.com/UCL/STIR/blob/7b4c27470ad175a80f29e9aabe945b6831a4f159/src/recon_buildblock/BinNormalisationFromGEHDF5.cxx#L453-L473

as `proj_data_info_cyl_ptr` is a null pointer, which should not be. 

Commit d9ca96ec746f5504e16f4712afbf1ff41cb96dd2 did not have this issue, yet I can't see any modification in anything related.... I tried reverting the `ProjDataGEHDF5.cxx` changes, but did not fix the issue. 

I also do not understand why `set_up` is not being called, where in theory this pointer would be set. 

https://github.com/UCL/STIR/blob/7b4c27470ad175a80f29e9aabe945b6831a4f159/src/recon_buildblock/BinNormalisationFromGEHDF5.cxx#L259-L264

My advanced debugging technique of printing to command line shows that this function is not being called... Nor now neither when the error was not there. So I dont understand why its not being called, but I dont understand why before it worked while still not being called.

**Comment by KrisThielemans** [comment]
I've checked this again on one of the STFC machines. This was with `release_4` branch. All was well. I suspect you have a local problem.

By the way, I ran this with a "SuperBuild-STIR", so just set
```sh
export pardir=~/devel/build/sources/STIR/examples/GE-Signa-PETMR/
```
That worked alright as well.

**Comment by AnderBiguri** [comment]
@KrisThielemans well.... thats strange. I was definetly changing commits, adding and removing code (including prints) and could see the changes, so its weird that its a local issue. 

For the DMI data, can you give me EXACTLY the file you use to test, so I can go and run that without modifications (aside from setting pardir) to see what could be wrong?

**Comment by AnderBiguri** [comment]
Is it this one (its the one I've been using)?
 https://github.com/UCL/STIR/pull/601#issuecomment-693038760

**Comment by KrisThielemans** [comment]
yes, that's what I do. I removed `output` and `extras`, and started from the top.

**Comment by AnderBiguri** [comment]
I can not reproduce this anymore.... I suspect a broken norm file.
