### ISSUE TITLE
Wierd order of 3d values in python

### ISSUE THREAD

**Issue by adler-j** [UCL/STIR#7]
When creating a `FloatVoxelsOnCartesianGrid` with [this](https://github.com/odlgroup/odl/blob/67087d232b238a0a4dbee0e8ad03b631faaf4fbc/examples/tomo/data/stir/initial.hv) input file, we get

```python
>>> volume = stir.FloatVoxelsOnCartesianGrid.read_from_file('initial.hv')
>>> volume.shape()
(15, 64, 64)
```

But the file says that the shape should be `x = 64`, `y = 64`, `z = 15`.

Some testing shows that almost all STIR methods give the results in [z, y, x] order. Is this intended?

**Comment by KrisThielemans** [comment]
hi. yes this is intended and is described in the developer's guide. It's a bit unfortunate of course. The reason for it is that our nD arrays are implemented recursively such that volume[z][y][x] works, and we made it equivalent to volume[(z,y,x)]. It's probably an unfortunate design decision though.

we do the same for physical coordinates. there it is less unfortunate as people shouldn't really rely on a specific orientation w.r.t. the patient anyway (although we have no info on that orientation in STIR currently)

**Comment by adler-j** [comment]
Ok, thank you for a quick answer! I'll get this implemented on our side then.
