### ISSUE TITLE
Does reusing time-frame info from previous outputs make sense in indirect Patlak modelling?

### ISSUE THREAD

**Issue by AnderBiguri** [UCL/STIR#700]
When calling `apply_patlak_to_images`

the code does the following:

https://github.com/UCL/STIR/blob/7b4c27470ad175a80f29e9aabe945b6831a4f159/src/modelling_utilities/apply_patlak_to_images.cxx#L86-L105

i.e. it uses an existing file as a template, then will write over it. 

I can only see 2 possible cases where the code for the template is used

1. You are using the same data as before, or similar, and then use the output file as template. But this is unnecesary, as we can create it without the template
2. You are using different dataframes than before, and thus your output will have bad info, because you are using it as template, instead of writting the new one, which you can do. 

So, I only see this piece of code as a "trap". Either doesn't do anything bad but its useless, or does something bad/unexpected, but also by not really adding anything at all, because removing the code would have avoided the unexpected behaviour and result in a good output file. 

Any reason to keep it?

**Comment by KrisThielemans** [comment]
agreed. best to cut it. (it used to be there because we were updating an ECAT7 file)
