### ISSUE TITLE
BasedCoordinate, 1-based indexing

### ISSUE THREAD

**Issue by AnderBiguri** [UCL/STIR#701]
More of a question rather than an issue:

Is there any reason, aside from "this is hard to remove at this point in time" to have a 1-based indexing class that is essentially an `std::array` with templated sizes? I am mostly concerned by the 1-based indexing, as it creates code that, well, makes no sense in C++, and just helps confuse unless you know the class.

e.g.

```
BasedCoordinate<2,int> min_range;
min_range[1]=0; min_range[2]=10;   //???????
```

I see there is mention of this in #686 too. If I am to write code, should I just avoid these classes as much as possible?

**Comment by KrisThielemans** [comment]
yeah well. Choices made. Someone (probably me) at some point thought that many people would find at more natural that "the first coordinate" would be `a[1]`, and "the first frame" at `get_time_frame(1)`

Was it a bad idea? Sure. It's even worse in the Python interface I think. (it didn't feel so bad at the time as `VectorWithOffset` and `Array` allow you to specify the offset already anyway, so you cannot count on the fact that 0 is the first element).

Can we change it (without breaking things)? I seriously doubt it. This is going to be in many many places.

Can we avoid these classes? No. There are no alternatives. In fact, creating alternatives would make the situation only worse. Although arguably `BasicCoordinate` is obsolete now that we've switched to C++11, and could/should be using `std::array`. So, we could try to whole-sale replaces this, but it's a horrible project.

It would obviously help if we'd document this with a list of the classes/methods where this convention is used. #686 might have them all.

**Comment by AnderBiguri** [comment]
@KrisThielemans sure, I assumed it came from back in the past, and indeed I wasn't even considering removing them, as they are everywhere and it's not a trivial change!

However, I guess my question was more in the lines of "should I consider this deprecated and just avoid them from now on if I can?"

**Comment by KrisThielemans** [comment]
I can't see how you can avoid them. Maybe you could give an example

**Comment by AnderBiguri** [comment]
well, in case I were to write some more code for patlak, for example (or, as an arbitary example, for Logan), just use 0 based indexing for those `Array` classes.

**Comment by KrisThielemans** [comment]
let's talk about it then... I certainly agree that the 1-based indexing for the model-matrix was a bad idea. That might be fixable (but let's only do it if we really need to)

**Comment by robbietuk** [comment]
Was there a resolution to this?

**Comment by AnderBiguri** [comment]
@robbietuk Dont use it in the future, and "if aint broken, dont fix it" for whats its there now.
