### ISSUE TITLE
Tidy up Patlak code

### ISSUE THREAD

**Issue by AnderBiguri** [UCL/STIR#702]
Just opening an issue to keep track of all the things that need tidy up in the Patlak code (will make a PR for this, testing codes now).

- [ ] ~~Indentation all over the place (pending, maybe not fix)~~ . Not here, #98 
- [x] Add more comments
- [x] `PlasmaData::get_if_decay_corrected()` -> `PlasmaData::get_is_decay_corrected()` and other typos
- [x] Unnecessary second if (unnecessary error maybe?)
https://github.com/UCL/STIR/blob/7b4c27470ad175a80f29e9aabe945b6831a4f159/src/modelling_buildblock/PatlakPlot.cxx#L178-L181
- [ ] ~~Remove unnecessary extra code just to make sure one can index 1-based (will this have impact in direct recon? it should not)~~ Don't fix. 
      https://github.com/UCL/STIR/blob/7b4c27470ad175a80f29e9aabe945b6831a4f159/src/modelling_buildblock/PatlakPlot.cxx#L145-L150
 - [x] `brain_patlak_model_array` not just brain

**Comment by KrisThielemans** [comment]
Indentation is a very old sore, #98. We've never taken the plunge due to different editors etc. I'd really don't want to do a whole-sale indentation change of the Patlak code now with someone's settings, and then redo it all again later. Maybe now is the time to close #98...

**Comment by AnderBiguri** [comment]
@KrisThielemans hum I think I don't get the problem, likely because I don't use emacs and other stuff, but all editors I ever used can handle white space and tabs (otherwise python would break hehe). The issues I can see with indentation are not just that something is wider or not, but there are literally less characters in places there should be more, or just different levels, such as:

https://github.com/UCL/STIR/blob/7b4c27470ad175a80f29e9aabe945b6831a4f159/src/modelling_buildblock/PatlakPlot.cxx#L263-L278

I can see in my local editor the same indentation and formats as in Github, should that not be the one that we need to target as clean reference? 

This is indeed more of a discussion for #98, but the current indentation does indeed make it 100% harder to work with STIR code, just adding another layer to the obfuscation. 

In any case, the rest of the checkboxes still apply, will tackle those first.

**Comment by KrisThielemans** [comment]
there's many issues on indentation, one simple one is if it looks the same everywhere (as soon as you have tabs, it doesn't). the next one if it's consistent (and what you call consistent), and the next is how you enforce it.

I 100% agree that a lot of STIR files have an indentation mess!

**Comment by KrisThielemans** [comment]
> Unnecessary second if (unnecessary error maybe?)

I cannot recall right now, but in the code review that I sent you, I found that it only worked under certain circumstances. I believe this `if` guards against people trying something else (even though it looks unnecessary there). But that might be another `if`...

**Comment by KrisThielemans** [comment]
> there are literally less characters in places there should be more, or just different levels, such as:

funnily/strangely enough, the code in the quote that give above looks perfectly fine to me... (it would be clearer if `{}` would be used for the second `for`)

**Comment by AnderBiguri** [comment]
@KrisThielemans I copied the wrong chunk hehehe. Too late today... Sorry about that

**Comment by KrisThielemans** [comment]
😄

**Comment by KrisThielemans** [comment]
decay correction is discussed in #685
