### ISSUE TITLE
add_multiplication_with_approximate_Hessian - Issues

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#718]
`add_multiplication_with_approximate_Hessian` is a slightly confusing method.

Poisson log-likelihood
-----
The method computes `A'((1/y)A(input))`, where `A`and `A'` are the forward and backward projection operations, `input`  could be a vector of 1s and `y` the measured data
https://github.com/UCL/STIR/blob/997f672f69749466f296feb4f322fefcd2b834b8/src/recon_buildblock/PoissonLogLikelihoodWithLinearModelForMeanAndProjData.cxx#L809-L893

This is a method that saves on computation by not computing the true hessian, but an approximation, at `current_estimate` `A' ((y/ybar^2) A(input))`, where `ybar` is the forward projected  `current_estimate`. This is therefore the reason for `approximate` in `add_multiplication_with_approximate_Hessian`. Therefore the arguments for this function are `output, input` and it does not require `current_estimate`.

Priors
------
The prior functions are slightly different however as they are not computationally costly to compute. Additionally, up until recently the QP is the only prior with an implementation of `add_multiplication_with_approximate_Hessian` and the Hessian of the QP is 1, and independent of the `current_estimate`. Therefore the implementation works as expected. https://github.com/UCL/STIR/blob/997f672f69749466f296feb4f322fefcd2b834b8/src/recon_buildblock/QuadraticPrior.cxx#L586-L658

However, in general, the prior input arguments for this method in https://github.com/UCL/STIR/blob/997f672f69749466f296feb4f322fefcd2b834b8/src/recon_buildblock/GeneralisedPrior.cxx#L62-L71
are not sufficient as the Hessian of a prior may not be independent of the `current_estimate`, e.g. logcosh https://github.com/UCL/STIR/pull/716

______
Proposed Resolution
-----
- Addition of another method `accumulate_Hessian_times_input` that takes 3 arguments (`output, current_estimate, input`) and computes the second derivative at `current_estimate` and multiplies by `input`. This would need to be done for both Poisson log-likelihood and priors with surrogate methods, i.e. QP and logcosh.

----- 
EDIT:
This issue has been expanded to cover all aspects of `add_multiplication_with_approximate_Hessian` which include likelihood classes and priors.

- [x] Addition of Likelihood method `accumulate_Hessian_times_input` #733

- [x] Additon of Prior method `accumulate_Hessian_times_input` #719

It was discussed in #719 to use `accumulate_` terminolgoy rather than `add_` for methods that add/accumulate on the output. Therefore:

- [ ] `add_subset_sensivity` method should be renamed `accumulate_subset_sensitivity`

- [ ] At the next major release, rename `add_multiplication_with_approximate_Hessian` to `accumulate_multiplication_with_approximate_Hessian`

**Comment by KrisThielemans** [comment]
I've corrected the initial math, removed the assumption that `input` is `current_estimate` (as it isn't) and removed some spelling mistakes :-)

**Comment by KrisThielemans** [comment]
After some more thought, I think that the difficulty is that the concept of the "approximate Hessian" will only work for data-fit term (e.g. least squares or Poisson), where we can find a reasonable estimate of the Hessian for images "close" to the solution, without knowing what that solution is (for Poisson, by replacing `y/ybar^2` with `1/y`). This doesn't work for priors generally.

As noted in https://github.com/UCL/STIR/pull/719#discussion_r506630828, it might be better to drop the function that assumes we can compute an "approximate Hessian" for the whole objective function that satisfies this property. Alternatively, we leave it in, but let it call `error` for every prior where it doesn't make sense (possibly everything except the quadratic prior (or no prior)). That'd be backwards compatible, but we then should add documentation that this function is likely to be useless in most cases.

**Comment by robbietuk** [comment]
> "approximate Hessian" will only work for data-fit term

I agree with this. Therefore any functionality of the priors computing `accumulate_Hessian_times_input()` (real Hessian) cannot be used in `add_multiplication_with_approximate_Hessian()` methods.

>Alternatively, we leave it in, but let it call error for every prior where it doesn't make sense

This will therefore work. Below is a table detailing the possiblities of calling the objective function's current and proposed Hessian multiplication methods:

|                        | Data-fit term | Quadratic Prior  | Log-cosh Prior |
| ------------- | ------------- | ------------- | ------------- |
| `add_multiplication_with_approximate_Hessian()`  |  y  | y | n (error?) |
| `accumulate_Hessian_times_input()`  | y (but expensive)  | y | y |

The question is, how do we then handle the objective function call of `accumulate_Hessian_times_input()`. This will work for all priors but is undesirable for the data-fit term. 

Alternatively we could use a combination of both (which is what I started doing in https://github.com/UCL/STIR/pull/719#discussion_r506568531):
 - `Datafit_sptr->add_multiplication_with_approximate_Hessian(output, input)`
 -  `Proir_sptr->accumulate_Hessian_times_input(output, current_image_estimate, input)`

But then what do we name this combination?

**Comment by robbietuk** [comment]
I think this got closed automatically with the merge of #719 and I dont seem to be able to reopen it. This issue is appicable to more incoming PR's

**Comment by KrisThielemans** [comment]
interesting. it looks like `addresses` is also a "closing keyword". didn't know that! (I carefully used a word that wouldn't close it 😩 )

**Comment by robbietuk** [comment]
Closing because specific issues have been created for remaining points.
