### ISSUE TITLE
need to have a way to flag deprecated code

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#732]
we currently flag it (if at all) in doxygen. Would be best to do it in C++ as well, see [here](for some hints), or even SWIG (no clue how to do that). 

In addition, ideally we would clearly indicate at which release we're going to do that, but that might be beyond our capabilities in keeping track of things.

**Comment by AnderBiguri** [comment]
@KrisThielemans link in the comment is not there!

**Comment by KrisThielemans** [comment]
oops. https://stackoverflow.com/questions/295120/c-mark-as-deprecated#:~:text=In%20C%2B%2B14%2C%20you%20can%20mark%20a%20function%20as,For%20example%2C%20the%20following%20function%20foo%20is%20deprecated%3A
