### ISSUE TITLE
doxy2swig unicode encoding error during compilation

### ISSUE THREAD

**Issue by szho42** [UCL/STIR#734]
try to compile with Python interface enabled.
The native C++ code compiled with not issues.
However, there is an unicode encoding error when converting doxygen to xml. 

---

parsing file: /workspace/STIR-bin/Release/xml/dir_43bdf3cad22e53c8329992cdc5085372.xml
parsing file: /workspace/STIR-bin/Release/xml/indexpage.xml
Traceback (most recent call last):
  File "/workspace/STIR/external_helpers/doxy2swig/doxy2swig.py", line 838, in <module>
    main()
  File "/workspace/STIR/external_helpers/doxy2swig/doxy2swig.py", line 835, in main
    p.write(args[1])
  File "/workspace/STIR/external_helpers/doxy2swig/doxy2swig.py", line 167, in write
    o.write(''.join(self.pieces))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 705622: ordinal not in range(128)
make[2]: *** [src/swig/CMakeFiles/RUN_DOXY2SWIG.dir/build.make:80: src/swig/STIR_DOXY2SWIG.i] Error 1
make[2]: *** Deleting file 'src/swig/STIR_DOXY2SWIG.i'
make[1]: *** [CMakeFiles/Makefile2:7007: src/swig/CMakeFiles/RUN_DOXY2SWIG.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

**Comment by szho42** [comment]
It seems that the cmake found python2, instead of python 3 in my case, as there are multiple python interperators installed.
Change the cmake configuration (explict using python3 and the correponding python lib and python include) resolve this unicode issue.

**Comment by szho42** [comment]
However, there is another error regarding SWIG.

Anyone experienced the same issue?

---

[100%] Building CXX object src/swig/CMakeFiles/_stir.dir/__/Shape_buildblock/Shape_buildblock_registries.cxx.o
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx: In function 'PyObject* _wrap_ExamInfo_get_time_frame_definitions(PyObject*, PyObject*)':
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx:60719:1: warning: label 'fail' defined but not used [-Wunused-label]
 fail:
 ^~~~
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx: In function 'PyObject* _wrap_IterativeReconstruction3DFloat_get_inter_iteration_filter(PyObject*, PyObject*)':
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx:102379:1: warning: label 'fail' defined but not used [-Wunused-label]
 fail:
 ^~~~
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx: In function 'PyObject* _wrap_OSMAPOSLReconstruction3DFloat_get_parameters(PyObject*, PyObject*)':
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx:103852:1: warning: label 'fail' defined but not used [-Wunused-label]
 fail:
 ^~~~
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx: In function 'PyObject* _wrap_OSSPSReconstruction3DFloat_get_parameters(PyObject*, PyObject*)':
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx:104657:1: warning: label 'fail' defined but not used [-Wunused-label]
 fail:
 ^~~~
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx: In function 'void SWIG_Python_addvarlink(PyObject*, char*, PyObject* (*)(), int (*)(PyObject*))':
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx:146872:16: warning: 'char* strncpy(char*, const char*, size_t)' specified bound depends on the length of the source argument [-Wstringop-overflow=]
         strncpy(gv->name,name,size);
         ~~~~~~~^~~~~~~~~~~~~~~~~~~~
/workspace/STIR-bin/Release/src/swig/CMakeFiles/_stir.dir/stirPYTHON_wrap.cxx:146869:27: note: length computed here
       size_t size = strlen(name)+1;
                     ~~~~~~^~~~~~
make[1]: *** [CMakeFiles/Makefile2:6980: src/swig/CMakeFiles/_stir.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

**Comment by szho42** [comment]
install the latest SWIG version resolve this issue.
error occurs for swig 3.x.x version
works fine for swig 4.x.x version

**Comment by KrisThielemans** [comment]
Could you say which STIR version you're compiling? I recently removed some erroneous strange characters in comments from some files (sorry, can't find the commit at the moment).

If 'master', then maybe you try and find where it is by looking at the generated XML file (`dir_43bdf3cad22e53c8329992cdc5085372.xml` in the example above) and check the line.

For your [second problem](https://github.com/UCL/STIR/issues/734#issuecomment-720263265) I don't see any error there, only warnings (about things that STIR has no control over). Any error must have been higher up.

**Comment by szho42** [comment]
I was using the 'master' branch.
In my case, the 1st issue can be resolved by using Python 3.x when compiling.
And the 2nd issue can be resolved by using the latest version SWIG (version 4.0.x).

Thanks for your reply.

**Comment by KrisThielemans** [comment]
I believe I have caught all these recently. I'll therefore close this.
