### ISSUE TITLE
load sinogram data (converted from pet-rd-tools) in python binding

### ISSUE THREAD

**Issue by szho42** [UCL/STIR#739]
We are currently testing PET recon in STIR with unconstrcuted data (Siemens format, in .dcm header and .bf binary data pair).

The steps are:
1. convert the sinogram and normalization data from Siemens to interfile format using PET-RD-TOOLS
2. futher convert the file to STIR interfile with convertSiemensInterfileToSTIR.sh in STIR/script/IO/, which will convert the xxx.s.hdr to xxx.hv accordingly
3. try to load the file (xxx.hv) in STIR with python binding

`image = stirextra.to_numpy(stir.FloatVoxelsOnCartesianGrid.read_from_file(sinogram_file));`

However, there are some errors in parsing the header.

`RuntimeError: KeyParser: the list corresponding to the keyword "data offset in bytes" has to be resized to size 2. This means you have a problem in the keyword values.`

check with the xxx.hv header file,

> data offset in bytes [1]:=24504

> data offset in bytes [2]:=69603806

The size of the keyword in the header file is already 2.

Any thoughts would be helpful.
Cheers

**Comment by KrisThielemans** [comment]
I'm confused by this. The title says sinograms, but the example you give is an image. To clarify:
- you should not run `convertSiemensInterfileToSTIR.sh` on sinograms ("projection data" in STIR terminology), nor listmode data
- for the MRAC image Interfile header, we do need to, but it doesn't work yet. See https://github.com/UCL/STIR/issues/196. (Note: you could use `nm_mrac2mu` (although there are still some problems there sadly), so we currently use STIR to read the DICOM image and do the multiplication by hand, followed by registration. We have no automatic workflow for the hardware mu-maps yet.]

Assuming that you do want to read a sinogram, please use `stir.ProjData(filename)`.

**Comment by szho42** [comment]
thanks, Kris, for the explanation.We got wrong about the usage of the convertSiemensInterfileToSTIR.sh

Just wondering what is the common steps your team use to reconstruction MRAC-based PET image using STIR?

**Comment by KrisThielemans** [comment]
> Just wondering what is the common steps your team use to reconstruct MRAC-based PET image (list-mode data from Siemens mMR scanners) using STIR?

attempting to make a list at #755 (but pressed for time)
