### ISSUE TITLE
get/set_bin_value

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#753]
- `get_bin_value` in `ProjDataFromStream` should be virtual such that it can be overriden by the existing version in `ProjDataInMemory` (which is faster)
- `set_bin_value` in `ProjDataFromStream` should be virtual and should be overloaded by `ProjDataInMemory`

**Comment by KrisThielemans** [comment]
#782 did not yet add `ProjDataInMemory::set_bin_value`, so reopening.

**Comment by danieldeidda** [comment]
> 
> 
> #782 did not yet add `ProjDataInMemory::set_bin_value`, so reopening.

do we want this to be pure virtual?

**Comment by KrisThielemans** [comment]
closed with #784
