### ISSUE TITLE
Logcosh value evaluation returns inf with larger values

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#768]
Interesting one, this time with exponentials.
The logcosh value evaluation 
https://github.com/UCL/STIR/blob/10e5fd409d62ac21fa9453ecf6238ac3748544b6/src/recon_buildblock/LogcoshPrior.cxx#L292-L295
will return `inf` when `voxel_diff > 90.3167` (approx.) because of the evalution of `cosh(voxel_diff) ~=8.3e+38`. This is above the `float` max value of 2.7e+34.

Obviously this computation could be performed in `double` but will only allow evaluation up to `voxel_diff ~=  700`, no great improvement.

I think the function evaluation need to be split. The trigonometric identifier:`cosh(x) = ( e^x + e^(-x) )/ 2` gives one method. At `|x|>30` the impact of the e^(-|x|) is so minimal. Apply the logarithm `log[(1/2) * e^|x|] = log(1/2) + |x|` and the impact of missing term is mininal. 

Shall write a new function in the header for this, something like:
```
elemT voxel_diff = fabs(current_image_estimate[z][y][x] - current_image_estimate[z+dz][y+dy][x+dx]);
elemT loghalf = log(1/2);  // Define this much earlier in the method outside of for loops
if ( voxel_diff < 30){
   elemT current = weights[dz][dy][dx] * 
         (1/(this->scalar*this->scalar))*log(cosh(this->scalar*voxel_diff));
} else {
   elemT current = weights[dz][dy][dx] * 
         (1/(this->scalar*this->scalar)) * ( this->scalar*voxel_diff + loghalf ) ;
}
```
and add a little documentation explaining this rational.

**Comment by zeljkozeljko** [comment]
If need be one can be (needlessly) more accurate regarding the rewriting, ie since
<img width="375" alt="Screenshot 2020-12-10 at 01 49 40" src="https://user-images.githubusercontent.com/25665703/101710863-4015cb00-3a8a-11eb-9e5c-c041696faf39.png">
