### ISSUE TITLE
Constantly running into "not supporting shifted X/Y origin" error when attempting to forward project

### ISSUE THREAD

**Issue by Judge24601** [UCL/STIR#772]
Hello,

I've been attempting to use STIR for forward projection for some time, but consistently run into "ProjMatrixByBinUsingRayTracing sadly doesn't support shifted x/y origin yet" when using any of my data, rather than data that's from the STIR-exercises repo.  For some reason, any matrix size[1] or [2] set in the interfile will produce this error, unless it matches the size of the example images (211 x 211 ) or one less, (210 x 210). I'm not clear on why this occurs, and it happens regardless of the actual size of the image. Modifying the offset values for x and y has no effect.
I've also tried scaling my data so it's 211 x 211, but that results in a sinogram that is a constant value throughout, which does not make sense either.

Are there some steps that need to be followed for forward projection to prepare the data? I've gone through the user manual and wiki, and haven't found anything.

**Comment by KrisThielemans** [comment]
I think we'll need more information on what steps you are exactly following.

The offset is determined from Interfile keywords (or other things when reading Nifti files etc). It doesn't have anything to do with number of voxels.
