### ISSUE TITLE
Energy resolution units for sinogram header

### ISSUE THREAD

**Issue by emikhaylova** [UCL/STIR#778]
When using "create_projdata_template", one of the questions is:
Enter the energy resolution of the scanner : [0,1000 D:-1]:
What are these units?

**Comment by KrisThielemans** [comment]
From the following, it follows that `Scanner::energy_resolution` is expressed as a fraction (and computed at the reference energy), so should be between 0 and 1.
https://github.com/UCL/STIR/blob/e0e40a90935b21b9cff3e51ff71ddd5dc30f8bf1/src/scatter_buildblock/scatter_detection_modelling.cxx#L117-L118

This isn't documented, and in some places the doc seems actually wrong. PR in construction.

**Comment by KrisThielemans** [comment]
fixed by #1149
