### ISSUE TITLE
keyword parsing in .hroot files

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#79]
`CListModeDataROOT`  initialises the scanner's `num_rings` and `num_detectors_per_ring` from the module et al keywords (read by `InputStreamFromROOTFileForCylindricalPET` et al.), but it initialises the max_ring_difference  and num_views parameters for its `ProjDataInfoCylindricalNoArcCorr` object from independent `num_rings` and `num_detectors_per_ring` members (parsed from the corresponding keywords in the .hroot).

This seems very dangerous to me. I think we should remove the explicit keywords from the .hroot file.

@NikEfth, I think this is a left-over from the (currently disabled) code to do axial compression and view-mashing directly when reading the ROOT-file, but that should use different keywords in any case (if we ever enable it, I don't really see why we would, except for testing of the list-mode recon).

**Comment by NikEfth** [comment]
It might look redundant but this is a way of knowing the the GATE conversion gives you the number of rings and detectors that you think that you have simulated.

**Comment by KrisThielemans** [comment]
redundancy is good for checking consistency of course. I'd be inclined to make them optional (and flag that in the doc of course).
In any case, if we keep them, we have to explicitly check consistency and throw an error if they aren't.
