### ISSUE TITLE
pass time-frame info via Bin

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#794]
#770 makes `BinNormalisation::get_bin_efficiency()` independent of time. The idea is to make the call simpler and more future proof. For instance, we want to use multi-layered detectors, multiple energy windows etc. It would not make sense to have to pass all this information to `get_bin_efficiency` etc.

This does imply though that the information needs to be stored in `Bin`. It should have a `time_frame` member etc. (as an index, not a float-pair), as it's a bin.

The question is then how to set this information. We have a constructor
https://github.com/UCL/STIR/blob/fe1af133aee5c44ce9fecd50993612f47d274b44/src/include/stir/Bin.h#L55-L56
Unfortunately, this has a default value, which will create confusion once we start to add multiple arguments. Indeed, @NikEfth has addressed this by removing them in #304 (see [here](https://github.com/UCL/STIR/blob/4a2be3211ea8f021570c5fd52aaf8aefc9abfe1b/src/include/stir/Bin.h#L50-L51).

To avoid too many conflicts, we think the best solution is to
- add `time_frame` private member and corresponding accessors in `Bin`, default it to 1
- set the time frame where it needs to be set. This is probably only here:
https://github.com/UCL/STIR/blob/fe1af133aee5c44ce9fecd50993612f47d274b44/src/listmode_buildblock/LmToProjData.cxx#L655-L656
which should become
```c++
bin.set_bin_value(1); 
bin.time_frame = current_frame;
get_bin_from_event(bin, record.event()); 
```

@NikEfth what do you think?

**Comment by NikEfth** [comment]
Yeah, this might be hard. 
I think that simplest is to cherry-pick a new PR with the Bin or any other class that you would like to use. 
If you let me know I can do it and then I will try to sort out any conflicts with the TOF branch. 

Maybe this is a strategy to reduce the size of that PR... (I hope not).
