### ISSUE TITLE
InputStreamFromROOTFileForCylindricalPET uses wrong conventions for blocks and buckets?

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#80]
Terminology in STIR (from Scanner.h) :
```
      \li \c crystal the smallest detection unit
      \li \c block several crystals are grouped in a block, this can be in
          3 dimensions (see layer). This information could be useful for finding the
          geometry of the scanner, but we would plenty more
          size info presumably.
      \li \c layer Some scanners have multiple layers of detectors to give
          Depth Of Interaction information
      \li \c bucket several \c blocks send detected events to one \c bucket.
          This has consequences for the dead-time modelling. For instance,
          one bucket could have much more singles than another, and hence
          presumably higher singles-dead-time.
      \li \c singles_unit (non-standard terminology)
          Most scanners report the singles detected during the acquisition.
          Some scanners (such as GE scanners) report singles for every crystal,
          while others (such as CTI scanners) give only singles for a 
          collection of blocks. A \c singles_unit is then a set of crystals
          for which we can get singles rates.
```
In [GATE CylindricalPET terminology](http://wiki.opengatecollaboration.org/index.php/Users_Guide_V7.2:Defining_a_system#CylindricalPET), this seems to lead naturally to
- Module = bucket
- submodule = block

with number of modules per RSector=1. (I think GATE would be able to have one extra level compared to STIR).

This seems consistent with `InputStreamFromROOTFileForCylindricalPET::get_num_axial_crystals_per_singles_unit`. However, this is different from other functions implemented in InputStreamFromROOTFileForCylindricalPET.inl, e.g.
```
int get_num_dets_per_ring() const
{
    return static_cast<int>( this->crystal_repeater_z * this->module_repeater_z *
                             this->submodule_repeater_z);
}
int get_num_axial_blocks_per_bucket_v() const
{
    return this->module_repeater_z;
}
int get_num_axial_crystals_per_block_v() const
{
    return static_cast<int>(this->crystal_repeater_z *
       this->module_repeater_z);
}
```
This seems to lead to some strange arrangement. I think the correct way is
```
int get_num_axial_blocks_per_bucket_v() const
{
    return this->submodule_repeater_z;
}
int get_num_axial_crystals_per_block_v() const
{
    return static_cast<int>(this->crystal_repeater_z );
}
```
@NikEfth what do you think?

Of course, I wouldn't know what to do with the RSector stuff.

**Comment by NikEfth** [comment]
Hi Kris, 
Alright so the get_num_dets_per_ring() looks clearly a bug to me, right now. They should been the "_y" components. 

And I also agree about the get_num_axial_blocks_per_bucket_v(). 
But then: 
`int get_num_axial_crystals_per_block_v()
{
return static_cast<int>(this->crystal_repeater_z * this->submodule_repeater_z);
}`

That looks better I think

**Comment by KrisThielemans** [comment]
I don't know about "_z" vs "_y". I thought that made sense in the original code.

I don't understand your suggestion for `get_num_axial_crystals_per_block_v`. Aren't the `repeater` variables saying how many of the items there are in the encompassing unit? So I'd have thought that my suggestion was correct (of course I thought that!)

**Comment by NikEfth** [comment]
**So the get_num_rings() and get_num_dets_per_ring() must flip. This is a bug.** 

GATE has one extra level which you have to choose were to merge. I have always considered: 
bucket = rsector
block = module+submodule

So num of blocks per bucket is the number of modules per rsector. So, the number of crystals per block is that product of the number of crystals in a submodule by the number of modules in that block.

**Comment by KrisThielemans** [comment]
ok. i think we don't see the bug because of the `CListModeDataROOT` constructor actually swaps them around when making the scanner.

to me, it makes most sense to do

bucket=rsector+module
block=submodule

but I don't know what that means for GATE. I don't really mind which one of these 2 we use, as long as we make it clear...

**Comment by NikEfth** [comment]
But an rsector moves around the FOV and circulates complete (most of the time). So you will end having e.g. 4 axial modules and 4 (transaxial modules in an rsector) * 48 (rsectors) = 192 buckets. Does this sound reasonable?

**Comment by KrisThielemans** [comment]
I'm a bit confused about what you're trying to say. sorry.

I don't know if an rsector can contain modules that both circle round and translate along the axis (we'd need that letting them correspond to buckets). but really, the only thing that matters here is it somehow corresponds to what GATE does with these things, and what STIR would do with them. 

As the Scanner doc says, the bucket stuff is mostly intended for dead-time modelling. In fact, right now STIR ignores all the block stuff, except in the ECAT7 dead-time modelling code. In the near future, STIR will think about blocks (using Parisa's stuff) in the projector. It'd be possible to let the projector think about "modules of blocks" (i.e. "buckets").

what does GATE do?

**Comment by NikEfth** [comment]
This image tries to describe the concept: 
http://wiki.opengatecollaboration.org/images/2/22/Depth-p4.jpg
Then the submodule is just a subdivision of the module.

**Comment by KrisThielemans** [comment]
nice figure. thanks.

question is if the rsector/module stuff has anbything to do with how GATE does dead-time modelling, or as that entirely flexible and you can specify that outside?
(I don't see why it'd be useful to merge submodule into a "block", unless a submodule might be a single PMT, but that wouldn't make sense with all the sharing going on)

**Comment by NikEfth** [comment]
The dead time 'level' is defined by the `Singles readout depth := `. 1=rsector,2= module etc. 
So, as long as the user has is 2 then 

> bucket=rsector+module
> block=submodule]

will check out
