### ISSUE TITLE
compute..Hessian.par file error

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#802]
currently has
```
    prior type := Quadratic Prior
    Quadratic Prior Parameters:=
      penalisation factor := 0.0
      only 2D:= 0
    END Quadratic Prior Parameters:=
```
but our keyword is still `Quadratic`

**Comment by robbietuk** [comment]
https://github.com/UCL/STIR/blob/84a000431372059707ca65cabadb8fc9eba1759a/examples/samples/compute_sqrt_Hessian_row_sum.par#L46-L50
Oops, missed it. PR coming.
