### ISSUE TITLE
BinNormalisationFromECAT8 broken

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#804]
I just get zeroes now as efficiencies. Probably since #672. <strike>I've tried to hard-code `get_calib_decay_branching_ratio_factor` to ``1`  but that doesn't help.</strike>

I guess similar problems for GEHDF5.

**Comment by danieldeidda** [comment]
On it!

**Comment by danieldeidda** [comment]
Are you running correct_projdata?

**Comment by KrisThielemans** [comment]
yes. output is just 0. (could be NaN possibly)

**Comment by danieldeidda** [comment]
It's happening because branching ratio was not set if I set it to 1 it works
