### ISSUE TITLE
BinNormalisation::set_up fails on ExamInfo equality again for ECAT8 norm

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#809]
as before, and `ExamInfo` printed are the same. This was when running the SIRF recon on NEMA data

**Comment by danieldeidda** [comment]
Does this happens only with this particular dataset?

**Comment by KrisThielemans** [comment]
It's the only one I tried. sorry.

**Comment by KrisThielemans** [comment]
This has now been resolved
