### ISSUE TITLE
Add PatlakPlot function for clarity

### ISSUE THREAD

**Issue by AnderBiguri** [UCL/STIR#820]
Currently PatlakPlot has n frames (`patlak_plot_sptr->get_time_frame_definitions().get_num_frames()`) and a starting frame (`patlak_plot_sptr->get_starting_frame()`), which can be any frame  (e.g. there can be 20 frames, and the starting one be frame 10).

Interestingly the first frames can generally be empty, as they are not used, so they dont exist. 

In any case, if you want to loop from first used to last used frame, the loops right now look like:

```
for(unsigned int frame_num=this->_patlak_plot_sptr->get_starting_frame();frame_num<=this->_patlak_plot_sptr->get_time_frame_definitions().get_num_frames();++frame_num)
```
 
I think it would be much cleaner and logical to have a function:

```
unsigned int
PatlakPlot::get_ending_frame() const    // or get_last_frame_number() or whatever you prefer. 
{
  return this->get_time_frame_definitions().get_num_frames();
}
```
That way for loops would be:
```
for(unsigned int frame_num=this->_patlak_plot_sptr->get_starting_frame();frame_num<=this->get_ending_frame();++frame_num)
```

It would make code much cleaner and easy to follow (particularly when bug hunting :) ) plus it does not break any compatibility as the other one is still valid. 

Happy to add it if you agree.

**Comment by KrisThielemans** [comment]
sure
