### ISSUE TITLE
STIR's include-path should be first

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#85]
At present, `include_directories` for some dependencies (such as Boost) occurs before the one for STIR (which is in `stir_dirs.cmake`). This means that if a dependency is found in the same location as an older version of STIR, unexpected compilation problems (or segmentation faults) can occur.

Presumably, the `include_directories` statement from `stir_dirs.cmake` needs to be moved first.

See also https://github.com/CCPPETMR/SIRF-SuperBuild/issues/28

**Comment by NikEfth** [comment]
Would like to confirm and add, that in the case you make install stir UCL_master a copy of the header in the installation path is made. If one later switch branches has also to manually remove those headers.

**Comment by rijobro** [comment]
This is still a problem, however it is addressed in #309.
