### ISSUE TITLE
Problem while re-reading an RDF file when EOF was reached

### ISSUE THREAD

**Issue by eliseemond** [UCL/STIR#86]
Currently, if one wants to limit the number of segments while reading the entire listmode file, some events might not be stored/displayed (via lm_to_projdata for example). This is crucial in the future addition of the time-of-flight capability where the listmode file will require to be re-read multiple times.

**Comment by eliseemond** [comment]
This is due to a bug in stir/IO/InputStreamWithRecords.inl::set_get_position.

This is a known bug of C++ https://stackoverflow.com/questions/16364301/whats-wrong-with-the-ifstream-seekg

**Comment by KrisThielemans** [comment]
Fixed in aa82cbe42ce4ad2ceab49150b2d0f8c4806e331e
