### ISSUE TITLE
SAFIRCListmodeInputFileFormat::can_read should not write errors

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#87]
At present, when a non-SAFIR listmode file is used, `SAFIRCListmodeInputFileFormat::can_read` will write warnings/error messages when it tries to parse the non-SAFIR listmode file.

suggested solution: modify `actual_do_parsing` to
```
bool actual_do_parsing(std::istream& input, bool write_warning = true)
```
and pass it to the `parse` call. (Obviously for all signatures). Then call it appropriately in `can_read`.

@jafische could you have a look?

**Comment by jafische** [comment]
Hi Kris, I will have a look, but can only do so starting in a week from now. Hope that's OK. Sorry for the delay.
