### ISSUE TITLE
Convert images to Bq/mL

### ISSUE THREAD

**Issue by ashgillman** [UCL/STIR#879]
This was discussed at the last SyneRBI hackathon and is an outstanding item. I assume this would be implemented here rather than SIRF?

I think @danieldeidda had done some work on this?

**Comment by KrisThielemans** [comment]
we have a whole project on this. I don't think we need a new issue?

**Comment by KrisThielemans** [comment]
https://github.com/UCL/STIR/projects/4

**Comment by ashgillman** [comment]
Indeed, I used the wrong search terms
