### ISSUE TITLE
BinNormalisation can error-out because of originating_system

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#892]
`ExamInfo::operator==` checks for `originating_system` but this is not uniquely defined .For instance, @evgueni-ovtchinnikov [reported a case](https://github.com/SyneRBI/SIRF/issues/926#issuecomment-844185647_) where `this->originating_system` was `2008`, and `p1.originating_system` was `Siemens mMR`.

@danieldeidda, shall we remove it from the comparison? `BinNormalisation` will check for `proj_data_info` anyway. If we do, we should document that we're not checking it.

**Comment by danieldeidda** [comment]
> 
> 
> `ExamInfo::operator==` checks for `originating_system` but this is not uniquely defined .For instance, @evgueni-ovtchinnikov [reported a case](https://github.com/SyneRBI/SIRF/issues/926#issuecomment-844185647_) where `this->originating_system` was `2008`, and `p1.originating_system` was `Siemens mMR`.
> 
> @danieldeidda, shall we remove it from the comparison? `BinNormalisation` will check for `proj_data_info` anyway. If we do, we should document that we're not checking it.

OK yes better to remove it

**Comment by danieldeidda** [comment]
> 
> If we do, we should document that we're not checking it.

You mean to write something in documentation? or to throw a warning message?

**Comment by KrisThielemans** [comment]
let's just add a bit of doxygen. Writing a warning is maybe ok, although we might see a lot of them. I guess I wouldn't, but feel free 😄
