### ISSUE TITLE
CMake Find ROOT

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#91]
we're currently using our own FindCERN_ROOT.cmake. However, ROOT supplies its own, see
https://root.cern.ch/how/integrate-root-my-project-cmake

Possibly we should use that file. Trouble is that you need to know where ROOT is before you can use it. In their example they rely on the env variable `ROOTSYS`. Not sure if that will always be defined. @NikEfth, do you know if this variable is required?

**Comment by NikEfth** [comment]
Hi Kris, 
I have met quite a few people working with ROOT and I  think that most have not made use of the ROOTSYS. Then would prefer to add root  in PATH and LD_LIBRARY_PATH. I don't know who well my script would work with ROOT6

**Comment by KrisThielemans** [comment]
Closing. this seems to introduce trouble for the user. Hopefully at some point ROOT will use CMake config mode...
