### ISSUE TITLE
Hessian_row_sum multithreading issues

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#935]
Using the `compute_sqrt_Hessian_row_sum` utility, not using approximate Hessian (uses Hessian_row_sum method). During the forward and backward projection operations, the code uses all 7 cores available, indicated by `INFO: Thread ***/7 calculating segment_num: 3, view_num: 231` where `***` changes at each INFO for all threads. At the end of the operations though, there is always only one core remaining. Likely this is due to an alocation of operations and the remaining core is slowed by other computer processes. Either that or I have a dud CPU core.

Anyway, I would have hoped the segment_num - view_num combinations were not prealocated and distribution continued until the pool of pending processes was closed.

Evidence:
```
[Cut to end]
INFO: Thread 1/7 calculating segment_num: 3, view_num: 260

INFO: Thread 1/7 calculating segment_num: 3, view_num: 261

INFO: Thread 1/7 calculating segment_num: 3, view_num: 262

INFO: Thread 1/7 calculating segment_num: 3, view_num: 263

INFO: Thread 1/7 calculating segment_num: 3, view_num: 264

INFO: Thread 1/7 calculating segment_num: 3, view_num: 265

INFO: Thread 1/7 calculating segment_num: 3, view_num: 266

INFO: Thread 1/7 calculating segment_num: 3, view_num: 267

INFO: Thread 1/7 calculating segment_num: 3, view_num: 268

INFO: Thread 1/7 calculating segment_num: 3, view_num: 269

INFO: Thread 1/7 calculating segment_num: 3, view_num: 270

INFO: Thread 1/7 calculating segment_num: 3, view_num: 271

INFO: Output image of sqrt Hessian row sum has been computed and saved as [Cut filename]
```

Relevant code
--------
https://github.com/UCL/STIR/blob/5f5fd2d745ec0f49b0fe1bc70ff57b7914519d42/src/recon_buildblock/PoissonLogLikelihoodWithLinearModelForMeanAndProjData.cxx#L919-L1061

**Comment by KrisThielemans** [comment]
relevant line is
https://github.com/UCL/STIR/blob/621154460e7f1bf6e0b82a08418663baacba945f/src/recon_buildblock/PoissonLogLikelihoodWithLinearModelForMeanAndProjData.cxx#L988

Looks like `runtime` doesn't mean what you might think as the doc says "get the value from `OMP_SCHEDULE` env variable", see e.g.
https://software.intel.com/content/www/us/en/develop/articles/openmp-loop-scheduling.html, which could default to `static` on some systems.

First try to set the env variable to `dynamic`. If that works, we'll have to change the code (could be in other places as well)

**Comment by robbietuk** [comment]
Setting `export OMP_SCHEDULE=DYNAMIC` fixed the problem as you mention. 

It appears that the `ViewSegmentNumbers` are a list with segments grouped together, containing all views (i.e. `[Views for Seg.1, Views for Seg.2,..., Views for Seg.13]`).  Using `export OMP_SCHEDULE=STATIC` divides this list into sublists based upon list position. As computing obeque projections is cheaper because of fewer ray traces, the core assigned to the higher segments finishs first.

I guess something recently did an update to change the default behaviour as `$OMP_SCHEDULE` was previously unset, which is why on my computer I have just noticed this issue.

This is also an issue for the distributable code:
https://github.com/UCL/STIR/blob/5f5fd2d745ec0f49b0fe1bc70ff57b7914519d42/src/recon_buildblock/distributable.cxx#L429

forward_projector:
https://github.com/UCL/STIR/blob/5f5fd2d745ec0f49b0fe1bc70ff57b7914519d42/src/recon_buildblock/ForwardProjectorByBin.cxx#L198

backprojector:
https://github.com/UCL/STIR/blob/5f5fd2d745ec0f49b0fe1bc70ff57b7914519d42/src/recon_buildblock/BackProjectorByBin.cxx#L207

BinNormalisation (2x):
https://github.com/UCL/STIR/blob/5f5fd2d745ec0f49b0fe1bc70ff57b7914519d42/src/recon_buildblock/BinNormalisation.cxx#L148
https://github.com/UCL/STIR/blob/5f5fd2d745ec0f49b0fe1bc70ff57b7914519d42/src/recon_buildblock/BinNormalisation.cxx#L195

PoissonLogLikelihoodWithLinearModelForMeanAndProjData.cxx 3 times

and  FBP2DReconstruction
https://github.com/UCL/STIR/blob/5f5fd2d745ec0f49b0fe1bc70ff57b7914519d42/src/analytic/FBP2D/FBP2DReconstruction.cxx#L295

Do we want to change/test these to `[...] schedule(dynamic)`?

**Comment by KrisThielemans** [comment]
> Do we want to change/test these to `[...] schedule(dynamic)`?

yes please. This will currently be system/openmp library specific. For the views/segments, the `dynamic` one is the only that makes sense (as work-load is very uneven).
