### ISSUE TITLE
Conda installation doesn't work

### ISSUE THREAD

**Issue by JacksonFurrier** [UCL/STIR#942]
I tried to use STIR as a reconstruction for my algorithm but, following the [steps](http://stir.sourceforge.net/wiki/index.php/Installing_STIR_with_conda) here I've got the following error by simply importing it in python from the conda env.

"Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import stir
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\JohnDoe\miniconda3\envs\stirenv\lib\site-packages\stir.py", line 15, in <module>
    from _stir import *
ImportError: DLL load failed while importing _stir: The specified module could not be found."

Inspecting it further the conda environment doesn't contain the any stir DLL. What can be the problem?

EDIT: Tried to compile it with boost 1.77 with CMake  3.21.0 and with msvc 19.29.30038.1 and it fails with
"STIR\src\test\test_multiple_proj_data.cxx(39): error C2039: 'setw': is not a member of 'std'"

**Comment by jvavrek** [comment]
I had this same issue building from source. I added
```c++
#include <iomanip>
```
to the top of the file and was able to build.

**Comment by KrisThielemans** [comment]
The `<iomanip>` problem was solved in 86908818758304d03cfe2a9e78a6eb646161a929 on `master`.

The `conda` problem I'm not sure. I can assure you that the stir dll is present in the package. I suspect it's something else in your conda environment. I don't have conda at present on my Windows machine due to continuing problems with conda unfortunately.

**Comment by JacksonFurrier** [comment]
Seems like the problem is gone. I've changed os from Win11 + WSL 2.0 to arch64 and it is all fine and working, thank you.

**Comment by KrisThielemans** [comment]
It actually works fine for me on Win10 (Powershell). haven't tried conda on WSL.
