### ISSUE TITLE
Logcosh parabolic surrogate

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#955]
@robbietuk should this return `true`?
https://github.com/UCL/STIR/blob/877511b607a90cbc3c3faebf9fa4e2dc3ea72f1b/src/include/stir/recon_buildblock/LogcoshPrior.h#L112-L113

**Comment by robbietuk** [comment]
Yes it should. It requires the DiscretisedDensity values in the surrogate calculation. https://github.com/UCL/STIR/blob/877511b607a90cbc3c3faebf9fa4e2dc3ea72f1b/src/recon_buildblock/LogcoshPrior.cxx#L438-L505

QP is the other prior with this functionality and it does need an input but does not rely on it for DiscretisedDensity values, but does need the shape etc. 

https://github.com/UCL/STIR/blob/877511b607a90cbc3c3faebf9fa4e2dc3ea72f1b/src/recon_buildblock/QuadraticPrior.cxx#L497-L566
