### ISSUE TITLE
SAFIR example file or code trouble

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#976]
```
cd  examples/SAFIR-listmode-virtual-scanner/
list_lm_events listmode_input_SAFIR.par |head
<snip>
INFO: Setting energy window keys as in STIR3.0
CListModeDataSAFIR: opening file point_5.clm.safir
Scanner: SAFIR_20
Time 1
Time 29
Time 58
Time 83
Time 112
Time 139
Time 170
Time 195
Time 223
Time 249
Time 279
Time 308
Time 331
Time 364
<snip>
Time 9811
Time 9835
Time 9862
Time 9892
Time 9918
Time 9942
Time 9967
Time 9995
Time 6482
Time 6675
Time 2483
Time 627
Time 5738
Time 2154
Time 4585
Time 3413
Time 1247
Time 4554
Time 1681
Time 822
Time 3065
<snip>
```
Something clearly wrong with these time stamps. @jafische any idea what causes this?

Also, it turns out that the SAFIR reader fails when pointing to a file in separate directory (i.e. `list_lm_events somewhere/listmode.par`).

**Comment by KrisThielemans** [comment]
@emikhay @jafische could you should some light on this. Likely the file (or just its timestamps) is corrupted after a certain point

**Comment by jafische** [comment]
@KrisThielemans, I will have a look. Likely as you suggest, a corrupted file.

**Comment by jafische** [comment]
@KrisThielemans: So indeed it seems to be a file that is corrupt in its time stamps towards the end. I can not fix it because I do not have the raw data at hand, but I will try to find a replacement next week.

**Comment by KrisThielemans** [comment]
ok. As we currently have no tests that depend on the timestamp, I'd be happy with a PR that adds a README in the relevant directory documenting this issue. (Adding binary files is always a pain). what do you think?

**Comment by jafische** [comment]
So I decided that his could actually be fixed by truncating the file as
only the end of it has this problem. It's done and a pull request is
waiting. If you want it otherwise, please let me know.


Am 25.01.22 um 15:23 schrieb Kris Thielemans:
