### ISSUE TITLE
Scatter simulation 

### ISSUE THREAD

**Issue by mele-y** [UCL/STIR#982]
Is there any paper investigating the accuracy of the scatter simulation funtion in STIR compared to the Monte Carlo method in GATE?

**Comment by robbietuk** [comment]
This is probably a question for the users list (stir-users@lists.sourceforge.net) but ["Evaluation of the single scatter simulation algorithm implemented in the STIR library"]( https://ieeexplore.ieee.org/document/1466455) is one that compares the scatter simulation to SimSET (another Monte Carlo simulation package). You can also check the [STIR website](http://stir.sourceforge.net/) publications section for more STIR works.
