### ISSUE TITLE
CMake checking for std::unique_ptr doesn't honor CXX_STANDARD

### ISSUE THREAD

**Issue by KrisThielemans** [UCL/STIR#983]
found by @robbietuk 

error:
```
 CMake Error at src/CMakeLists.txt:199 (message):
   Problems compiling with std::unique_ptr.  Giving up.
```
Code is
https://github.com/UCL/STIR/blob/e8d250feb8dfbb00fcb25ab63d08282496ac6751/src/CMakeLists.txt#L191-L196

Underlying cause is that the C++ standard hasn't been passed to the compiler when using `check_cxx_source_compiles`.

However, we try to handle this:
https://github.com/UCL/STIR/blob/e8d250feb8dfbb00fcb25ab63d08282496ac6751/src/CMakeLists.txt#L174-L184

This apparently fails for @robbietuk

**Comment by KrisThielemans** [comment]
@robbietuk  can you give your CMake version?

[CMake doc on CheckCXXSourceCompiles](https://cmake.org/cmake/help/latest/module/CheckCXXSourceCompiles.html) seems to imply we have a problem in https://github.com/UCL/STIR/blob/e8d250feb8dfbb00fcb25ab63d08282496ac6751/src/CMakeLists.txt#L175 and https://github.com/UCL/STIR/blob/e8d250feb8dfbb00fcb25ab63d08282496ac6751/src/CMakeLists.txt#L178
which should set `CMAKE_REQUIRED_FLAGS`, not `CMAKE_REQUIRED_DEFINITIONS`

**Comment by robbietuk** [comment]
```
$cmake -version
cmake version 3.21.3
```

**Comment by KrisThielemans** [comment]
then I don't understand
https://cmake.org/cmake/help/latest/policy/CMP0067.html

**Comment by robbietuk** [comment]
Disabling `check_cxx_source_compiles` and the conditional statement, but keeping 
```
option(STIR_USE_BOOST_SHARED_PTR "Use boost::shared_ptr as opposed to std::shared_ptr (not recommended)" OFF)
     mark_as_advanced(STIR_USE_BOOST_SHARED_PTR)
```
allows for configuration, generation and compilation. The issue must be related to `check_cxx_source_compiles`?

**Comment by KrisThielemans** [comment]
are you saying you have to set `STIR_USE_BOOST_SHARED_PTR=ON` for your config (gcc 4.9.2)? It's probably just a too old compiler.

In any case, possibly you can configure with the original code and find a file somewhere which says how `check_cxx_source_compiles` is running the compiler. If it doesn't make any attempt to add a flag for C++11, either it's a bug, or  CMake has detected it's gcc 4.9.2. and does some special handling.

**Comment by robbietuk** [comment]
I think it would set `STIR_USE_BOOST_SHARED_PTR=OFF`?

**Comment by KrisThielemans** [comment]
ok, I misunderstood you then. That doesn't have anything to do with `unique_ptr` (we gave up trying to use Boost replacements for that, as it didn't work anyway)
