### ISSUE TITLE
GHA: Need for test with different c++ versions

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#988]
This came up in a discussion today so making a reminder issue. I think we are only testing c++11 builds with GHA. https://github.com/UCL/STIR/blob/master/.github/workflows/build-test.yml

We found that with some MacOS clang versions, with c++14/c++17/c++20, were producing build warnings or errors in https://github.com/UCL/STIR/issues/856, which was fixed in https://github.com/UCL/STIR/pull/987

**Comment by KrisThielemans** [comment]
This was completed a while ago.
