### ISSUE TITLE
`SymmetryOperations_PET_CartisianGrid` have significant code duplication

### ISSUE THREAD

**Issue by robbietuk** [UCL/STIR#995]
[`SymmetryOperations_PET_CartisianGrid.cxx` ](https://github.com/UCL/STIR/blob/master/src/recon_buildblock/SymmetryOperations_PET_CartesianGrid.cxx) is entirely duplication of the parent classes methods [`SymmetryOperation.cxx`](https://github.com/UCL/STIR/blob/master/src/recon_buildblock/SymmetryOperation.cxx)

Except the `SymmetryOperation_PET_CartesianGrid_swap_zq::transform_proj_matrix_elems_for_one_bin()` for some reason, which misses some preprocessing.
https://github.com/UCL/STIR/blob/06963f9292d7e9cbfe5b3ffa8d49eb7a533ec6eb/src/recon_buildblock/SymmetryOperations_PET_CartesianGrid.cxx#L359-L372
______
We can probably just remove the redefinitions of the methods and rely on those defined in `SymmetryOperation`? I can do this for the TOF symmetry changes or in STIR master?

**Comment by KrisThielemans** [comment]
> Except the `SymmetryOperation_PET_CartesianGrid_swap_zq::transform_proj_matrix_elems_for_one_bin()` for some reason, which misses some preprocessing.

hmmm. that seems to be a bug then. I guess the `bin` is currently never used after the transformation, as otherwise we'd have seen this 22 years ago...

More comments in  #996

**Comment by KrisThielemans** [comment]
@robbietuk maybe you could put up a PR to fix `SymmetryOperation_PET_CartesianGrid_swap_zq`? I'll mark this one as "won't fix" and close (far too many open issues...)
